### ISSUE TITLE
Nested Scrollbable Tab Views?

### ISSUE THREAD

**Issue by reactor81** [happypancake/react-native-scrollable-tab-view#107]
I need one of the children to have it's own scrollable tab view. Like a sub menu of tabs.

It doesn't seem like this is supported? The sub children tabbar renders but none of the child elements render. 

Any pointers to what I might need to change in your code to get this to work?

Thanks

**Comment by reactor81** [comment]
I guess sliding left/right in this child component that has it's own scrollable tab view would ideally only scroll that component. Hmm. get's a little finicky I guess. Thoughts?

**Comment by skv-headless** [comment]
https://github.com/brentvatne/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/FacebookTabsExample.js#L18
It might be helpful. Could you make a photo of your interface? I'm not sure that I understood you correct?

**Comment by reactor81** [comment]
Hi, I actually have 2 rows of tabs. These are some online examples that I think show the idea:

http://cdn.makeuseof.com/wp-content/uploads/2011/05/image-146.jpg?77608b

https://help.comodo.com/uploads/Comodo%20KoruMail/4b9a3ae6e2cbd6008bec704ed0edea34/5eac818f1e1c4adc19d335055b06586b/7ea73eb6802c802d11af9131b08f5d7c/km_sysconfig50.png


It is like this in JSX

<ScrollableTabView>
    
   <ScrolableTabView>
          <SomeChild1 />
           <SomeChild2 />
  </ScrollableTabView>

  <SomeChild3 />
  <SomeChild4 />
</ScrollableTabView>

**Comment by gadiel** [comment]
any updates on this?

**Comment by zjhsd2007** [comment]
this issue is still there

**Comment by alzalabany** [comment]
any updates ?

**Comment by pengfeiyan** [comment]
@reactor81 
I have the same issue.  "The sub children tabbar renders but none of the child elements render."
had you resolved this problem? would you like to help me?
 please give me some advise. 
thank you very much.

**Comment by lwddsy** [comment]
i have the same problem, 
please give me some advise.
thank you very much.

**Comment by davyuu** [comment]
Any fixes or workarounds?

**Comment by tnagorra** [comment]
I have the same problem, but only the first two children tabviews do not render.

**Comment by 337240552** [comment]
I have the same problem, the first nested child tabview does not render

**Comment by sandropoluan** [comment]
Still no update?

**Comment by JackuyLiu** [comment]
what's the fucking reason,this issue keep existing for 3 years?

**Comment by ptomasroos** [comment]
Closing as this issue is very old, feel free to open a new issue if its still happening in the latest release
