### ISSUE TITLE
Error on iOS: invalid number value (infinite) in JSON write

### ISSUE THREAD

**Issue by peter4k** [happypancake/react-native-scrollable-tab-view#112]
When loading the page with scrollable-tab-view, app terminates with objective-c error (not js error): Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid number value (infinite) in JSON write'.

Before app terminates there are warnings: ios[5692:60505] -[<CALayer: 0x7fe1916ee6d0> display]: Ignoring bogus layer size (15576890575604482885591488987660288000.000000, 17.000000), contentsScale 2.000000, backing store size (31153781151208965771182977975320576000.000000, 34.000000)

Looks like this is a bug while using this component inside "NavigatorIOS"

**Comment by ncammarata** [comment]
ever find a fix for this?

**Comment by akic4op4** [comment]
RCTJSONStringify() encountered the following error: Invalid number value (infinite) in JSON write   

this issue is so relatable..

I get this error when rendering ScrollablTabView in a View!

It got crash :(

**Comment by skv-headless** [comment]
Sorry for ignoring this issue. Could you give me code snippet to reproduce this issue?

**Comment by peter4k** [comment]
I am sorry I chose to not use this library for my app because I have to use NavigatorIOS. I don't think I still have the code.
But I think if you use the scroller tab view insider a NavigatorIOS you will get the error.
Hope this can help!

**Comment by symmetriccurve** [comment]
the error occurs when you try to add a string('deg') to a number(0-360). I'm expecting the string deg is the bug.

**Comment by octohedron** [comment]
I take the error comes from having a `NavigatorIOS` with a `ScrollableTabView` inside? 

Surprisingly in my case it only happens when first mounting the component, then it gets fixed if I dismiss it and navigate with the parent `NavigatorIOS` and come back.

Anyone found a workaround?

**Comment by ptomasroos** [comment]
Closing as this issue is very old, feel free to open a new issue if its still happening in the latest release
