### ISSUE TITLE
flex: [number] not work in ScrollView

### ISSUE THREAD

**Issue by L-Jovi** [happypancake/react-native-scrollable-tab-view#133]
I have some jsx below

```
<View>
  <ScrollableTabView>
    <ScrollView>
      <CustomView></CustomView>
    </ScrollView>
  </ScrollableTabView>
</View>
```

all above jsx tag have style `flex: 1`, and I want to use flexbox layout in `CustomView` tag, but I find that `flex: [number]` can't work.
however, when I specify `height` css property of `CustomView` component, all things back to normal.

if I don't know `height`, how could I use `flex: [number]` in my `CustomView`?

thanks for your time.

**Comment by skv-headless** [comment]
I'm not sure that you can use flex for elements inside ```ScrollView``` maybe someone will give better answer.

**Comment by lrettig** [comment]
I'm having this same problem

**Comment by npomfret** [comment]
Same here.  I notice that if I put a ListView in a team it nicely uses up all the available space.  But if I put a view in there with `flex: 1` it does nothing.  Anyone got a solution?

**Comment by luancuba** [comment]
I've "solved" it wrapping the scrollview with a view and put flex on it (view).

**Comment by ptomasroos** [comment]
Closing as this issue is very old, feel free to open a new issue if its still happening in the latest release
