### ISSUE TITLE
Issue: Implementing react-native-router-flux with ScrollableTabView

### ISSUE THREAD

**Issue by miknonny** [happypancake/react-native-scrollable-tab-view#155]
I have been able to implement Router on ScrollableTabView. 
But when i try to nest it on one of the tabs. nothing shows up except for the tabs. I do not see the router component in tabs.

...

``` javascript
...
return (
      <View style={styles.container}>
       <ScrollableTabView initialPage={0} renderTabBar={() => <TabBar />}>
         <ScrollView tabLabel="ios-videocam-outline" style={styles.tabView}>
            <Router hideNavBar={true} wrapRouter={true}>
              ...
            </Router>
         </ScrollView>
      </ScrollableTabView>
     </View>
)
```

I really need help.

**Comment by faceyspacey** [comment]
+1 I'm also having difficulty implementing this with react-native-router-flux. 

@miknonny do you have a sample app I can help you with.

**Comment by miknonny** [comment]
@faceyspacey  The Router component should be a top level component and should not be nested in ScrollableTabView like i did above instead it should be the other way round.

Right implementation.
```javascript
...
return (
      <Router hideNavBar={true} >
        <Schema name="default" sceneConfig={false} />
        <Route name="tabs" component={ScrollableTabComponent} initial={true} /> 
      </Router>
    )
  }
```

**Comment by faceyspacey** [comment]
So did that work for u? Any caveats?

**Comment by miknonny** [comment]
Yes it worked perfectly. ScrollableTabView should be a prop of Route component set as the initial route. so when the app loads, the initial route is the ScrollableTabView.

**Comment by faceyspacey** [comment]
what about further routes--should they all be nested within this route for ScrollableTabView to show?

**Comment by miknonny** [comment]
@faceyspacey No it should not. Lets assume that a you want to navigate to settings from 'Tab 1'  of ScrollableTabView. Your Router component would look something like this.


```javascript
  <Router hideNavBar={true>
        <Schema name="default" sceneConfig={false} />
        <Route name="tabs" component={TabbedComponent} initial={true} />
        <Route name="settings" component={Settings} title="Settings" hideNavBar={false} />
           <Router>
                <Route name="profile" component={Profile} title="About"/>
                <Route name="account" component={Account} title="Account"/>
            </Router>
      </Router>
```

Then you can call Actions.settings({title: 'Settings', data: 'whatever'}) from `Tab 1` to go to Settings. That is the way i did it. 
Note that `settings`  method on `Action` refers to the `Route` name property.

After settings, further routes down it will be nested under like `Profile` and `Account`

**Comment by faceyspacey** [comment]
yea, but the TabbedComponent will disappear when you go to the settings route. It only exists on the "tabs" route, and then within it you cant change pages by using regular `Actions`, e.g: `Actions.login()`. 

So you essentially lose the ability to control routing within it. In short, we need to make a deeply integrated tab component of our own, similar to the one they already have:

https://github.com/aksonov/react-native-router-flux/blob/master/TabBar.js

This is also the suggestion I got from the react-native-router-flux creator:

https://github.com/aksonov/react-native-router-flux/issues/257


It doesn't seem too hard. If we make it a plugin to react-native-router-flux (which is more popular), that will surely grow the popularity of this widget, which will be good because it will mean more support overall.

**Comment by miknonny** [comment]
@faceyspacey that would be great!. I must say i am not that experienced but i am willing to put out time for it and learn.

**Comment by faceyspacey** [comment]
honestly, it's looking like this component is a perfect match with ex-navigator that the router uses. Like, the router is basically unnecessary for an app built with this sexy scrollable pages. see what im saying. give every page its own navigator and done. that's what I'm doing for now. 

...cuz the reality is: it will require a lot more than just what I and that other guy described above. in addition, we gotta hi-jack their action mechanism to use the one of this scrollable component, but only if you're moving between top level routers that correspond to tabs, and then for all sub pages use the standard one of that flux router. ..It's basically really messy to combine the 2. I'm not saying it can't be done--it can be done. But it won't be fun and the other router really isn't made for this. It's made for a stack of pages pushed and popped blindly--it doesn't perceive a bunch of top level pages floated horizontally in one very wide view. 

So anyway, for now I think im gonna use plain ex-navigator.

**Comment by KevinHu2014** [comment]
@miknonny So is there still issues on implement Router on ScrollableTabView?

**Comment by luisfuertes** [comment]
Im using this with `"react-native": "0.29.1",` and `"react-native-router-flux": "^3.30.2",` 

Somebody know how can i integrate ScrollableTabView with RNRF? When i push other view my tabBar disappear from botton.

**Comment by juanpujol** [comment]
Is there a complete example of this integration? Thanks.

**Comment by leonacky** [comment]
Hi, 
I have an issue on iOS.
I'm using `react-native-scrollsble-tab-view` inside router/scene from `react-native-router-flux`, I have 4 tabs and the first tab contain scrollable-tab-view, its work fine on start but when I try to click on other tab of 4 tabs and go to first tab again, I see that scrollable-tab-view is not working, I can't swipe, can't click the tabs.
This is main has 4 tabs:
`<Router createReducer={reducerCreate} sceneStyle={{backgroundColor:'#f7f7f7'}} hideNavBar={true}>
                <Scene key="modal" component={Modal} >
                    <Scene key="root" hideNavBar={true}>
                    <Scene key="launch" component={Launch} title="Launch" initial={true} style={{flex:1, backgroundColor:'transparent'}}/>
                    <Scene key="tabbar" tabs={true} hideNavBar={true}>
                        <Scene key="tab1" hideNavBar={false} initial={true} component={HomeScreen} title="Tab #1" icon={TabIcon}/>
                        <Scene key="tab2" component={SearchScreen}  hideNavBar={false} title="Tab #2" icon={TabIcon}/>
                        <Scene key="tab3" hideNavBar={false} component={NotificationScreen} title="Tab #3" icon={TabIcon}/>
                        <Scene key="tab4" hideNavBar={false} component={ProfileScreen} title="Tab #4" icon={TabIcon}/>
                    </Scene>
                    <Scene key="error" component={Error}/>
                    </Scene>
                </Scene>
            </Router>`

First tab is `HomeScreen` contain `scrollable-tab-view`

`<ScrollableTabView
                style={{marginTop:60}}
                initialPage={0}
                renderTabBar={() => <HomeTabBar />} >
                <HomeTabC2CScreen style={styles.tabView} tabLabel="ios-list" />
                <HomeTabC2CScreen style={styles.tabView} tabLabel="ios-people" />
                <HomeTabKhuyenMaiScreen style={styles.tabView} tabLabel="ios-notifications" />
            </ScrollableTabView>`

Pls help me how to fix it
Thanks

**Comment by work2fork** [comment]
Same issue for using it inside `react-native-router-flux`

**Comment by Naoto-Ida** [comment]
I have a similar situation going on:

```js
<Scene
  initial
  key='tabWithTabsInside'
  component={() => (
    <View>
      <ScrollableTabView renderTabBar={() => <DefaultTabBar />}>
        <Scene key='tab1InsideTab1' />
        <Scene key='tab2InsideTab1' />
        <Scene key='tab3InsideTab1' />
      </ScrollableTabView>
    </View>
  )}
/>
```

The tab `tabWithTabsInside` created by `react-native-router-flux` is rendering, but the tabs inside of it (`react-native-scrollable-tabview` isn't rendering.

**Comment by ptomasroos** [comment]
Closing as this issue is very old, feel free to open a new issue if its still happening in the latest release
