### ISSUE TITLE
Cannot convert argument to string: Error Domain=RCTErrorDomain Code=0 

### ISSUE THREAD

**Issue by ajoshdee** [happypancake/react-native-scrollable-tab-view#198]
Hi I seem to be having this error when putting it into another view
Cannot convert argument to string: Error Domain=RCTErrorDomain Code=0 "Invalid number value (NaN) in JSON write" UserInfo={NSLocalizedDescription=Invalid number value (NaN) in JSON write}

**Comment by tomauty** [comment]
Yeah, I receive this too. I'm putting the tabview inside of an image.

**Comment by xushuwei202** [comment]
+1

**Comment by timsmith339** [comment]
@tomauty You're the man

**Comment by ptomasroos** [comment]
Closing as this issue is very old, feel free to open a new issue if its still happening in the latest release
