### ISSUE TITLE
peerDependencies does not meet RC versions.

### ISSUE THREAD

**Issue by bcalik** [happypancake/react-native-scrollable-tab-view#216]
I have `react-native 0.23.0-rc1` installed, but peer dependency does not meet it and gives an error below:

`npm WARN EPEERINVALID react-native-scrollable-tab-view@0.4.0 requires a peer of react-native@>=0.20.0 but none was installed.`

**Comment by skv-headless** [comment]
Have you installed it from github? What react-native version in package.json(I mean react-native inside node_modules)?
Probably I can remove peerDependencies but I need to know why it doesn't work in your case.

**Comment by bcalik** [comment]
`node_modules/react-native/package.json` file says:
```
"version": "0.23.0-rc1"
```

and my own package.json file:
```
"react-native": "^0.23.0-rc1",
"react-native-scrollable-tab-view": "^0.4.0",
```

**Comment by skv-headless** [comment]
I like npm so much. https://github.com/npm/npm/issues/8854 I found this.

**Comment by skv-headless** [comment]
I use ```peerDependencies``` because 0.3.x is not compatible with react >=0.20. It might cause problems.
