### ISSUE TITLE
Cleanup Access to Children

### ISSUE THREAD

**Issue by cancan101** [happypancake/react-native-scrollable-tab-view#236]
[Right now this code is used to access children](https://github.com/brentvatne/react-native-scrollable-tab-view/blob/2aa6570024624395f359c2fb689583362c10eb91/index.js#L177-L179):

``` js
  _children() {
    return React.Children.map(this.props.children, (child) => child);
  },
```

Consider changing to `React.Children.toArray(this.props.children)`.

Further the whole concept can be eliminated and the extra array creation can be avoided. I assume this was here for [some sort of legacy reasons](https://github.com/brentvatne/react-native-scrollable-tab-view/commit/321194523af7f7db467ee487fb0c1455d17137d2).

Lines like this:

``` js
this._children().map((child) => child.props.tabLabel),
```

can then be changed to:

``` js
React.Children.map(this.props.children, (child) => child.props.tabLabeld);
```

**Comment by skv-headless** [comment]
```React.Children.map(this.props.children, (child) => child.props.tabLabeld);``` to long imo. But ```React.Children.toArray(this.props.children)``` is good.

**Comment by cancan101** [comment]
Why introduced the intermediate array?  Is the abstraction worth it? I would argue there is both a performance and a readability penalty to having it.

**Comment by skv-headless** [comment]
As you wish and don't see a reason to argue about this.
