### ISSUE TITLE
ScrollableTabBar glitch/lag on thumb up

### ISSUE THREAD

**Issue by olup** [happypancake/react-native-scrollable-tab-view#297]
The scrollableTabBar from your example gets glitchy on my phone : it scrolls fine as i scroll with my thumb between two view - but on the end of the gesture, when my thumb leave the screen and the view finish to scroll, the tab bar is not following. It lags and with some delay just jumps to the right tab.

I've ben screening the process with systrace and couldn't find much thing valuable there. I have a couple of frames lost from time to time, but the lag happens non regardingly. FPS stays at 60 and js ftps never get under 40. 

Again, everything is super smooth as long as i keep my thumb driving. Only the release triggers visual lag. The rest of the scrollable view is absolutely smooth whatsoever.

Does it look like a performance issue or is `this.props.scrollValue.addListener(this.updateView);` stopping to get datas on thumb release ?

**Comment by sudosiyang** [comment]
I have the same problem only when the every page has long listView, the press the tab the active will visual lag. Keeping the thumb driving the tab avtive wil smooth

**Comment by skv-headless** [comment]
ios or android? Could you make video? Default tab bar or scrollable?

**Comment by sudosiyang** [comment]
![2016-06-08 10_17_26](https://cloud.githubusercontent.com/assets/5602140/15880697/611964ea-2d62-11e6-9aad-85be82b741b4.gif)

**Comment by skv-headless** [comment]
Do you mean delay after selecting tab?

**Comment by skv-headless** [comment]
@sudosiyang what about yours profile monitor? In your example I see couple of problems. I think in your js thread fps is really low. Play with ListView props and lazy content loading. https://facebook.github.io/react-native/docs/performance.html

**Comment by skv-headless** [comment]
@olup look at android example in master. Is this animation good?

**Comment by olup** [comment]
@skv-headless Well, the example online sounds ok - a bit behind but that's probably due to emulation or something.
But the example has empty panels. On my app, there is a full ListView with pics and text. I'll try to send a video later today to show you what i mean, taken straight from my android phone.

**Comment by olup** [comment]
there is a gif of my screen, you can probably see what i am talking about. Smooth moves when i am thumb-controlling, jumps when i thumb up. However, panels run fine : 

![ezgif com-resize](https://cloud.githubusercontent.com/assets/13785588/15886047/0f94c9ea-2d5b-11e6-9aea-e47b68ae8573.gif)

**Comment by olup** [comment]
Actually, the bug happens only on tab change : letting the thumb go up when we stay on the same page does not make it happen. It probably has to do with rerender.

**Comment by Coobers** [comment]
It's caused by re-render after animation starts. 
If you comment out last line in function goToPage (this.setState({currentPage: pageNumber, })) in package index.js it'll run without a glitch if you use defaulttabs.

**Comment by olup** [comment]
Thank you very much @Coobers, however the solution you provide does not work.

But based on same idea I commented out the onPageSelected props of the android ViewPager. And that works.
Problem is we then loose present page tracking. But on the right track ! Next step is to find out how to tweak _updateSelectedPage to prevent it from rerender. I'll post it here once i find my way.

**Comment by olup** [comment]
So, ended up adding a function to check tab changes from offset and position : 

```
_checkTabFromPosition(pos,off){
    if (off!=0 || pos == this.pos) return;
    this._updateSelectedPage(pos);
    this.pos=pos;
  },
```

then, i take out the `onPageSelected` prop of `ViewPagerAndroid` and i add a call to my function in the `onPageScroll` prop as such :

```
onPageScroll={(e) => {
           const { offset, position, } = e.nativeEvent;
           this._updateScrollValue(position + offset);
           this._checkTabFromPosition(position,offset);
         }}
```

So now re-render wil happen only after the scroll animation is done !

**Comment by Coobers** [comment]
@olup  You are correct. I actually change state to object variable. I didn't ran it on android, but on ios I have few more problems with efficiency, I think I'll push a PM or make a fork with all the changes soon.
Most important thing is that render cannot run during animation, since it'll lag animation like crazy (it includes views and selection of tabs).

**Comment by sudosiyang** [comment]
@skv-headless I have play with ListView props and lazy content loading but when the list too long >100 the js fps is really low,and the debug is false.

**Comment by hotaryuzaki** [comment]
> So, ended up adding a function to check tab changes from offset and position :
> 
> ```
> _checkTabFromPosition(pos,off){
>     if (off!=0 || pos == this.pos) return;
>     this._updateSelectedPage(pos);
>     this.pos=pos;
>   },
> ```
> 
> then, i take out the `onPageSelected` prop of `ViewPagerAndroid` and i add a call to my function in the `onPageScroll` prop as such :
> 
> ```
> onPageScroll={(e) => {
>            const { offset, position, } = e.nativeEvent;
>            this._updateScrollValue(position + offset);
>            this._checkTabFromPosition(position,offset);
>          }}
> ```
> 
> So now re-render wil happen only after the scroll animation is done !

Are you solved the issue?
Hey where is _updateScrollValue function????????
