### ISSUE TITLE
Android: when tabView1 contains tabView2, initialPage has nothing

### ISSUE THREAD

**Issue by xQuotes** [happypancake/react-native-scrollable-tab-view#321]
Android: when tabView1 contains tabView2, initialPage has nothing:

![os](https://cloud.githubusercontent.com/assets/19151604/16296329/49c22ce8-395e-11e6-8882-d83b7145b885.png)

but when I swipe screen, It shows!
![a11](https://cloud.githubusercontent.com/assets/19151604/16296623/a6c717c2-395f-11e6-8af0-3202a96e425a.jpg)

iOS works well!

**Comment by xiaobuu** [comment]
+1

**Comment by tomauty** [comment]
Yeah, I've noticed this too.

**Comment by summersky92** [comment]
i think there is a hack solution here:  https://github.com/skv-headless/react-native-scrollable-tab-view/issues/215
