### ISSUE TITLE
Run in dev "react-native-scrollable-tab-view": "../..",

### ISSUE THREAD

**Issue by ButuzGOL** [happypancake/react-native-scrollable-tab-view#357]
How you do development
I see this link
https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/package.json#L11
but it copy/paste to node_modules and when I want to change in src you should always do npm i ?

**Comment by skv-headless** [comment]
I usually make changes in ```node_modules``` files then copy them. I think it is possible to make symlink into ```node_modules``` in postinstall hook. But I don't know what is right solution for that. Any suggestions are welcome.

**Comment by ButuzGOL** [comment]
As I understand rn(watchman) has problems with symelinks so temporary solution
```
node_modules/react-native/packager/packager.sh --projectRoots /Users/butuzgol/Playground/react-native-scrollable-tab-view/,/Users/butuzgol/Playground/react-native-scrollable-tab-view/examples
```
and in 

```var ScrollableTabView = require('../index');```
