### ISSUE TITLE
Smooth scrolling issue when ListView is put inside Scrollable Tab View

### ISSUE THREAD

**Issue by brookehurford** [happypancake/react-native-scrollable-tab-view#358]
I have added a ListView inside a ScrollableTabView on iOS. When doing this it messes with the smooth scrolling of the ListView. Here is a video showing the problem:

https://www.youtube.com/watch?v=c4kV4tByAyg

Here is my code:

```
<ScrollableTabView 
              tabBarBackgroundColor="white"
              tabBarUnderlineColor="#E51937"
              tabBarActiveTextColor="black"
              tabBarTextStyle={{fontSize: 14, paddingTop: 5}}>
                <ListView
                  tabLabel="List"
                  contentContainerStyle={styles.list}
                  ref="listview"
                  renderFooter={this._renderFooter}
                  initialListSize={15}
                  pageSize={15}
                  // onEndReached={this.loadMore}
                  // onEndReachedThreshold={1}
                  scrollRenderAheadDistance={10}
                  onScroll={this.onScroll}
                  dataSource={dataSource}
                  renderRow={this.renderPlace}
                  style={[styles.listView,styles.scrollContainer]}
                  />
                <View style={styles.flexContainer} tabLabel="Map">
                  {this.getMap()}
                </View>
            </ScrollableTabView>
```

**Comment by skv-headless** [comment]
As I understood you don't like paging. Try to remove ```pageSize={15}```

**Comment by brookehurford** [comment]
Removing the pageSize={15} from the ListView has no effect on the scrolling issue.

It still only lets me scroll to certain points in the list. If I try to land on parts of the list it pulls me up or down (as I tried to show in the video).

**Comment by skv-headless** [comment]
try https://facebook.github.io/react-native/docs/scrollview.html#pagingenabled
```pagingEnabled={false}``` for ListView.
I can't imagine how ```react-native-scrollable-tab-view``` can influence to ListView.

**Comment by brookehurford** [comment]
Unfortunately that is not working either. Do you have any issues with
smooth scrolling when you put a list view inside the scrollable tab? I am
just wondering if I'm the only one to have this happen, it sounded from
some of the other issues that others may have experienced this as well.

Brooke

On Fri, Jul 22, 2016 at 4:53 AM, Evgeniy Sokovikov <notifications@github.com

**Comment by iit2008047** [comment]
I am facing the same issue. Can any one help  Brooke and me

**Comment by wachauski** [comment]
Hello.  In the Index.js file, line 147, change the line to "pagingEnabled={false}".  Currently, it only has "pagingEnabled".  Cheers!

**Comment by iit2008047** [comment]
but with this change, our tab view paging is disabled.

**Comment by skv-headless** [comment]
I will be able to take a look on weekend. Seems to be a bug in react-native. It would be great if someone can help with it.

**Comment by wachauski** [comment]
I'm using these versions and my tab view paging appears to be okay:
"react": "^15.0.2"
"react-native": "^0.26.0-rc"

**Comment by iit2008047** [comment]
do you have a list view for each tab. check out the video posted by Brooke. we don't want the pagination in listview it should be smooth scroll and each tab should have its listview maintained  (scroll position)

**Comment by skv-headless** [comment]
@brookehurford sorry I can't reproduce that issue on my listview scrolling working well. What seems to be strange for me:
1) ```scrollRenderAheadDistance``` is too small try 200 or even more
2) I don't know what is your ```onScroll``` function. try to remove it
