### ISSUE TITLE
It is not work with react-native-swiper

### ISSUE THREAD

**Issue by layue128** [happypancake/react-native-scrollable-tab-view#361]
If you made a view includes react-native-swiper in scrollable-tab-view, nothing be shown in swiper. iOS is ok, but android is not.

**Comment by shiqian123** [comment]
me too

**Comment by yuanji123** [comment]
me too

**Comment by 471685249** [comment]
me too

**Comment by zhoujl** [comment]
me too

**Comment by 879479119** [comment]
me too

**Comment by skv-headless** [comment]
Have you tried react-native version 31. I saw a commit which might fix it.

**Comment by otoinsa** [comment]
If you set ScrollableTabView prop locket to true, there is no more conflict with touch event;
So I assume this is quite the issue for any content inside ScrollableTabView that has gestures :(

**Comment by gaguirre** [comment]
Any update on this? @otoinsa @skv-headless

**Comment by hectorsc** [comment]
Any solution or update for this problem? :(

**Comment by ljunb** [comment]
It's not work in Android, any solution yet?

**Comment by shiyunsheng** [comment]
I find another issue
Found it :
removing
"justifyContent: 'center',
alignItems: 'center'"

in the style of ScrollableTabView did the trick
