### ISSUE TITLE
is it possible to have a sticky tab on certain position

### ISSUE THREAD

**Issue by bondanherumurti** [happypancake/react-native-scrollable-tab-view#385]
is it possible to have sticky header tab on specific position if i have a very long content?

**Comment by skv-headless** [comment]
I'm not sure what do you mean. Can you make video what effect do you want do achieve. If I understand you correctly that yes but you need to write a custom tab bar.

**Comment by bondanherumurti** [comment]
this is what i meant, i hope it explains, currently i made it using custom component

http://recordit.co/f2zcnELSIK

**Comment by skv-headless** [comment]
Cool 👍 Would you like to share your code?

**Comment by chromonav** [comment]
yes it is possible to do so just embed scrollable tabview inside another


<ScrollableTabView >
                           <View>
                                <ScrollableTabView renderTabBar={() => <FacebookTabBar />} position="bottom"> 
                                 <Text tabLabel="helo1">hell</Text>
<Text tabLabel="helo2">hell</Text>
<Text tabLabel="helo3">hell</Text>
</ScrollableTabView >
                            </View>
                            <Text tabLabel="helo">hell</Text>
</ScrollableTabView>

**Comment by littlesome** [comment]
@skv-headless  Facebook's f8 app iOS version has something like this, (native F8Scrolling and Animated fallback) 

[Native F8Scrolling pin & unpin](https://github.com/fbsamples/f8app/blob/master/ios/F8Scrolling.m)

[ListContainer](https://github.com/fbsamples/f8app/blob/master/js/common/ListContainer.js)

**Comment by tanpuer** [comment]
http://recordit.co/f2zcnELSIK!
it looks cool. Can you share the code?

**Comment by tibbus** [comment]
I will create a PR which will allow this behavior, to add a custom component above the **tabBar** and on scroll to stick the **tabBar** to the top.

**Comment by leoyb** [comment]
@bondanherumurti Can you share your custom component?

**Comment by ivanzhang2** [comment]
> this is what i meant, i hope it explains, currently i made it using custom component
> 
> http://recordit.co/f2zcnELSIK

can you share your custom component?

**Comment by Jeijie** [comment]
Hi, anyone can share a  demo ?

**Comment by 0x01001** [comment]
> this is what i meant, i hope it explains, currently i made it using custom component
> 
> http://recordit.co/f2zcnELSIK

are you alive? pls share your code, thank you ^^
