### ISSUE TITLE
Problem when changing tab after rotating 

### ISSUE THREAD

**Issue by kristinfjola** [happypancake/react-native-scrollable-tab-view#400]
When changing a tab by swiping just after rotating the device, the content jumps back to the previous page while the tab label stays correct. This does not seem to be a problem when pressing a tab label just after rotating, but there is a slight lag instead. 

I managed to eliminate this bug by removing the following lines in index.js in `_handleLayout:`

`
this.requestAnimationFrame(() => {
   this.goToPage(this.state.currentPage);
});`

located here: https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/index.js#L241

I did not make a PR since I wasn't fully sure about the consequences of removing these lines.

**Comment by skv-headless** [comment]
It would be great if you make a video.

**Comment by skv-headless** [comment]
what react-native version do you use? I don't see this problem on example project(v0.28)

**Comment by kristinfjola** [comment]
Using v0.31, sorry for not replying but since I needed to fix this quickly I did it locally.
