### ISSUE TITLE
ViewPagerAndorid RCTEventEmitter.receiveEvent Error bug

### ISSUE THREAD

**Issue by charlesluo2014** [happypancake/react-native-scrollable-tab-view#414]
### Issue Description

Error calling function:ViewPagerAndorid RCTEventEmitter.receiveEvent
### Steps to Reproduce / Code Snippets

```

<View>
<ScrollableTabBar tabStyle={styles.headerTabStyle} style={styles.headerTabbar}  tabBarTextStyle={styles.headerTextStyle} tabBarUnderlineColor="#D12A39" tabBarActiveTextColor="#D12A39">
           <View tabLabel="one" />
           <View tabLabel="two" />
           <View tabLabel="three" />
           <View tabLabel="four" /> 
        </ScrollableTabBar>
</View>
```
# 
### Additional Information
- React Native version: [0.32.0]
- Platform(s) : Android
- Operating System (macOS, Linux, or Windows?):macOS

**Comment by XHTeng** [comment]
I had the same issue !

**Comment by tiaaaa123** [comment]
Same issue.

**Comment by gregorpilz** [comment]
Same issue.

**Comment by shivekkhurana** [comment]
Issue confirmed with react 0.34 as well.

**Comment by skv-headless** [comment]
Please try version from master. There is no ViewPager. I appreciate any feedback.

**Comment by shivekkhurana** [comment]
Hi Evgeniy,

I had to tell you that this library is indeed beautiful 🌼
It saves so much time and gives my products a nice aesthetic sense. Thanks for taking time out to build and open source this.

--

By trying version from master, do you mean :
`npm install git@github.com:skv-headless/react-native-scrollable-tab-view.git` ?

Thanks

**Comment by tonygriv** [comment]
@shivekkhurana, https://github.com/skv-headless/react-native-scrollable-tab-view/tarball/master
