### ISSUE TITLE
Controlled Tabs for both onPress and swipe

### ISSUE THREAD

**Issue by afaayerhan** [happypancake/react-native-scrollable-tab-view#438]
I am trying use Navigator Experimental to control the tabs but i can only control the onPress and can't control when the tab is swiped (ps can only disable change tab on swipe) but can't use navigator experimental to trigger it. maybe it's api should be like TabBarIOS which is very easy to control? or should I just implement mine?

**Comment by skv-headless** [comment]
I'm not sure that I understood you. there is a ```page``` property to control like in ```TabBarIOS```.

**Comment by afaayerhan** [comment]
I used the page before (ps I was doing it wrong) tried it again and it worked. only drawback is not as smoth (fast) as the original. but get's the job done

**Comment by afaayerhan** [comment]
reopening this because it was an inefficient keep both tab change with swipe and press. one API I would suggest is to have callback prop that we can pass down (Maybe should be called onPageWillChange) so that the user can dispatch actions there to change the Navigator states.

**Comment by satya164** [comment]
@afaayerhan You could try https://github.com/react-native-community/react-native-tab-view which let's you own the navigation state.
