### ISSUE TITLE
ScrollableTabBar with react-native-side-menu

### ISSUE THREAD

**Issue by mlostekk** [happypancake/react-native-scrollable-tab-view#439]
I am having some issues together with the side menu from the npm package `react-native-side-menu`

There seems to be some width problems. This leads to a wrong rendering of the tabs.

Anybody got this combination up and running?

**Comment by skv-headless** [comment]
I use it that way.
Can make a screenshot and code snippet?

**Comment by akshaygoyal88** [comment]
I used it together like this
`render() {
    const menu = <Menu navigator={this.props.navigator} isOpen={this.state.isOpen} onItemSelected={this.onMenuItemSelected} />;
    
    return (        
        <SideMenu
            menu={menu}
            isOpen={this.state.isOpen}
            onChange={(isOpen) => this.updateMenuState(isOpen)}
            navigator={this.props.navigator}>
              <ScrollableTabView
                style={{marginTop: 0,backgroundColor:'#B9B7EC' }}
                renderTabBar={() => <DefaultTabBar />}
              >
                <Account navigator={this.props.navigator} tabLabel='Account'></Account>
                <Gallery navigator={this.props.navigator} tabLabel='Gallery'></Gallery>
              </ScrollableTabView>
              
              <Button style={styles.button_menu} onPress={() => this.toggle()}>
                <Image
                  source={require('../Thumbnails/menu.png')} style={{width: 32, height: 32}} />
              </Button>
        </SideMenu>
    );
  }`
