### ISSUE TITLE
App crashes when initial state for tabs is empty

### ISSUE THREAD

**Issue by ChangeSomeCode** [happypancake/react-native-scrollable-tab-view#440]
Android
react-native@0.34.0
react-native-scrollable-tab-view@0.6.0

Hello.

In [DynamicExample](https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/DynamicExample.js#L30), if set empty list to "tabs":

```
getInitialState() {
  return {
    tabs: [],
  };
}
```

and try to change state, app crashes with error:

```
setState(...): Can only update a mounted or mounting component.
```

Thanks!

**Comment by atinder90** [comment]
Faced similar issue, workaround is
`{ tabs.length ? <ScrollableTabView ...> : <ActivityIndicator ...> }`
