### ISSUE TITLE
How to stop propagation on swipe

### ISSUE THREAD

**Issue by jsdario** [happypancake/react-native-scrollable-tab-view#446]
Hi. First: thanks for your library.

Users on my app will trigger actions accidentally while swipping. Is there a way to stop the onPress propagation so while swipping no other press events are triggered inside the view?

Thanks!

**Comment by skv-headless** [comment]
To be sure what do you mean can you please make a video?

**Comment by jsdario** [comment]
Sure, I'll edit this comment ASAP
