### ISSUE TITLE
scrollable tab bar dynamic is failure?

### ISSUE THREAD

**Issue by iamdurui** [happypancake/react-native-scrollable-tab-view#451]
I want to use a scrollable dynamic tabs, but  in your example scrollable tabs failure happened?What is going on?

**Comment by summersky92** [comment]
I think fixed already inside #362, but haven't released yet, can change in the lib file.

**Comment by skv-headless** [comment]
Do you mean that the example project fails?

**Comment by Clcll** [comment]
This way  the tabs stick together, how can we update the view ?

**Comment by iamdurui** [comment]
@skv-headless @summersky92 I want to ask  you why animation is very stumbleuse when I use the scrollTabBar ? How to solve? thanks!

**Comment by Silvercast** [comment]
I have the same problem as @iamdurui . please help
