### ISSUE TITLE
About  ' initialPage' setting ...

### ISSUE THREAD

**Issue by rocwangv** [happypancake/react-native-scrollable-tab-view#458]
Thx for this lib.

![da870920-2cec-4d54-97ba-96eab5da887f](https://cloud.githubusercontent.com/assets/15099302/19349643/aa472b42-9186-11e6-9b24-e74d367f08b5.png)

![57c6632e-23a8-41d2-aab3-3df77c76aeda](https://cloud.githubusercontent.com/assets/15099302/19349653/bad8cd6c-9186-11e6-9b11-6d339886a821.png)

As my images shows , 1st time I search(use the keyboard search button) , the [night] tab has data ,so I want the [night] tab is selected,and everything works well.
The 2nd time I search, the [day] tab has data , so I want the [day] tab is selected ,and the issue like the image 2 : the underline's style works and the word's style not change ..

Any answers are indebted forever !!

**Comment by skv-headless** [comment]
My guess would be that something with keys. Try to remove numbers ```day``` instead of ```day(3)```. If you have time dig in code it would be awesome.

**Comment by AndrewHenderson** [comment]
I'm seeing the same issue on RN v.37, Tabs v0.7.1

**Comment by sksahil030** [comment]
@skv-headless initialPage={this.state.tabNum},when I change this.state.tabNum,page not rendering 

can u please solve help regarding this issue https://github.com/skv-headless/react-native-scrollable-tab-view/issues/547

**Comment by boniattirodrigo** [comment]
Do you have another component changing it?

**Comment by ykl522** [comment]
this.refs.scrollableTabView.goToPage(1);
...
<ScrollableTabView
      ref={'scrollableTabView'}
      ......
>
