### ISSUE TITLE
Nested subset does not display,Help

### ISSUE THREAD

**Issue by durongzhang** [happypancake/react-native-scrollable-tab-view#469]
![image](https://cloud.githubusercontent.com/assets/15725537/20085654/794bb944-a5a5-11e6-8409-3e86ec57fc8a.png)
### Subset of the first tab not show

**Comment by durongzhang** [comment]
Do you have a good solution

**Comment by skv-headless** [comment]
@durongzhang I so sorry for delay. Please try master version it should work

**Comment by linus87** [comment]
I meet the same issue today. You have to click the second tab, then click the first tab, then you can see the first tab's content.
