### ISSUE TITLE
Cannot use CustomTabBar

### ISSUE THREAD

**Issue by rithvikvibhu** [happypancake/react-native-scrollable-tab-view#473]
So i copied the DefaultTabBar.js to app root and renamed it to CustomTabBar.

Tried importing it like
```js
CustomTabBar = require('./CustomTabBar');
```
and changing the import for Button (in CustomTabBar.js):
```js
import Button from 'react-native-scrollable-tab-view';
```
It works (sort of). The tabs don't show text and the border is blue throughout.
I wanted to know why the same piece of code wouldn't work when importing from module and from another file. Any ideas?

**Comment by rithvikvibhu** [comment]
Also, there's a warning:
`Each child in an array or iterator should have a unique "key" prop. Check the render method of 'DefaultTabBar'. See https://fb.me/react-warning-keys for more information`

```
in Button (created by DefaultTabBar)
in DeafultTabBar (created by ScrollableTabView)
in RCTView (created by View)
in ScrollableTabView (created by CustomTabBar)
in RCTView (created by View)
in CustomTabBar (created by ScrollableTabView)
in RCTView (created by View)
in View (created by ScrollableTabView)
in ScrollableTabView (created by *****appnamehere****)
... and stuff
```

**Comment by Nicomalacho** [comment]
Same here, RN 0.37

**Comment by soriac** [comment]
Getting the same warning, RN 0.42

**Comment by skv-headless** [comment]
Please make a repo showing this bug and I will take a look

**Comment by iLeonelPerea** [comment]
Did you fixed it ? i have the same error
