### ISSUE TITLE
Module not found: Error: Cannot resolve module 'react-native'

### ISSUE THREAD

**Issue by Triyugi** [happypancake/react-native-scrollable-tab-view#475]
Hello,

I am using scrollable tabs code from https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/ScrollableTabsExample.js but its giving error;

**Comment by skv-headless** [comment]
What version are installed for ```react-native``` and ```react-native-scrollable-tab-view```?

**Comment by Triyugi** [comment]
@skv-headless Thanks for replying so quick.
React-native version is "version": "0.37.0" and react-native-scrollable-tab-view version is: "version": "0.6.0"

**Comment by Triyugi** [comment]
I was using react-native module globally, when I am using it locally following errors are coming:

`ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'Text' in C:\xampp\htdocs\whenez\
frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 58:22-37

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'TextInput' in C:\xampp\htdocs\wh
enez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 59:27-47

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'ToastAndroid' in C:\xampp\htdocs
\whenez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 60:30-53

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'ToolbarAndroid' in C:\xampp\htdo
cs\whenez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 61:32-57

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'Touchable' in C:\xampp\htdocs\wh
enez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 62:27-47

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'TouchableHighlight' in C:\xampp\
htdocs\whenez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 63:36-65

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'TouchableNativeFeedback' in C:\x
ampp\htdocs\whenez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 64:41-75

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'TouchableOpacity' in C:\xampp\ht
docs\whenez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 65:34-61

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'TouchableWithoutFeedback' in C:\
xampp\htdocs\whenez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 66:42-77

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'View' in C:\xampp\htdocs\whenez\
frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 67:22-37

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'ViewPagerAndroid' in C:\xampp\ht
docs\whenez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 68:34-61

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'WebView' in C:\xampp\htdocs\when
ez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 69:25-43

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'ActionSheetIOS' in C:\xampp\htdo
cs\whenez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 72:32-57

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'AdSupportIOS' in C:\xampp\htdocs
\whenez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 73:30-53

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'Alert' in C:\xampp\htdocs\whenez
\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 74:23-39

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'AlertIOS' in C:\xampp\htdocs\whe
nez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 75:26-45

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'Animated' in C:\xampp\htdocs\whe
nez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 76:26-45

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'AppRegistry' in C:\xampp\htdocs\
whenez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 77:29-51

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'AppState' in C:\xampp\htdocs\whe
nez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 78:26-45

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'AsyncStorage' in C:\xampp\htdocs
\whenez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 79:30-53

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'BackAndroid' in C:\xampp\htdocs\
whenez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 80:29-51

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'CameraRoll' in C:\xampp\htdocs\w
henez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 81:28-49

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'Clipboard' in C:\xampp\htdocs\wh
enez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 82:27-47

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'DatePickerAndroid' in C:\xampp\h
tdocs\whenez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 83:35-63

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'Dimensions' in C:\xampp\htdocs\w
henez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 84:28-49

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'Easing' in C:\xampp\htdocs\whene
z\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 85:24-41

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'I18nManager' in C:\xampp\htdocs\
whenez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 86:29-51

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'ImagePickerIOS' in C:\xampp\htdo
cs\whenez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 87:32-57

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'InteractionManager' in C:\xampp\
htdocs\whenez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 88:36-65

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'Keyboard' in C:\xampp\htdocs\whe
nez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 89:26-45

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'LayoutAnimation' in C:\xampp\htd
ocs\whenez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 90:33-59

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'Linking' in C:\xampp\htdocs\when
ez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 91:25-43

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'NativeEventEmitter' in C:\xampp\
htdocs\whenez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 92:36-65

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'NavigationExperimental' in C:\xa
mpp\htdocs\whenez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 93:40-73

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'NetInfo' in C:\xampp\htdocs\when
ez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 94:25-43

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'PanResponder' in C:\xampp\htdocs
\whenez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 95:30-53

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'PermissionsAndroid' in C:\xampp\
htdocs\whenez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 96:36-65

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'PixelRatio' in C:\xampp\htdocs\w
henez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 97:28-49

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'PushNotificationIOS' in C:\xampp
\htdocs\whenez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 98:37-67

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'Settings' in C:\xampp\htdocs\whe
nez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 99:26-45

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'Share' in C:\xampp\htdocs\whenez
\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 100:23-39

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'StatusBarIOS' in C:\xampp\htdocs
\whenez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 101:30-53

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'StyleSheet' in C:\xampp\htdocs\w
henez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 102:28-49

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'Systrace' in C:\xampp\htdocs\whe
nez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 103:26-45

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'TimePickerAndroid' in C:\xampp\h
tdocs\whenez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 104:35-63

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'UIManager' in C:\xampp\htdocs\wh
enez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 105:27-47

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'Vibration' in C:\xampp\htdocs\wh
enez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 106:27-47

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'VibrationIOS' in C:\xampp\htdocs
\whenez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 107:30-53

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'RCTDeviceEventEmitter' in C:\xam
pp\htdocs\whenez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 110:36-68

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'RCTNativeAppEventEmitter' in C:\
xampp\htdocs\whenez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 111:39-74

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'NativeModules' in C:\xampp\htdoc
s\whenez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 112:31-55 145:13-37

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'Platform' in C:\xampp\htdocs\whe
nez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 113:26-45

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'processColor' in C:\xampp\htdocs
\whenez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 114:30-53

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'requireNativeComponent' in C:\xa
mpp\htdocs\whenez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 115:40-73

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'ColorPropType' in C:\xampp\htdoc
s\whenez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 118:31-55

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'EdgeInsetsPropType' in C:\xampp\
htdocs\whenez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 119:36-65

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'PointPropType' in C:\xampp\htdoc
s\whenez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 120:31-55

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'throwOnWrongReactAPI' in C:\xamp
p\htdocs\whenez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 175:31-62

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'ReactNative' in C:\xampp\htdocs\
whenez\frnt\node_modules\react-native\Libraries\react-native
 @ ./~/react-native/Libraries/react-native/react-native.js 189:28-50`

**Comment by skv-headless** [comment]
@Triyugi did you solve this issue? I've never met something like this, don't even know how to reproduce 😞

**Comment by Triyugi** [comment]
No, I am still facing this issue.

**Comment by zhoujun900113** [comment]
@Triyugi ,did you solve this issue? I met the same issue.

**Comment by Triyugi** [comment]
No, I am still facing this issue.
