### ISSUE TITLE
dynamic create  tabs and then click the item ,the item underLine can‘t show before a second click

### ISSUE THREAD

**Issue by solitaire12** [happypancake/react-native-scrollable-tab-view#476]
code here 
 <ScrollableTabView
                style={{height:50}}
                tabBarUnderlineStyle={{height: 2, backgroundColor: '#d43c33',}}
                tabBarBackgroundColor='#fff'
                tabBarActiveTextColor='#d43c33'
                tabBarInactiveTextColor='#999'
                renderTabBar={() => <ScrollableTabBar  />}
              >
                {this.props.goodsType.map(this._createItem)}

**Comment by skv-headless** [comment]
Could you please make a video? Sorry for delay 😞

**Comment by solitaire12** [comment]
thank you,i have resolved it

**Comment by anbublacky** [comment]
@skv-headless i have this array of data

[
  {
    "id": 1,
    "name": "Indian",
    "avatar_url": "ddddd",
    "menu_items": [
      {
        "id": 7,
        "name": "zzzzz",
        "price_cents": 0,
        "price_currency": "USD",
        "avatar_url": "image.com"
      },
      {
        "id": 4,
        "name": "ccccc",
        "price_cents": 0,
        "price_currency": "USD",
        "avatar_url": "image.com"
      }]

The tab name should be indian and the contents inside will be menu items, i searched about it but nothing helped, and there is no documentation on dynamic data. I believe this is possible, but how can i do it

**Comment by huiming1313** [comment]
@solitaire12 
Would you mind to share how you resolve this issue ?
I'm currently facing the same issue

**Comment by sbodrero** [comment]
@solitaire12 hi, same issue for me. What was your solution please ?
Thanks.

**Comment by sbodrero** [comment]
Got it ! Added tabBarTextStyle={{ color: '#fff' }} to ScrollableTabView params
