### ISSUE TITLE
Rendering scrollableTabView blur TextInput from container

### ISSUE THREAD

**Issue by tiaaaa123** [happypancake/react-native-scrollable-tab-view#477]
Hi! 
I'm making an app and in a `Scene`, I have a container with a `TextInput`. When I focus on the `TextInput`, I change a state which suppose to display a `ScrollableTabView`. However, when the container re-render to add the `ScrollableTabView`, the `TextInput` blur and doing so, the `ScrollableTabView `disapears....

Why does it remove focus on input?

**Comment by skv-headless** [comment]
Could you please make a video? Sorry for delay 😞

**Comment by leechance** [comment]
@skv-headless you are a good gay !!

**Comment by tiaaaa123** [comment]
Any news about a possible fix?

**Comment by skv-headless** [comment]
Do you want to say that if you remove scrollableTabView then TextInput doesn't blur? I don't believe that scrollableTabView is guilty in that.

**Comment by tiaaaa123** [comment]
![with](https://cloud.githubusercontent.com/assets/9055082/21996319/b53579bc-dbf7-11e6-8ec5-ec7dc612077c.gif)
![without](https://cloud.githubusercontent.com/assets/9055082/21996321/b68d8ade-dbf7-11e6-9738-51bf9189d7d9.gif)

Here's the same component but one has the scrollableTabView and the other one hasn't. The logic is the same. The only difference is that when the scrollable is rendered, it blurs the input.
So yes, when i remove the scrollableTabView, then the TextInput doesn't blur

**Comment by IanRamosC** [comment]
I'm facing exactly the same issue (only when there's a `<ScrollableTabView />` ). Any update/solution for it?

**Comment by yogevlahyani** [comment]
Any Solutions ? Happens to me too

**Comment by toinfinityandbeyond** [comment]
+1 any fix?

**Comment by toinfinityandbeyond** [comment]
I just did a workaround, but I'm not sure if it's the best way...
`contentProps={{ keyboardShouldPersistTaps: 'always', keyboardDismissMode: 'none' }}`

**Comment by toinfinityandbeyond** [comment]
Ok, my first attempt did not work as expected because the keyboard was always displayed even when the tab changed.

So I finally did this and now it works perfect :)

```
constructor(props){
    super(props);
    this.state ={
      dismissmode: 'none'
    }
  }
```

```
<ScrollableTabView
            initialPage={0}
            style={{flex:1}}
            contentProps={{ keyboardShouldPersistTaps: 'always', keyboardDismissMode: this.state.dismissmode }}
            onChangeTab={()=>{ this.setState({dismissmode:'on-drag'}) }}
            >
            <TabInfluencers
              tabLabel={language.people}
              people={ this.props.results.people}
              influencers={this.props.influencers}
            />
            <TabCategories
              tabLabel={language.recos}
              recos={ this.props.results.recos}
              categories={this.props.categories}
              getCategory={this.props.getCategory.bind(this)}
              getSubcategory={this.props.getSubcategory.bind(this)}
             />


          </ScrollableTabView>
```


Btw, this only happened to me on Android
