### ISSUE TITLE
Custom TabBar Bugs?

### ISSUE THREAD

**Issue by hetao1024768** [happypancake/react-native-scrollable-tab-view#478]
If I put children(Tabs) which their width wider then the width of the screen on my custom tabBar, they'll shaking

**Comment by skv-headless** [comment]
Could you please make a video? Not sure what do you mean by shaking

**Comment by hetao1024768** [comment]
[bug.mp4.zip](https://github.com/skv-headless/react-native-scrollable-tab-view/files/612767/bug.mp4.zip)

**Comment by skv-headless** [comment]
You can try https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/ScrollableTabBar.js.

**Comment by hetao1024768** [comment]
When I put three tabs, they don't shake. But they'll shake if there's no room for the tabs.

**Comment by hetao1024768** [comment]
<img width="560" alt="2016-11-28 10 40 06" src="https://cloud.githubusercontent.com/assets/9963866/20654753/1b0714fc-b557-11e6-81ce-56e7225fb39f.png">
When I use it directly,it's fine. Instead of Array, it'll shake.(The data of array is dynamic.It can be changed by setting,like check checkbox...in other page of my app)

**Comment by tonylkc** [comment]
I faced this issues too. I tried to work on a dirty hack. 

In ScollableTabBar.js: 

> onTabContainerLayout(e) {
    this._tabContainerMeasurements = e.nativeEvent.layout;
    let width = this._tabContainerMeasurements.width - 1;
    if (width < WINDOW_WIDTH) {
      width = WINDOW_WIDTH;
    }
    this.setState({ _containerWidth: width, });
    this.updateView({value: this.props.scrollValue._value, });
  },

minus the width by 1, then the shaking is gone.

**Comment by hetao1024768** [comment]
@tonylkc 3Q

**Comment by Silvercast** [comment]
I have exactly the same issue. so sad :(

**Comment by imzyf** [comment]
@hetao1024768 first judge tabs count, if count equal 0, don't render ScrollableTabView

eg
```
const content = this.state.tabs.length > 0 ? <ScrollableTabView ...> .. </ScrollableTabView> : <View/>;

return (<View>
    {content}
</View>);
```
