### ISSUE TITLE
Map of Pages between static pages causes the whole navigation shaking and kills the CPU.

### ISSUE THREAD

**Issue by bogomazov** [happypancake/react-native-scrollable-tab-view#481]
How to reproduce:
As a child to ScrollableTabView with ScrollableTabBar pass:
1. static Page.
2. Place map that returns few pages (more then 1)
3. static Page

**Comment by skv-headless** [comment]
Could you make pull request reproducing this bug on example? It would be much easier to fix

**Comment by bogomazov** [comment]
Unfortunately, I cannot reproduce the bug on the example. I believe it happens once tab leaves the boundaries of the width (when `ScrollableTabBar` comes into play) it starts shaking only if childs are generated as a map (not static).

**Comment by hetao1024768** [comment]
The same to me. Shaking @bogomazov [https://github.com/skv-headless/react-native-scrollable-tab-view/issues/478](url)

**Comment by bogomazov** [comment]
The issue arises when child pages are being dynamically populated on the same page.
In my case I used `persist` lib to load initial state.
ScrollableTabView rendered 0 childs and then mapped them respectively.
`onTabContainerLayout` is being updated with an event of width change on IOS infinitely times (width changes between values 350 and 361 (where the first is a screen size and the later is a presumably calculated ScrollableTabBar total width.

Hack around:
Show `ScrollableTabBar` after initial state is loaded (map values are known).
