### ISSUE TITLE
ScrollView stickyHeaderIndices problem

### ISSUE THREAD

**Issue by xclion** [happypancake/react-native-scrollable-tab-view#496]
![image](https://cloud.githubusercontent.com/assets/12453134/21171852/780a39e0-c209-11e6-9d64-e23ebe5b9b51.png)

If a layer of ScrollView is wrapped outside, then the ScrollableTabView child element cannot be rolled.

**Comment by xclion** [comment]
@skv-headless

**Comment by skv-headless** [comment]
What `react-native-scrollable-tab-view` version do you use?

**Comment by xclion** [comment]
"react-native-scrollable-tab-view": "^0.7.0",

**Comment by DavidKongDesheng** [comment]
same issue here~~

**Comment by skv-headless** [comment]
Can you provide example project so I will be able to take a look?

**Comment by ericyang89** [comment]
the same， it do not work when i warpped a View out of it
``` jsx
     // <View>
      <ScrollableTabView
        tabBarPosition="overlayTop"
        style={{ flex: 1 }}
        renderTabBar={() => <DefaultTabBar />}
        onChangeTab={this.onChangeTabHandle}
      >
        {tag.map(item => (
          <ContentList
            key={item.get('id')}
            id={item.get('id')}
            postList={item.get('post')}
            tabLabel={item.get('name')}
            onRefresh={this.onViewRefreshHandle}
            onLoad={this.onViewLoadHandle}
          />
        ))}
      </ScrollableTabView>
      // </View>
```

**Comment by Ekhui** [comment]
@xclion 在吗大兄弟 怎么解决的

**Comment by Ekhui** [comment]
@xclion 在吗大兄弟 怎么解决的 被这个问题困扰一个星期了

**Comment by alexpchin** [comment]
Please can you give information on why this was closed without an answer?

**Comment by ptomasroos** [comment]
Because there is no example repo for me to reproduce

**Comment by alexpchin** [comment]
Roger that. Let me knock one up...

**Comment by alexpchin** [comment]
Here is a repo to demonstrate the problems: https://github.com/alexpchin/react-native-scrollable-tab-view-sticky-header-indicies

**Comment by liu-miao-miao** [comment]
same issue. when ScrollableTabView inside ScrollView. inside ScrollableTabView is a flatlist with dynamic data. so it`s height is dynamic. then i got problem:
    problem 1: when set stickyHeaderIndices, the ScrollableTabView can`t scroll, but it should can;
    problem 2: not set stickyHeaderIndices, it can scroll, but flatList onEndReached auto trigger;
i try a lot, but still can`t fix it. so anyone can fix it?

`<ScrollView
    style={{ flex: 1 }}
    ref={(scrollView) => this.scrollView = scrollView}
    showsVerticalScrollIndicator={false}
    stickyHeaderIndices={[3]}
>
    <View style={{ height: 200 }}><Text>1</Text></View>
    <View style={{ height: 200 }}><Text>2</Text></View>
    <View style={{ height: 200 }}><Text>3</Text></View>
    <View style={{ flex: 1 }}>
        <ScrollableTabView
            initialPage={0}
            renderTabBar={() => <ScrollableTabBar style={{ borderBottomWidth: 0 }} />}
            tabBarInactiveTextColor='#666666'
            tabBarActiveTextColor='#333333'
        >
            <View tabLabel='page1'><FlatList /></View>
            <View tabLabel='page2'><FlatList /></View>
            <View tabLabel='page3'><FlatList /></View>
        </ScrollableTabView>
</ScrollView>`
