### ISSUE TITLE
Problem on Right-To-Left scenes

### ISSUE THREAD

**Issue by Arman92** [happypancake/react-native-scrollable-tab-view#508]
Thanks for the great component, I have issues when I switch to RTL layout,

The swipe gesture is reversed and only the first tab's child content is being rendered.
maybe other tabs get rendered too, but not shown.

I tried some tweaks on index.js but had no luck.

**Comment by skv-headless** [comment]
Can you make screenshot? I don't know actually how RTL should looks like

**Comment by Arman92** [comment]
This is the correct one, all three tabs are shown correctly and swipe gesture is correct.
![ezgif com-d3af416ca2](https://cloud.githubusercontent.com/assets/3900575/21465809/6672df50-c9c7-11e6-9ad9-1ed35510b8c9.gif)




But this one, which has a RTL layout, the swipe gesture is reversed (actually because the UI is flipped horizontally in sake of RTL) and the other two tabs are not shown:
![ezgif com-683327606d](https://cloud.githubusercontent.com/assets/3900575/21465817/832dc9c0-c9c7-11e6-9ce7-0449d9447b58.gif)

**Comment by skv-headless** [comment]
You can try `prerenderingSiblingsNumber={Infinity}`. Please provide code snippet I need to know how do you achieve RTL just `initialPage={2}` or something else.

**Comment by Arman92** [comment]
I tried `prerenderingSiblingsNumber={Infinity}` it didn't work.

RTL is achieved either by setting phone's language to a RTL language such as "Persian" or "Hebrew", OR setting it explicitly via `I18nManager.forceRTL(true);` [refrence](https://facebook.github.io/react-native/blog/2016/08/19/right-to-left-support-for-react-native-apps.html)

I don't think putting my code snippets would be helpful, but in case you needed it:


            <ScrollableTabView tabBarPosition='top' prerenderingSiblingsNumber={Infinity}>

                <NestedScrollView
                    tabLabel={I18n.t("CarDetails.Summary")}
                    tabKey='Summary'
                    style={styles.scroll}>

                    <ListView
                        enableEmptySections={true}
                        style={styles.list}
                        dataSource={this.state.summaryDataSource}
                        renderRow={this._renderRow}
                        renderSeparator={this._renderSeparator}
                    />

                </NestedScrollView>

                <ScrollView style={styles.scroll}
                    tabLabel={I18n.t("CarDetails.Reports")}
                    tabKey='Reports'
                >

                    <View style={{flexDirection: 'column', }}> 
                    <View style={{flexDirection: 'row', alignItems: 'center',
                        justifyContent: 'center'}}>
                        
                        <Text> {I18n.t('CarDetails.Period') + ": "} </Text>

                        <Picker
                            style={styles.picker}
                            mode="dropdown"
                            selectedValue={this.state.minutePickerValue}
                            onValueChange={(itemValue) => this.setState({minutePickerValue: itemValue})}>

                            <Item label={"1 " + I18n.t('CarDetails.Minute')} value="1" />
                            <Item label={"5 " + I18n.t('CarDetails.Minute')} value="5" />
                            <Item label={"10 " + I18n.t('CarDetails.Minute')} value="10" />
                            <Item label={"15 " + I18n.t('CarDetails.Minute')} value="15" />
                            <Item label={"30 " + I18n.t('CarDetails.Minute')} value="30" />
                            <Item label={"45 " + I18n.t('CarDetails.Minute')} value="45" />
                            <Item label={"55 " + I18n.t('CarDetails.Minute')} value="55" />

                        </Picker>

                        <Picker
                            style={styles.picker}
                            mode="dropdown"
                            selectedValue={this.state.hourPickerValue}
                            onValueChange={(itemValue) => this.setState({hourPickerValue: itemValue})}>

                            <Item label={"0 " + I18n.t('CarDetails.Hours')} value="0" />
                            <Item label={"1 " + I18n.t('CarDetails.Hours')} value="1" />
                            <Item label={"2 " + I18n.t('CarDetails.Hours')} value="2" />
                            <Item label={"3 " + I18n.t('CarDetails.Hours')} value="3" />
                            <Item label={"4 " + I18n.t('CarDetails.Hours')} value="4" />
                            <Item label={"5 " + I18n.t('CarDetails.Hours')} value="5" />
                            <Item label={"6 " + I18n.t('CarDetails.Hours')} value="6" />
                            <Item label={"7 " + I18n.t('CarDetails.Hours')} value="7" />
                            <Item label={"8 " + I18n.t('CarDetails.Hours')} value="8" />
                            <Item label={"9 " + I18n.t('CarDetails.Hours')} value="9" />
                            <Item label={"10 " + I18n.t('CarDetails.Hours')} value="10" />
                            <Item label={"12 " + I18n.t('CarDetails.Hours')} value="12" />
                            <Item label={"15 " + I18n.t('CarDetails.Hours')} value="15" />
                            <Item label={"20 " + I18n.t('CarDetails.Hours')} value="20" />
                            <Item label={"24 " + I18n.t('CarDetails.Hours')} value="24" />

                        </Picker>
                    </View>

                    <SubmitButton onPress={this.showPolyLine_statistics.bind(this)} >
                        <Text>{I18n.t('CarDetails.ShowPolyline_Statistics')}</Text>
                    </SubmitButton>

                    <ActivityIndicator
                        size="large"
                        color="#fff600"
                        animating={this.state.polylineLoading}
                    />


                    {
                       this.state.statisticsDataSource.getRowCount() > 0 ? 
                       <Text style={{marginLeft:10}}>{I18n.t('CarDetails.Statistics') + ':'}</Text>
                       : null
                    }


                   <ListView
                       enableEmptySections={true}
                       style={styles.list}
                       dataSource={this.state.statisticsDataSource}
                       renderRow={this._renderRow}
                       renderSeparator={this._renderSeparator}
                   />

                   </View>
               </ScrollView>



           <NestedScrollView 
               style={styles.scroll}
               tabLabel={I18n.t("CarDetails.Charts")}
               tabKey='Charts'
           >

               <View
                style={{flexDirection: 'row', justifyContent: 'center', flex:0.5,}}
               >
                   <IconnedButton 
                       onPress={() => this.chartSettingDlg.openDialog()}
                       style={styles.iconedButton}
                   >
                       <MaterialIcons name="settings" size={18} color="#F4840B" />
                       <Text style={{marginLeft:5}}>{I18n.t('CarDetails.ChartSettings')}</Text>
                   </IconnedButton>

                   <SubmitButton 
                       style={styles.iconedButton}
                       onPress={this.fetchChartData.bind(this)} >
                       <MaterialIcons name="show-chart" size={18} color="#F4840B" />
                       <Text style={{marginLeft:5}}>{I18n.t('CarDetails.ShowChart')}</Text>
                   </SubmitButton>

                </View>

               <ActivityIndicator
                   size="large"
                   color="#fff600"
                   animating={this.state.chartLoading}
               />

               {
                    this.state.chartData.xValues.length > 0 ?
                   <LineChart 
                       style={{flex:1, width: width, height: 300}} 
                       data={this.state.chartData}
                       visibleXRange={[0,30]}
                       maxVisibleValueCount={50} 
                       xAxis={{drawGridLines:false,gridLineWidth:1,position:"BOTTOM"}}
                       yAxisRight={{enable:false}} 
                       yAxis={{startAtZero:false,drawGridLines:true,position:"OUTSIDE_CHART", textColor: "#E94343"}}
                       drawGridBackground={false}
                       backgroundColor={"#FAFAFA"} 
                       description={"Dolphin Apadana FMSx"}
                       legend={{enable:true,position:'ABOVE_CHART_LEFT',direction:"LEFT_TO_RIGHT", legendForm: "CIRCLE"}}
                       pinchZoom={true}
                       dragDecelerationFrictionCoef={0.5}
                       noDataText={"No data available"}
                   />
                   : null
                }

           </NestedScrollView>

           </ScrollableTabView>

**Comment by tje3d** [comment]
Any update on this? you can also forceRTL from Android "Developer Options"

**Comment by rzrobert** [comment]
```
"react": "16.4.1",
 "react-native": "0.55.2",
```
 same problem
