### ISSUE TITLE
Get active tab from ref?

### ISSUE THREAD

**Issue by nickmaxwell10** [happypancake/react-native-scrollable-tab-view#51]
Hey mate, first off, this is a beautiful module, well done!
I have some prev/next buttons that I want to control the active tab.  

I put the following function on the ScrollableTabView
  onChangeTab={(obj) => {this.setState({ day: obj.i })}}
then in my prev button callback, I update the view
  this.refs.dayScroller.goToPage(this.state.day - 1)

This causes the horizontal swipe to be a little laggy.  If I take out the onChangeTab callback, smooth again.

I am using a version of the CustomTabBar from the main example.  Is there some way I can retrieve the activeTab from the dayScroller or tabBar refs?
This way, in my prev button callback, I would be able to update the view with
this.refs.dayScroller.goToPage(this.refs.dayScroller.activeTab - 1)

**Comment by nickmaxwell10** [comment]
Scratch this, I decided to render the buttons in the custom header.  Working great!

**Comment by nickmaxwell10** [comment]
Needed this again, found it via this.refs.dayScroller.state.currentPage

<ScrollableTabView ref="dayScroller">
           ...
</ScrollableTabView>

**Comment by BigPun86** [comment]
@nickmaxwell10 Could you show me how you solved this with a code snippet? I am trying to do the same, because the onChange really slows my Tabs extremely..

**Comment by ahmetacikgoz** [comment]
You can try this: 

`onChangeTab={({ i, ref }) => this.setState({tab : i}) }`

**Comment by ptomasroos** [comment]
Closing as this issue is very old, feel free to open a new issue if its still happening in the latest release
