### ISSUE TITLE
Horizontal ScrollView in Tab's content not work

### ISSUE THREAD

**Issue by tuandt** [happypancake/react-native-scrollable-tab-view#510]
I have a screen with Tabs like https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/FacebookExample.js On one tab, I put a ScrollView with horizontal={true} at the top. A ListView inside that ScrollView. When I have a long list, I can not scroll that list horizontal. It will swipe the tabs instead.

Could you please check that?

**Comment by guo846773272** [comment]
me.too   no problem in iOS.  But android can't

**Comment by skv-headless** [comment]
maybe this is related https://github.com/facebook/react-native/issues/8024. But I personally would not do nested scroll with the same scrolling direction.

**Comment by tuandt** [comment]
Hi, Skv-headless,

It's not the same scrolling direction.
Imagine that in one of tabs, you have a list of people as Horizontal menu at the top and the bottom is list of detail information about that person.

Hope you can check that.

**Comment by ollija** [comment]
Downgrading react-native-scrollable-tab-view to 0.6.0 solved this for me.

**Comment by tuandt** [comment]
Thank you very much ollija!

**Comment by workhardupc** [comment]
@ollija, when i Downgrading react-native-scrollable-tab-view to 0.6.0, the content become blank.

**Comment by workhardupc** [comment]
@tuandt do you solve the problem ?

**Comment by tuandt** [comment]
@workhardupc It worked fine  when I downgrade to 0.6.0 and my RN version was 0.38. After upgrade to 0.42, there was an error then I moved to use https://github.com/react-native-community/react-native-tab-view. It lacks some features but it's working fine with Horizontal ScrollView inside  and in progress to improve.

**Comment by vicvans20** [comment]
The downgrade to 0.6.0 is working for me, currently running RN on version 0.44.0 without problems.

**Comment by chenghaohao** [comment]
so ... the latest version still has the problem。。

**Comment by gurleen-kaur-30** [comment]
downgrading is making the component slow
