### ISSUE TITLE
TextInput with textAlign centered in Android

### ISSUE THREAD

**Issue by otoinsa** [happypancake/react-native-scrollable-tab-view#523]
To replicate:
```
<ScrollableTabView>
	<View style={{flex: 1}} tabLabel='Test'>
		<TextInput style={{textAlign: 'center'}} />
	</View>
</ScrollableTabView>
```

So if I focus that text input and enter a character,
the ScrollableTabView will trigger tab change (what?!).

So how can I use inputs with centered text?
This is a very odd issue, I've seen this happen only in Android.

GIF (sorry for the bad gif quality):
![in](https://cloud.githubusercontent.com/assets/7381482/21805098/0009b5d2-d73b-11e6-97f0-4eed02db42ba.gif)

**Comment by skv-headless** [comment]
Looks really weird. Is it working fine when you set another `textAlign`?

**Comment by ahmetacikgoz** [comment]
+1

**Comment by ahmetacikgoz** [comment]
It's working on version 0.6.0

**Comment by 13160102112** [comment]
I have the similar issue . I do not have textAlign property . However , when the TextInput is on blur ,the same result happened in Android sometimes( not everytime ).

**Comment by ielgnaw** [comment]
I have the same issue too......

**Comment by vinalys** [comment]
Reproduced here as well, could not find a way to fix it yet. However I found this issue even with text alignment not specified in the textinput, but with an intensity decreased... Let's say here is the behavior I noted:
 - aligned center: shift to the far right when focused
 - aligned left: shift slightly to the right
 - align right: goes even further to the right (maybe more than if centered?)

I am wondering if this is something that may be linked to cursor positioning based on length of text also, but this looks really strange and similar to what I can see in the original GIF posted.

I think I can see this issue also on version 0.6.0.
I am on the version 0.41.2 of RN, 15.4.2 of React.
I did not notice this issue previously with the version 0.6.0 used together with RN 0.34.0 and React 15.3.1 (not sure react would have anything to do with this bug but just posting it in case).

**Comment by imbudhiraja** [comment]
Hi  @otoinsa @vinalys please follow this 
https://github.com/gamingexperience/react-native-scrollable-tab-view/blob/93e6b909ac94e76d6883731b988954398cc77293/index.js

**Comment by CrewS** [comment]
I have the similar issue, happend on  Android 4.2.2 or 4.4.4, 
when i  focus on the input ,the tab content will shift to the far right but tab don't change 
i find the "onChangeTab" function don't trigger when this happen

**Comment by MaiYiHang** [comment]
+1

**Comment by luwu1991** [comment]
I have the same issue when textAlign is right.

**Comment by yogevlahyani** [comment]
Hi, @imbudhiraja 
I am using https://github.com/skv-headless/react-native-scrollable-tab-view/pull/608 PR for RTL performence and what you gave here does fix this bug but it turns it back to LTR ..
