### ISSUE TITLE
Add background color on active tab

### ISSUE THREAD

**Issue by radvc** [happypancake/react-native-scrollable-tab-view#536]
Hi just want to ask what is the props for changing style of active tab, i use the 'tabBarActiveStyle' props and set background color but nothing happens.

**Comment by skv-headless** [comment]
It is not that difficult to do. Here https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/DefaultTabBar.js#L20 property `activeTabStyle`.

**Comment by radvc** [comment]
@skv-headless  this is my example code

<ScrollableTabView
  style={{ margin: 20 }}
  scrollWithoutAnimation={true}
  tabBarActiveTextColor={'#00A47D'}
  tabBarUnderlineStyle={{ backgroundColor: '#00A47D'}}
  activeTabStyle={{ backgroundColor: 'red' }}
>
	
   <TabOne tabBarUnderlineStyle={{ borderColor: '#00A47D' }} tabLabel='Tab 1' />
   <TabTwo tabLabel='Tab 2' />

</ScrollableTabView>

**Comment by babelom** [comment]
@radvc 
Hi !
You have to modify the DefaultTabBar component itself

**Comment by lalala345** [comment]
Hi all!
I did try it on latest version. But it not working.

**Comment by babelom** [comment]
I @lalala345 can you show us a piece of your code please ? It will be simplier to see what's wrong.
