### ISSUE TITLE
Tab underline doesn't stick with current tab

### ISSUE THREAD

**Issue by c-h-** [happypancake/react-native-scrollable-tab-view#538]
It's pretty easy to swipe quickly between tabs on Android and get the underline bar (indicating selected tab) to get stuck in the wrong spot - either partially between tabs or on the wrong tab. Any tips on solving this? Is there a way to force the tab underline to reset or refresh?

Thanks!
![screenshot_2017-01-27-14-32-46](https://cloud.githubusercontent.com/assets/5919164/22384759/bcfa6adc-e49d-11e6-8307-6f6f2483e7c2.png)

**Comment by skv-headless** [comment]
You can do like this https://gist.github.com/skv-headless/3a1391d3b52736e7367eb33c3bc1a52b#file-gistfile1-js-L30. 
1) What version `react-native-scrollable-tab-view` do you use?
2) Does it happen in production mode
3) It would be awesome if can you find the problem

**Comment by otoinsa** [comment]
Hi, I get the same issue; no idea where to start though.
I have the 0.7.2 version, latest at this time
Also using react 0.39 version

Yes, it happens regardless of dev/production.
Not sure where to look for the problem, for some reason it does not happen on iOS;
is there something different in Android implementation?

![react-native-scrollable-tab-view-stuck](https://cloud.githubusercontent.com/assets/7381482/22778146/8da12ec6-eebe-11e6-9396-6bfbb1e8c25e.gif)

**Comment by Tarkzeng** [comment]
Does this issue been solved?

**Comment by Pietfro** [comment]
I experience the same issue. It occured after upgrading RN from 0.35 to 0.45.1

**Comment by ssskkk** [comment]
it seems onLayout not called
