### ISSUE TITLE
[Android] ListView onRefresh cancelled by horizontal scroll bug

### ISSUE THREAD

**Issue by Parrryy** [happypancake/react-native-scrollable-tab-view#541]
Pull down to refresh cancels when the slightest horizontal scroll happens, only seen this on android. Horizontal scrolling seems to be disabled when pulling to refresh on iOS. Is there already a solution to this? I have read about the issue but nothing seems to be solved yet.

**Comment by otoinsa** [comment]
I get the same issue when adding RefreshControl on Android, it get's frozen and just stays there...
Only if you are ninja-level skilled, you will be able to actually pull it and achieve a refresh in the scrollview/listview

Here's a screenshot:
![screenshot_20170209-114701](https://cloud.githubusercontent.com/assets/7381482/22777917/97a64330-eebd-11e6-86e4-e81bacd3f8ea.png)

**Comment by danieltr10** [comment]
Same issue as @otoinsa

**Comment by Darkhorse-Fraternity** [comment]
Same issue as @otoinsa

**Comment by jasongrishkoff** [comment]
+1

**Comment by devk1d** [comment]
Same issue @otoinsa

**Comment by feisan** [comment]
Same issue @otoinsa

**Comment by Parrryy** [comment]
@otoinsa That is my exact issue as well.

**Comment by feisan** [comment]
I had to temporarily rollback ScrollableTabView to v0.6.0 now.

**Comment by opaqe** [comment]
I get this behavior with NativeBase, which wraps scrollable-tab-view. Would love a way to lock scrolling if the refreshcontrol is initiated.

**Comment by buptyyf** [comment]
same issue!!!

**Comment by juanmanuelarze** [comment]
same TT

**Comment by jwde** [comment]
Same issue as @opaqe

**Comment by frankyLHJ** [comment]
The same issue, how to do it?

**Comment by krailler** [comment]
Same here...

**Comment by MichelDiz** [comment]
Same here ( "react-native-scrollable-tab-view": "^0.7.2",) 
None Horizontal response
Windows 10 (Android)

**Comment by juanmanuelarze** [comment]
whats happend with this issue?

**Comment by Parrryy** [comment]
Not sure but there is a fix it just hasn't been released.

**Comment by juanmanuelarze** [comment]
thx for the response Parry, oooohh i need it, my client gonna kill me (joke :D)

**Comment by krailler** [comment]
I fix it on PR #554

**Comment by juanmanuelarze** [comment]
thx @krailler, how can i update the package? i make npm install but nothing

**Comment by skv-headless** [comment]
Temporary solution downgrade to "react-native-scrollable-tab-view": "^0.6.0"

**Comment by tanpuer** [comment]
i downgrade to 0.60, but the same problem occurs.

**Comment by cloudZQY** [comment]
@tanpuer 
I downgrade to 0.6.0 and resolve it.
"react-native": "^0.42.0"
"react-native-scrollable-tab-view": "^0.6.0"
you can try it again.

**Comment by skv-headless** [comment]
I've published 0.6.3 with some fixes. Will be supporting it. Maybe version version 0.8 will be based on it.

**Comment by martinarroyo** [comment]
@skv-headless What would be the differences from this new version compared to 0.7.0? Are there some release notes that I can have a look at? I am worried about my setup having problems when downgrading.

**Comment by itaibs** [comment]
I'm using this package via the "native-base" package and downgrading is somewhere between a mess and impossible :/. Also when I tried it didn't work :(

Any news on when a fix is going to be out there or any kind of other workaround idea?

Thanks!

**Comment by RUIFERNANDE5** [comment]
Well, I'm tried to downgrade to 0.6 and the horizontal actually worked, but I could not swipe / navigate to other tabs on Android..

**Comment by Er-Xiao** [comment]
locked (Bool) - disables horizontal dragging to scroll between tabs, default is false.
chenge locked={true}  
defaults locked={false}

**Comment by RUIFERNANDE5** [comment]
I'm pretty sure if people didn't want the swipe functionality they would just build a component themselves to change views

**Comment by mehdijjz** [comment]
I'm having the same issue

**Comment by phumaster** [comment]
same issue :(

**Comment by jasongrishkoff** [comment]
I was using this library when the errors were showing up -- https://github.com/archriss/react-native-snap-carousel

They rolled out an update to try fix it, and indeed, haven't seen the error appear for a while now.

**Comment by marlti7** [comment]
+1

**Comment by marlti7** [comment]
you can fixed it in parent component add prop refreshControl and delete child component prop refreshControl

**Comment by phumaster** [comment]
@marlti7  you can give me more information? Or code? Please.

**Comment by inoutw** [comment]
I encounter the same issue while using ScrollView for both ios and android, Now I changed it to ViewPagerAndroid for Android, the issue was gone.
