### ISSUE TITLE
undefined is not an object (evaluating 'validAttributes[key]')

### ISSUE THREAD

**Issue by BigPun86** [happypancake/react-native-scrollable-tab-view#55]
Hey there, i am trying to use the basic implementations in my Android App, but i am keep getting these errors...

![screen shot 2015-10-20 at 11 17 09](https://cloud.githubusercontent.com/assets/7880624/10603006/229e6096-771c-11e5-9022-f5c08c0018f5.png)

![screen shot 2015-10-20 at 11 12 09](https://cloud.githubusercontent.com/assets/7880624/10602952/bf9ce062-771b-11e5-91c9-e7190224a3c5.png)

npm manager:

```
Unable to resolve module precomputeStyle from ProjectPath.../node_modules/react-native-scrollable-tab-view/index.js
Unable to resolve module precomputeStyle from ProjectPath.../node_modules/react-native-scrollable-tab-view/DefaultTabBar.js
```

**Comment by BigPun86** [comment]
Solved it by cloning the project into my node_module instead of installing it with npm

**Comment by daemonchen** [comment]
@BigPun86 which project did you clone? the react-native or react-native-scrollable-tab-view?

**Comment by ownzandy** [comment]
It works when you clone https://github.com/brentvatne/react-native-scrollable-tab-view/ into your project's node_module folder

**Comment by BigPun86** [comment]
Yes exactly! I cloned the project which @ownzandy has mentioned, sorry for late reply...

**Comment by sanyuelanv** [comment]
oh ! i see it in my project~can you tell me how to kill it~~

**Comment by JonathanWi** [comment]
Also having this issue, and updating or cloning the project doesn't solve it (currently using 0.3.4). Any idea @brentvatne ?
<img width="426" alt="capture d ecran 2016-01-22 a 12 52 10" src="https://cloud.githubusercontent.com/assets/1074479/12510025/185e796a-c107-11e5-90d7-7a0d5dff320f.png">

**Comment by leoabacade** [comment]
reporting the same issue here

**Comment by ericraio** [comment]
same issue here

**Comment by skv-headless** [comment]
Sorry for ignoring this issue. Could you give me code snippet to reproduce this issue?

**Comment by nicreichert** [comment]
I've been facing this issue, now. Did anyone find a solution for this?

**Comment by ptomasroos** [comment]
Closing as this issue is very old, feel free to open a new issue if its still happening in the latest release
