### ISSUE TITLE
[IOS] Swiping between tabs is not working on RTL devices

### ISSUE THREAD

**Issue by efratyo** [happypancake/react-native-scrollable-tab-view#553]
In RTL devices, switching between tabs is only available on tab tap. 
Swiping between tabs is not working and the current tab stays active.

RN- 0.40.0
RNSTV- 0.6.0

**Comment by skv-headless** [comment]
https://github.com/skv-headless/react-native-scrollable-tab-view/pull/559 is it working for you?

**Comment by zumaawad** [comment]
I will solve this issue soon

**Comment by efratyo** [comment]
Actually I solved this issue but I did it by mistake on v0.6.0, where it works well.
On v0.7.0+ it's not working.
If it worth something I can PR it.

**Comment by zumaawad** [comment]
yes please PR ;)

**Comment by efratyo** [comment]
I created a PR, then it got conflicted with the last version so I closed it.
You can use my forked branch for v.0.6.0- https://github.com/efratyo/react-native-scrollable-tab-view.git.

**Comment by zumaawad** [comment]
can u tell me what u changed ?

**Comment by efratyo** [comment]
Of course, take a look on this PR to see the changes- https://github.com/skv-headless/react-native-scrollable-tab-view/pull/560
