### ISSUE TITLE
goToPage instantly goes back to initial page if called too fast after the scene rendered

### ISSUE THREAD

**Issue by IgorVanian** [happypancake/react-native-scrollable-tab-view#558]
Tested only on Android.

If I call goToPage(nextPage) really fast after the scene with ScrollableTabView renders, the next page comes up as wanted but instantly goes back to the first page.

It doesn't happen if I wait >1 seconds before calling goToPage.
It also doesn't happen after it happened the first time (and after re-renders).
Only happens on the first scene render.

**Comment by skv-headless** [comment]
Why do you need to call `goToPage` right after rendering? Please describe why you cant use `initialPage`

**Comment by IgorVanian** [comment]
I have a "next" button that calls goToPage(currentPage+1) when tapped. The issue happens when I tap it right after render.

**Comment by windhost** [comment]
I got the same problem

**Comment by windhost** [comment]
[](https://github.com/facebook/react-native/issues/11693)

**Comment by windhost** [comment]
https://github.com/facebook/react-native/issues/11693

**Comment by windhost** [comment]
https://github.com/facebook/react-native/issues/6849
