### ISSUE TITLE
Performance issue on RN v.0.42

### ISSUE THREAD

**Issue by tuandt** [happypancake/react-native-scrollable-tab-view#561]
Hi,

I just upgraded to RN v.0.42. Swipe tabs is very slow and this issue happens on latest version: https://github.com/skv-headless/react-native-scrollable-tab-view/issues/510

Could some one please help?

**Comment by KaniRobinson** [comment]
Make sure you have turned off Slow animations in the IOS emulator.

**Comment by tuandt** [comment]
Hi KaniRobinson,

It's also slow on my phone too. Not just on emulator.

**Comment by skv-headless** [comment]
https://github.com/facebook/react-native/issues/11809 maybe it is a problem
