### ISSUE TITLE
is it possible to add scaling style on active tab?(question)

### ISSUE THREAD

**Issue by jasan-s** [happypancake/react-native-scrollable-tab-view#565]

**Comment by skv-headless** [comment]
Do you mean transform scale? Yeah why not?

**Comment by jasan-s** [comment]
@skv-headless yes transform scale. I am just clear where to add styling for the activetab

**Comment by skv-headless** [comment]
It depends on what do you want to scale.

**Comment by jasan-s** [comment]
Using icons for tabs. want to scale the ison when active
