### ISSUE TITLE
Page2 delay showing when doing background work in Page1 

### ISSUE THREAD

**Issue by zhuyifan2013** [happypancake/react-native-scrollable-tab-view#572]
I have two pages 1 and 2.
Page 1 will do some IO works with Promise, Page 2 just has general component.
My problem is when I launch My app and then immediately swipe to Page2 , it will delay show content until my IO work done.
Is it a bug of your library?

**Comment by MrLyfing** [comment]
Not sure but I think you should use `prerenderingSiblingsNumber={Infinity}` in props in order to initially render all tabs.
