### ISSUE TITLE
[Android] Bug on TabBar animation 

### ISSUE THREAD

**Issue by rigobcastro** [happypancake/react-native-scrollable-tab-view#574]
![Image](https://thumbs.gfycat.com/GroundedCaringEidolonhelvum-size_restricted.gif)

Hello everyone!

When I press any tab the animation appears to be returned incorrectly. It is something inexplicable, so I place the screen capture for understand better my error.

Thanks for your support.

**Versions & info:** 

Platform: Android 6
OS: MacOS Sierra
RN: 0.42.0
RN Scrollable Tab View: 0.7.3

**Render code**

Nothing special:

```javascript
<ScrollableTabView
        renderTabBar={() => <ScrollableTabBar />}
        tabBarBackgroundColor="#341497"
        tabBarActiveTextColor="white"
        tabBarInactiveTextColor="white"
        tabBarTextStyle={Styles.text}
        tabBarUnderlineStyle={Styles.underline}
      >
        <Text tabLabel="FIRST TAB">TAB 1</Text>
        <Text tabLabel="SECOND TAB">TAB 2</Text>
        <Text tabLabel="THIRD TAB">TAB 3</Text>
        <Text tabLabel="ANOTHER TAB">TAB 4</Text>
        <Text tabLabel="LAST TAB">TAB 5</Text>
 </ScrollableTabView>
```

**Comment by ggepenyan** [comment]
Why there is no reply

**Comment by ggepenyan** [comment]
it is actually a **bug** that needs to be fixed ((
