### ISSUE TITLE
callback on touch start?

### ISSUE THREAD

**Issue by L-Jovi** [happypancake/react-native-scrollable-tab-view#578]
hi, thanks for your smart project,

I want to do some actions when I touch tabView, I mean __touch start__ and __touch end__, and I try existed callback `onScroll` and `onChangeTab`, they cannot fire when I touch or release the child component.

would you mind set `touchStart` and `touchEnd` action or how should I implement it?

thanks for your time.

**Comment by goleador0322** [comment]
same here +1  <img src="http://cultofthepartyparrot.com/parrots/thumbsupparrot.gif" />
