### ISSUE TITLE
Is it possible for the tabs to scroll together ?

### ISSUE THREAD

**Issue by Kris4an7** [happypancake/react-native-scrollable-tab-view#579]
Hello, Is it possible for the tabs to scroll together.
For example if I have Tab1 and Tab2 and I scroll to the middle of Tab1 and I swipe to Tab2, I want Tab2 to be also in the middle. Assume Tab1 and 2 have the same length of the ScrollView.

Thank you !

**Comment by skv-headless** [comment]
Not sure that understood you. Can you make a small video on this effect?

**Comment by Kris4an7** [comment]
Here is a professional illustration  from paint in 1 minute. I hope it can clear it up. And thanks !
![untitled](https://cloud.githubusercontent.com/assets/25613799/24220917/781114a0-0f4c-11e7-9b3a-98c63e96d15a.png)

**Comment by Kris4an7** [comment]
Anyone ?
