### ISSUE TITLE
Cannot get the navigator  in the tab item

### ISSUE THREAD

**Issue by combing520** [happypancake/react-native-scrollable-tab-view#583]
Hi , I just want to kown ,how can I  get  the navigator in the tab item , 
i exec this code , but I  get  the result   true;
componentDidMount(){
      Alert.alert('navigator == null ? '+(this.props.navigator == null ));
  }

Thanks

**Comment by juanmanuelarze** [comment]
<Tab navigator={this.props.navigator}/>

**Comment by skv-headless** [comment]
https://github.com/skv-headless/react-native-scrollable-tab-view#changing-between-tabs?
or are you looking for something different?
