### ISSUE TITLE
iPad mini 2 crashes when orientation changes

### ISSUE THREAD

**Issue by evanidul** [happypancake/react-native-scrollable-tab-view#585]
Hey guys,

Great component.  Works great for me in most cases, however, I run into this odd case only on the iPad mini 2 where the app just crashes after I change orientation back and forth a few times, tabbing between various webviews.  I've tested on iPhone 6, 7, iPod Touch, various Android devices, and all of those are fine.  It's just this one iPad mini 2 where I see this issue (very consistently, crashes every time I flip orientation back and forth).

I've installed Fabric/Beta/Crashlytics to try to gain further insight, however, they report no crash.

I think it's this component because I swapped it out for TabBarIOS.  A build using TabBarIOS pointing to the exact same webviews works fine.  The reason I am using this component is for Android support and because I haven't figured out how to programmatically change tabs in TabBarIOS.  Otherwise I might just use TabBarIOS for the iPad Mini 2.  Also, just wondering if anyone else is experiencing this odd behavior on the iPad Mini 2.

thanks!

daniel

**Comment by skv-headless** [comment]
Can you attach error, stacktrace?

**Comment by evanidul** [comment]
[ipadcrashscrubbed.txt](https://github.com/skv-headless/react-native-scrollable-tab-view/files/867165/ipadcrashscrubbed.txt)

**Comment by evanidul** [comment]
Search for com.mycompany.myapp.  I don't get a react native red screen or anything.  The app just exits.  When I plug my iPad into xCode, this is what I see after the crash.  Let me know if you want more logs/data, and thank you for looking into this.

**Comment by evanidul** [comment]
For some reason, now I see:

Message from debugger: Terminated due to memory issue  (only for Ipad Mini)

Did a little experiment.  My app basically has 5 tabs with 5 WebViews.  If I point every WebView to https://www.google.com, then it stops crashing.  If I point only 2 to google, the app works for awhile before crashing.

Anyway, still odd that this works fine on iPhone and all the Android devices I tested on.  Also seems to work fine on IPad mini if I use TabBarIOS.
