### ISSUE TITLE
请问ScrollableTabView动态加title 怎么获取tabLabel相应点击事件 

### ISSUE THREAD

**Issue by zhengxuanyi** [happypancake/react-native-scrollable-tab-view#589]
render() {
        var itemViews = [];
        for (var i = 0; i < this.state.classList.length; i++) {

            var itemView=(

                  <Text tabLabel={this.state.classList[i].acName} >

                  </Text>
              
                );
            itemViews.push(itemView);
        }

        return (
            <View style={styles.container}>
                <ScrollableTabView
                    style={{marginTop: 20,height:45 }}
                    renderTabBar={() => <ScrollableTabBar />}

                >
                    {itemViews}
                </ScrollableTabView>

                <ListView
                    style={{backgroundColor:'white'}}
                    dataSource={this.state.dataSource} //数据源
                    renderRow={this.renderRow.bind(this)}
                />

            </View>
        );
    }

**Comment by skv-headless** [comment]
Please translate to english.

**Comment by zhengxuanyi** [comment]
I would like to ask how to get a dynamic title plus tabLabel ScrollableTabView corresponding click event




------------------ 原始邮件 ------------------
发件人: "Eugene Sokovikov";<notifications@github.com>;
发送时间: 2017年3月31日(星期五) 下午4:09
收件人: "skv-headless/react-native-scrollable-tab-view"<react-native-scrollable-tab-view@noreply.github.com>; 
抄送: "俄╮冷血不需要理由"<978357074@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [skv-headless/react-native-scrollable-tab-view] 请问ScrollableTabView动态加title 怎么获取tabLabel相应点击事件 (#589)




Please translate to english.

**Comment by FlyingMonkeyKing** [comment]
@zhengxuanyi 点击事件看看源码写的挺清晰的，看看gotoPage。至于后者，你要动态给谁加title就用组件传值呗
