### ISSUE TITLE
[Android] The tab page is blank when resetTo the root component.

### ISSUE THREAD

**Issue by ljunb** [happypancake/react-native-scrollable-tab-view#595]
Hello, I get a issue when resetTo the root component base on react-native-scrollable-tab-view.
There are some basic codes of `AMTabBarView.js` as the follows:
```
<AMSideMenu
    ref={sideMenu => this.sideMenu = sideMenu}
    ...
>
    <ScrollableTabView
        ...
        initialPage={this.props.initialPage || 0}
    >
        <Home tabLabel="Home"/>
        <Information tabLabel="Information" />
        <Shop tabLabel="Shop" />
    </ScrollableTabView>
</AMSideMenu>
```
This `ScrollableTabView` is wrapped in my custom component `AMSideMenu`, and when I resetTo the `AMTabBarView` with navigator on some pages:
```
this.props.navigator.resetTo({
    component: AMTabBarView,
    params:{initialPage : 2}
})
```
and then, the `Shop` page is blank, althrough I can alert something on the `Shop` render method at the same time. I need to click the tab to show up `Shop` page content. This issue is only appear in Android, iOS goes well everytime!
I'm looking forward for your response!

**Comment by skv-headless** [comment]
Could you please reproduce it on separate project or make pull request to examples?

**Comment by ljunb** [comment]
In the new test, I'm confused that the issue doesn't appear any more :(
I will continue to follow up on this issue as soon as I make progress.

**Comment by yunlongz** [comment]
i have the some problem with u  but I don't work it out··

**Comment by kormang** [comment]
I have the same problem too.
