### ISSUE TITLE
I  can not update tabbarunderlineheight?

### ISSUE THREAD

**Issue by iamlion** [happypancake/react-native-scrollable-tab-view#601]
I  can not update tabbarunderlineheight?
I want to update this underlineStyle , but i can not do it?
How can i do?

**Comment by skv-headless** [comment]
What exactly are you doing and what are you trying to update?

**Comment by iamlion** [comment]
Sorry, I am a Chinese, English aquatic product is not good, I should use translation software.
This component is perfect, but I want to modify his underline style, I look at the source code, only to find his background color can be modified, but I found the height, width can not be modified.

```


render() {
    const containerWidth = this.props.containerWidth;
    const numberOfTabs = this.props.tabs.length;
    const tabUnderlineStyle = {
      position: 'absolute',
      width: containerWidth / numberOfTabs,
      height: this.props.underlineHeight,
      backgroundColor: this.props.underlineColor,
      bottom: 0,
    };

    const left = this.props.scrollValue.interpolate({
      inputRange: [0, 1, ], outputRange: [0,  containerWidth / numberOfTabs, ],
    });

    return (
      <View style={[styles.tabs, {backgroundColor: this.props.backgroundColor, }, this.props.style, ]}>
        {this.props.tabs.map((tab, i) => this.renderTabOption(tab, i))}
        <Animated.View style={[tabUnderlineStyle, { left, }, ]} />
      </View>
    );
  },
});
```

This is part of the DefaultTabBar source code, I found that the height and width are calculated, can not define their own.

**Comment by Tgoing** [comment]
直接这样就可以把：tabBarUnderlineStyle={{backgroundColor: '#3e9ce9', height: 2}}
