### ISSUE TITLE
Control alignment of tabs based on tab header text

### ISSUE THREAD

**Issue by jsartisan** [happypancake/react-native-scrollable-tab-view#602]
![screen shot 2017-04-09 at 1 51 41 pm](https://cloud.githubusercontent.com/assets/6636360/24835901/b3db3992-1d2b-11e7-8788-72333799b799.png)
Is possible to achieve something like this

**Comment by jsartisan** [comment]
@skv-headless i want to achieve tab styling like this. Is this possible with your package ?

**Comment by linigithub** [comment]
Yes possible.
