### ISSUE TITLE
Blank page and setState to unmount component warnings

### ISSUE THREAD

**Issue by ihor** [happypancake/react-native-scrollable-tab-view#605]
Hey guys,

In our app we have a screen which has several navigation options. Each navigates to a different ScrollableTabView page. 

The problem appears when we try to go back and forward to the screen with ScrollableTabView component. Sometimes it produces a blank ScrollableTabView page. 

I did some debugging and found that somehow it tries to render the wrong page, not the one specified in the initialPage prop. I tried to catch that in componentDidMount and navigate to the correct page, but this method was not called by React.

Another thing which I see sometimes is "Can only update a mounted or mounting component.". I don't know if it is related. But I suspect that it might.

<img width="1437" alt="screen shot 2017-04-14 at 00 34 50" src="https://cloud.githubusercontent.com/assets/490943/25027605/3c0e75ba-20ae-11e7-9983-a4bf90795e74.png">

Is there anything we can do to avoid this issue? Let me know if you need more information.

**Comment by skv-headless** [comment]
Thanks for bug report. Could you please reproduce this bug on example? Or provide demo project?

**Comment by ihor** [comment]
Hey,

We switched to ```ScrollView``` with ```pagingEnabled```. I can't promise I'll find time to prepare an example. It were two screens:
- one with ```ScrollableTabView```
- and another one with a list of all individual pages in the ```ScrollableTabView``` clicking on which took you to the selected page

The problem appeared when we were switching quickly (but slow enough to repro this in a real app usage) between these two screens.
