### ISSUE TITLE
How to hidden the Tabbar when push a new page by using navigator?

### ISSUE THREAD

**Issue by TinchyChing** [happypancake/react-native-scrollable-tab-view#607]
I used navigator to make navigation, when i try to push a new scene, Tabbar is over the component. How can I fix it? Do I need to change the child component?

**Comment by skv-headless** [comment]
Please make a video or gif and provide code snippet. It would be much easier for me to help.

**Comment by yukailis** [comment]
传参 <NotStart tabLabel='未开始' navigator={this.props.navigator}/>

**Comment by yukailis** [comment]
<NotStart tabLabel='未开始' navigator={this.props.navigator}/>

**Comment by yukailis** [comment]
￼
￼

**Comment by yukailis** [comment]
navigator={this.props.navigator}

**Comment by barron9** [comment]
how to pass this props under tabs? this.props.navigation returns null
