### ISSUE TITLE
blank page at startup

### ISSUE THREAD

**Issue by cbjs** [happypancake/react-native-scrollable-tab-view#612]
react-native: 0.42
react-native-scrollable-tab-view: 0.6.3 (0.7.x, RefreshControl is not working on android)
os: android

need to click or swipe to other tab, then content show up.

![b](https://cloud.githubusercontent.com/assets/1215843/25110285/62ee5dac-2415-11e7-8539-05da8f6b02d6.gif)

**Comment by skv-headless** [comment]
Thanks for bug report. I can't reproduce. Could you please reproduce this bug on example? Or provide demo project.

**Comment by Jacse** [comment]
This happens for me when i update the `page`-prop. I have to swipe before I see anything rendered.

**Comment by ZHT131** [comment]
我现在启动应用无法加载tab内容页，只有当打开新页面后才可以显示出来

**Comment by yunlongz** [comment]
只是在Android上面会这样吧？

**Comment by cbjs** [comment]
seems like a bug of ViewPagerAndroid, I fix this by set a key for it. 
see pull request: https://github.com/skv-headless/react-native-scrollable-tab-view/pull/632

**Comment by yunlongz** [comment]
@cbjs 实在0.6.6版本基础上修改的吗？

**Comment by cbjs** [comment]
@yunlongz 0.7.4

**Comment by perfecten** [comment]
I have the same issue.
but the android is OK, iOS is NG.
