### ISSUE TITLE
when i use tab-view in the tab-view some bugs happen

### ISSUE THREAD

**Issue by zsj6102** [happypancake/react-native-scrollable-tab-view#619]
import ScrollableTabView, { DefaultTabBar, } from 'react-native-scrollable-tab-view';
export default class Demo extends Component
{
  render()
  {
    return (
      <ScrollableTabView
        renderTabBar={() => <DefaultTabBar />}
        ref={(tabView) => { this.tabView = tabView; } }

        tabBarUnderlineStyle={{
          position: 'absolute',
          width: 80,
          height: 4,
          backgroundColor: '#abde77',
          bottom: 0,
        }}

        tabBarBackgroundColor='#FFFFFF'
        tabBarActiveTextColor='#abde77'
        tabBarInactiveTextColor='#585858'
        textStyle={{ fontSize: 16 }}
        >
        <PageTwo tabLabel="旅行圈" />
        <PageOne tabLabel="聊天2121" />
        <Text tabLabel="旅行1">My</Text>
        <Text tabLabel="旅行圈1">My</Text>

      </ScrollableTabView>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
class PageOne extends React.Component
{
  // 构造

  render()
  {

    return (
      <ScrollableTabView
        renderTabBar={() => <DefaultTabBar />}
        ref={(tabView) => { this.tabView = tabView; } }

        tabBarUnderlineStyle={{
          position: 'absolute',
          width: 80,
          height: 4,
          backgroundColor: '#abde77',
          bottom: 0,
        }}
        initialPage={0}
        tabBarBackgroundColor='#FFFFFF'
        tabBarActiveTextColor='#abde77'
        tabBarInactiveTextColor='#585858'
        textStyle={{ fontSize: 16 }}
        >
        <Text tabLabel="旅行1">My</Text>
        <Text tabLabel="旅行圈1">My</Text>
        <Text tabLabel="聊天1">favorite</Text>
        <Text tabLabel="聊天222">favorite</Text>
      </ScrollableTabView>
    )
  }
}
class PageTwo extends React.Component
{
  // 构造

  render()
  {

    return (
      <ScrollableTabView
        renderTabBar={() => <DefaultTabBar />}
        ref={(tabView) => { this.tabView = tabView; } }

        tabBarUnderlineStyle={{
          position: 'absolute',
          width: 80,
          height: 4,
          backgroundColor: '#abde77',
          bottom: 0,
        }}
        tabBarBackgroundColor='#FFFFFF'
        tabBarActiveTextColor='#abde77'
        tabBarInactiveTextColor='#585858'
        textStyle={{ fontSize: 16 }}
        >
        <Text tabLabel="旅行2">My</Text>
        <Text tabLabel="旅行圈2">My</Text>
        <Text tabLabel="聊天2">favorite</Text>
        <Text tabLabel="聊天12">favorite</Text>
      </ScrollableTabView>
    )
  }
}
AppRegistry.registerComponent('Demo', () => Demo);

**Comment by zsj6102** [comment]
https://github.com/zsj6102/WisdomHall/blob/master/app/src/main/res/2.gif

**Comment by zsj6102** [comment]
https://github.com/zsj6102/WisdomHall/blob/master/app/src/main/res/2.gif

**Comment by zsj6102** [comment]
[https://github.com/zsj6102/WisdomHall/blob/master/app/src/main/res/2.gif](url)

**Comment by yunlongz** [comment]
what bugs？

**Comment by zsj6102** [comment]
@yunlongz when i submit the gif something went worng but you can  view    https://github.com/zsj6102/WisdomHall/blob/master/app/src/main/res/2.gif
to see the bug

**Comment by xufang215** [comment]
遇到同样的问题，最外层默认那一栏 内容不显示
