### ISSUE TITLE
Collapsible Toolbar with TabBar

### ISSUE THREAD

**Issue by ashrithks** [happypancake/react-native-scrollable-tab-view#638]
Hi All,

Tried to achieve collapsing toolbar with tabbar,

 -- ![Valid XHTML](https://camo.githubusercontent.com/97497a24719b85f5d618cba66ac4d23ccfdd7023/687474703a2f2f692e696d6775722e636f6d2f615069333243712e676966)

referring to --  https://medium.com/appandflow/react-native-scrollview-animated-header-10a18cb9469e

But no luck!!!
![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/19853363/26247388/49bb73c4-3cbb-11e7-8560-de277e711796.gif)

**Comment by skv-headless** [comment]
Do you mean it is slow? I think it is common pattern. Would you like to share your work?

**Comment by ashrithks** [comment]
sure

**Comment by tibbus** [comment]
I had the same issue, in the end I forked this repo and did the changes that fit my specs. I might publish it to npm if there's an interest for it.

**Comment by ashrithks** [comment]
@tibbus  can you share the npm link??

**Comment by skv-headless** [comment]
@tibbus I would love to add this as a custom tab bar into this repository.

**Comment by carobeta** [comment]
@tibbus can you share your fork? Thanks!

**Comment by binchik** [comment]
Here is what I did:
https://github.com/binchik/react-native-scrollable-tab-view/commit/524c041d0e111adaa474d4d1415a6d3cc441f432

Then you can just wrap your tab bar inside Animated.View and animate translateY based on scroll value.

**Comment by tibbus** [comment]
Here is the code and PR : https://github.com/skv-headless/react-native-scrollable-tab-view/pull/667

**Comment by ashrithks** [comment]
@tibbus  thank you so much,
@skv-headless  please merge the above PR .
