### ISSUE TITLE
How to disable animation of children but remain transition of underline

### ISSUE THREAD

**Issue by gameboyVito** [happypancake/react-native-scrollable-tab-view#639]
Dear all, I would like to know how to disable the sliding animation of all children components when switching among different tabs, but remaining the animation of underline. 

I have read the doc and using the `scrollWithoutAnimation ` and `locked` to disable the sliding effect, but it also disables the sliding animation of underline. I want to keep the `animation of underline` and disable the `horizontal dragging`, can anyone show me how to make a customize the default `ScrollableTabBar`?

**Comment by skv-headless** [comment]
scrollWithoutAnimation={false}
