### ISSUE TITLE
[IOS] when setting initialPage  = {this.initialPage}, have to set scrollWithoutAnimation ={true}

### ISSUE THREAD

**Issue by perfecten** [happypancake/react-native-scrollable-tab-view#646]
IOS: when setting initialPage  = {this.initialPage}, have to set scrollWithoutAnimation ={true},
otherwise the change of tabs is strange(scrollWithoutAnimation ={false}),
When I set scrollWithoutAnimation ={true},All is well.

PS: this.initialPage is setted in componentWillMount. 
My app will save the seleted tabPage for the next opening.

but Android is OK.

**Comment by skv-headless** [comment]
What do you mean strange? Could you please make a video?

**Comment by garando** [comment]
I've got exactly the same problem, here's the video of this strange behavior 
![ios bug mov](https://user-images.githubusercontent.com/7852028/28270319-bdffd77c-6b0d-11e7-8ecc-24f53bea4a6e.gif)
