### ISSUE TITLE
Animation stops working after pushing a new screen

### ISSUE THREAD

**Issue by elios264** [happypancake/react-native-scrollable-tab-view#647]
I'm using[ react-native-navigation](https://github.com/wix/react-native-navigation) to push a new screen but this seems to break the component.

![animation broken](https://cloud.githubusercontent.com/assets/15863852/26561045/c2f3ff6e-4480-11e7-8268-02f4344cbf33.gif)

**Comment by skv-headless** [comment]
Do you have any error or warning? Can you reproduce this bug on example project? I have no idea what is the problem so far 😞

**Comment by Himz20** [comment]
I am facing the same issue. It stops working.

**Comment by skv-headless** [comment]
Can you provide example project?

**Comment by jonanderdev** [comment]
I am facing the same issue. Any news on this?

**Comment by Himz20** [comment]
You can use Modal instead of push screen. It works with Modal :D

**Comment by sheshavpd** [comment]
Facing same issue. Any solution found?

**Comment by hzyIO** [comment]
@jonanderdev @Himz20 @sheshavpd  I had the same issue it has been fixed in the 0.7.4 ( at least for me) version which is only a tag and not on the npm version, which is 0.6.7. You have to include the tag in your package.json.

**Comment by mehdijjz** [comment]
I'm facing the same issue

**Comment by rodolfobarretoweb** [comment]
Move to 0.7.4 version, works !

**Comment by yechunxi** [comment]
I'm facing the same issue  ,the version 0.8.0

**Comment by git-Asir** [comment]
I'm facing the same issue in the version 0.8.0; the react-native version: ^0.50.3;i make it on the modal
