### ISSUE TITLE
TouchableOpacity fire when scrolling

### ISSUE THREAD

**Issue by AsafBrieferyDev** [happypancake/react-native-scrollable-tab-view#648]
I have a problem that when I drag the screen using touch over a TouchableOpacity - the onPress fires. 
To bypass that, I've added a "touch-lock"  that was called when scroll began (Iock) and scroll ended(unlock).
To do that I've added 2 new properties - onScrollBegin and onScrollEnd (creating 2 functions that check callbacks and call _onMomentumScrollBeginAndEnd),
I've changed:
```    
      onMomentumScrollBegin={this._onMomentumScrollBeginAndEnd}
      onMomentumScrollEnd={this._onMomentumScrollBeginAndEnd}
```
To:
```    
      onMomentumScrollBegin={this._onMomentumScrollBegin}
      onMomentumScrollEnd={this._onMomentumScrollEnd}
```
And added:
```
_onMomentumScrollBegin(e) {
    if (!!this.props.onScrollBegin) {
      this.props.onScrollBegin();
    }
    this._onMomentumScrollBeginAndEnd(e);
  },

  _onMomentumScrollEnd(e) {
    if (!!this.props.onScrollEnd) {
      this.props.onScrollEnd();
    }
    this._onMomentumScrollBeginAndEnd(e);
  },
```
Do you want me to create PR and add it?

**Comment by skv-headless** [comment]
@AsafBrieferyDev could please make a video of this bug? I understand better when I see. Thanks.

**Comment by vishaldhanotiya** [comment]
I have face same issue. 
Resolved this by import `TouchableOpacity` from `react-native-gesture-handler` instead of `react-native.`

Replace this

`import {TouchableOpacity } from 'react-native'`

From this

`import {TouchableOpacity } from 'react-native-gesture-handler'`

**Comment by islandryu** [comment]
This issue is probably caused by React-Native's ScrollView.
https://github.com/facebook/react-native/issues/27355
