### ISSUE TITLE
React.Children.only expected to receive a single React element child,

### ISSUE THREAD

**Issue by songxiaoliang** [happypancake/react-native-scrollable-tab-view#649]
Android simulator Samsung s6 5.1 running on the project abnormal: React.Children.only expected to receive a single React element child, I am positioned to Button.android.js TouchNativeFeedback. How to solve it?

**Comment by skv-headless** [comment]
I'm not 100% sure what are you doing but this error means that instead of group elements you should pass only one so you can just wrap your elements into the `View`

**Comment by songxiaoliang** [comment]
I am glad to receive your e-mail, I will be your source TouchableNativeFeedBack control to TouchableOpacity after the error will not occur, do not know why. Looking forward to your reply

**Comment by Andrfas** [comment]
I'm not using `react-native-scrollable-tab-view`, but faced the same problem. Looks like it is RN issue
