### ISSUE TITLE
RTL Issue

### ISSUE THREAD

**Issue by yogevlahyani** [happypancake/react-native-scrollable-tab-view#653]
Hi, My device is RTL and so is my application (FORCE RTL) But that tabs did work good with the fixed made **when it wasn't rtl forced** and not after I forced RTL - I swipe to the left but the tabs show it goes right although I swipe to the left and the screen goes right like it should be. just the tabs goes opposite.

**Comment by mehdijjz** [comment]
I have the same problem

**Comment by yogevlahyani** [comment]
Any solutions ?

**Comment by jkuwait** [comment]
+1

**Comment by Shabnam-Veranloo** [comment]
@yogevlahyani i have same prolem...
do you find any solution???

**Comment by MohamedHedar** [comment]
+1

**Comment by michelmouallem** [comment]
Go to node_modules/react-native-scrollable-tab-view and open ScrollableTabBar.js
steps:
- On line 2 replace :
     const { ViewPropTypes} = ReactNative = require('react-native');
      **to :** 
     const { ViewPropTypes,I18nManager} = ReactNative = require('react-native');
- on line 162 replace : 
     const dynamicTabUnderline = {
      left: this.state._leftTabUnderline,
      width: this.state._widthTabUnderline,
    };
   **TO :** 
    const key = I18nManager.isRTL ? 'right' : 'left';
    const dynamicTabUnderline = {
    [`${key}`]: this.state._leftTabUnderline,
    width: this.state._widthTabUnderline
    }

- Finaly on your terminal : **yarn add react-native-invertible-scroll-view**
then import **InvertibleScrollView from 'react-native-invertible-scroll-view';** to your JS file (ScrollableTabBar.js) 
Finaly replace on line 179  <ScrollView 
TO <InvertibleScrollView inverted={I18nManager.isRTL ?true :false}


Happy coding

**Comment by saurabh874** [comment]
@michelmouallem this is not working do you have any alternative solution for same?
