### ISSUE TITLE
width of tab change when get from server, render slow, tap sometime not working

### ISSUE THREAD

**Issue by yaraht17** [happypancake/react-native-scrollable-tab-view#654]
I have some issues: 
1. I get catalog from server and add to tab, when init width = screen width, but when get success from server, the amount text length of catalog more than screen width( i using scrolltabbar), tab is "jumping around". I solution: tabsContainerStyle={{ width: this.state.catalogs.length * 150 }} />}
2. In a tab, i get a list of product and when i change tab, everything is slowly, delay, performance not good, and some time click a tab content not change, and click again or again more it can change
How to fix it or improve performance

**Comment by yaraht17** [comment]
everyone can help me!

**Comment by RohitRajpal** [comment]
I am also facing the same issue.View not render properly **on clicking tab bars**,some times loads too slow, sometimes underline don't appear.
On swipe it works fine.
