### ISSUE TITLE
i use flatList on iphone simulator ，firstpage notshow

### ISSUE THREAD

**Issue by banli17** [happypancake/react-native-scrollable-tab-view#655]
1、i use flatList on iphone simulator ，firstpage notshow，but i scroll little to bottom or up, its show。 on android is ok。and other pages is ok。only firstpage。

2、because my menu has many, some times  i enter  the text is overlay,and some times is ok。i think this is bug ?

```
<ScrollableTabView
	initialPage={0}
	tabBarBackgroundColor='#fff'
	tabBarUnderlineStyle={{backgroundColor: DEFAULT_COLOR, height: 2}}
	tabBarActiveTextColor={DEFAULT_COLOR}
	renderTabBar={() => <ScrollableTabBar />}
>
	{
		lists.map((item, i)=> {
			return (
				<FlatList
					contentContainerStyle={{flex: 1}}
					key={i}
					tabLabel={item.title}
					data={lists}
					keyExtractor={({item, id})=>id}
					renderItem={this._renderItem.bind(this)}
				/>
			)
		})
	}
</ScrollableTabView>
```

because my menu has many, some times  i enter  the text is overlay。

**Comment by emsihyo** [comment]
I have too. InitialPage is not effect.No more than the FlatList. Index of the default page is 2.

**Comment by LFDCC** [comment]
Same issue.

**Comment by karimkhamwani** [comment]
+1
