### ISSUE TITLE
Install removes all packages in the current project

### ISSUE THREAD

**Issue by chrisciszak** [happypancake/react-native-scrollable-tab-view#658]
How is this even possible?

When I try to add this plugin with "npm install react-native-scrollable-tab-view --save" it literally removes all packages from my project. I have tested it with a fresh react-native project.

What's wrong? Any way to install it manually?
![screen shot 2017-06-06 at 23 47 46](https://user-images.githubusercontent.com/11364221/26855395-93b1dbd4-4b12-11e7-80ea-300f4c81c658.png)

**Comment by zhoumeitong** [comment]
use ' $ yarn add react-native-scrollable-tab-view ' to install
