### ISSUE TITLE
changing data source in dynamic tab list view

### ISSUE THREAD

**Issue by huiming1313** [happypancake/react-native-scrollable-tab-view#660]
In my application, the tab is render dynamically as well as its content.
Below are my implementation.
```
let topicListViews = this.state.topicList.map(
          (topic, i) => (
              <NewsListScene
                  tabLabel={this.state.topicList[i].name}
                  key={[i]}
                  types={[]}
                  topic={this.state.topicList[i].code}
                  country={this.state.selectedCountry}
                  navigation={this.props.navigation}
                  isReloadPage={this.state.isReloadPage} />
          )
        )
```

I will pass the props to this NewsListScene and inside it will have it own datasource and calling the api based on the given props.

and in my render method i have this, which give me dynamic tab and it dynamic content. As below

```
<ScrollableTabView
          style={styles.container}
          tabBarBackgroundColor='white'
          tabBarActiveTextColor='#FE566D'
          tabBarInactiveTextColor='#555555'
          tabBarTextStyle={styles.tabBarText}
          tabBarUnderlineStyle={styles.tabBarUnderline}
          renderTabBar={() => <ScrollableTabBar />}
      >
        { topicListViews }
      </ScrollableTabView>
```

In this page i will have a action menu, which allow user to choose different country. By the time user choose the country, it will have to refresh all of the tab content and calling the api in NewsListScene. Below is the sample screen
![untitled](https://user-images.githubusercontent.com/15344977/26893846-34cbe9b0-4bef-11e7-8330-266f6b93f2c9.png)

How can i change the tab content when user select different country ? the constructor in NewsListScene will not be trigger again as the tab content is already rendered.

And am i implement it in a proper way ?

**Comment by MrLaibin** [comment]
why close issue?

**Comment by agrawalsurabhi89** [comment]
same issue how did you resolve it @huiming1313
