### ISSUE TITLE
onChangeTab keep firing when I change rotation

### ISSUE THREAD

**Issue by kenvandemar** [happypancake/react-native-scrollable-tab-view#662]
Up to now, my everything work well excepting the bug:
- When I rotate the screen on tablet, onChangeTab function automatically run which cause unnecessary rendering of component. How to prevent that?
I am using react-native-orientation to check rotation on tablet.

**Comment by kenvandemar** [comment]
I fixed this by preventing function inside onChangeTab run each time the screen rotates. But this is temporarily solution, onChangeTab still run when screen is rotated. Hope better solution.

**Comment by skv-headless** [comment]
I can try `PureComponent` to prevent second rendering
