### ISSUE TITLE
 Run on Android platform is not good, who can help me

### ISSUE THREAD

**Issue by helloconch** [happypancake/react-native-scrollable-tab-view#663]
I am sorry, my English is not good.
when I  use  'react-native-scrollable-tab-view' run on IOS platform is good.
but on Android platform is not good, i don't know. why?
please see the zip files.
The Top Component  use 'react-native-scrollable-tab-view'
The Bottom Component use React Navigation (TabNavigator+StackNavigator)

I find ,when only use 'react-native-scrollable-tab-view' ,run on Android platform is  good.

but 'react-native-scrollable-tab-view' +'TabNavigator'  is not good.

Thanks.

[device-2017-06-11-144734.mp4.zip](https://github.com/skv-headless/react-native-scrollable-tab-view/files/1066266/device-2017-06-11-144734.mp4.zip)

**Comment by kenvandemar** [comment]
Could you upload your repo here?

**Comment by helloconch** [comment]
@kenvandemar 
The Bottom Component is  TabNavigator
`const BottomNavigator=TabNavigator({
  news:{screen:newsTabView},
  joke:{screen:joke},
  more:{screen:more}
}.......`

The Top Componnet is 'react-native-scrollable-tab-view'

`
export default class NewsTabView extends Component{
    static navigationOptions=({ navigation, screenProps })=>({
    tabBarLabel: '新闻',
    title:'掌上新闻',
    tabBarIcon: ({ tintColor }) => (
      <Image
        source={require('../../imgs/news_icon.png')}
        style={[styles.icon, {tintColor: tintColor}]}
      />
    ),
  });
  
  render(){
    return (
     <ScrollableTabView 
        renderTabBar={()=><ScrollableTabView.ScrollableTabBar/>}
        onChangeTab={(obj) => {
          console.log('index:' + obj.i);
        }
       }
        tabBarPosition='top'
        tabBarActiveTextColor={tabBarActiveColor}
        tabBarInactiveTextColor={tabBarInActiveColor}
        tabBarBackgroundColor={tabBarBackgroundColor}
        tabBarUnderlineStyle={{backgroundColor: tabBarUnderlineColor}}
        scrollWithoutAnimation={false}
        locked={false}
        style={{backgroundColor:tabBarBackgroundColor}}
        tabBarTextStyle={{fontSize: tabBarTextSize}}>
        <Newslist tabLabel="头条" id='toutiao' navigation={this.props.navigation}/>
        .................
`

thanks.

**Comment by kenvandemar** [comment]
as I see the mp4 video in your zip file, the scrollable tab on the top animates quite slow. Right?
Like you, we also use  react-native-scrollable-tab-view and react-navigation.  But I recommend you seperate your top Component, avoid to put 'navigationOptions'  and <ScrollableTabView /> in one file.
Moreover, I'm not sure 'renderTabBar={()=><ScrollableTabView.ScrollableTabBar/>}' is good way to make ScrollableTabBar, we often just use' renderTabBar={() => <ScrollableTabBar />}'.
Try to organize your structure as clear as possible. It is more important if you apply Redux to your project.

**Comment by fatsoon** [comment]
@helloconch 你可以试试在`TabNavigatorConfig`里设置`animationEnabled`为`false`

**Comment by helloconch** [comment]
@fatsoon 这个一直设置的 animationEnabled:false

**Comment by helloconch** [comment]
@kenvandemar  
hello , nice to know you.

https://github.com/helloconch/RNScrollTest

run ios is good, but run android ...

please take a look.

thanks.

**Comment by 393197906** [comment]
@helloconch  你好，我也遇到了同样的问题，混合使用无法正常滑动，后来我发现在问题页面添加一个input然后获取焦点后页面变的正常，不知道是什么原因。我用的是0.6.6,怀疑问题出在viewpager

**Comment by helloconch** [comment]
@393197906 能否贴下input处的代码片段，以及package,json配置看看...这个问题困扰有段时间，都准备用原生写android了....

**Comment by 393197906** [comment]
我之前升级过一次0.7.4版本，滑动正常，但是又会出现滑动触发太灵敏的问题，看了下源码0.7以后的版本是用scrollview实现的，效果并不理想。  因为我的页面需要带一个搜索input框，无意间发现获取焦点后能解决这个问题，只能暂时先用着。下面是片段代码
`<IndexHeader nav={this.props.navigation} focus={true}></IndexHeader>
                <ScrollableTabView
                    renderTabBar={() => <ScrollableTabBar />}
                    tabBarUnderlineStyle={{backgroundColor: color.main1, height: 2}}
                    tabBarActiveTextColor={color.main1}
                    tabBarInactiveTextColor={color.font1}
                    style={{backgroundColor: color.main2}}
                    contentProps={{keyboardShouldPersistTaps: 'always', keyboardDismissMode: 'none'}}
                >`

**Comment by WinterSunshine** [comment]
@helloconch  我也是遇见这个问题，放到TabNavigator里的页面，reload之后就不显示，放到其他二级页面就好着，请问你解决了吗？

**Comment by helloconch** [comment]
@393197906 好的 ，多谢

**Comment by helloconch** [comment]
@WinterSunshine 可以参考楼上朋友，给的提示，升级"react-native-scrollable-tab-view": "^0.7.4",

我运行个Demo在android设备上，可以正常切换不同顶部Tab

**Comment by ycpaladin** [comment]
我也遇到这个问题了，相同的代码在iOS下是正常的，但是在android中就不正常，困扰了我好久. 现在升级到0.7.4在android下就OK了。感谢！

**Comment by coolguy001tv** [comment]
`npm i react-native-scrollable-tab-view@0.7.4 ` did solve it.  It's so weird that in [npmjs.com - react-native-scrollable-tab-view](https://www.npmjs.com/package/react-native-scrollable-tab-view) , it shows me 0.6.7 is the latest.
`npm i react-native-scrollable-tab-view@0.7.4 ` 能够解决问题。 不过奇怪的是， [npmjs.com - react-native-scrollable-tab-view](https://www.npmjs.com/package/react-native-scrollable-tab-view)里边显示的是0.6.7是最新版本。

**Comment by chexuwu** [comment]
I fixed this bug. in componentDidMount join 
this.timer = setTimeout(()=> {
            this.setState({
                delayShowScrollTableView: true
            });
        }, 500);

**Comment by kaiyuanlee** [comment]
@chexuwu che GOOD!
