### ISSUE TITLE
Style property 'left' is not supported by native animated module

### ISSUE THREAD

**Issue by pvinis** [happypancake/react-native-scrollable-tab-view#669]
I dont understand whats happening with the versions on npm, master and in the tags, but i had 0.6.6, working, then i updated to 0.6.7, and now i get the above message. its complaining about the 'left' style on the underline view.
Any ideas?

**Comment by pvinis** [comment]
ok i did yarn install with both versions, diffed the folder, and found out the difference.

the `left` on the default tab bar changed to `transformX`

**Comment by p0d3r** [comment]
bump +1

**Comment by p0d3r** [comment]
Possible fix:

Go to render method of DefaultTabView, and find `const left` then update:

```
const left = {
      transform: [
        {
          translateX: this.props.scrollValue.interpolate({
            inputRange: [0, 1,], 
            outputRange: [0, containerWidth / numberOfTabs,],
          })
        }
      ]
    }
```

then

`<Animated.View style={[tabUnderlineStyle, left, this.props.underlineStyle,]} />`

**Comment by pvinis** [comment]
yep. that's what I did. still they versioning should be fixed, so that the default tab bar on github reflects that change.

**Comment by Obooman** [comment]
@p0d3r I crash into this problem too,but I don't understand what you are pointing out,I can't find any file named `DefaultTabView` or find any code you list.

`react-native-scrollable-tab-view@^0.6.7`

**Comment by Obooman** [comment]
Oh It's [here](https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/DefaultTabBar.js#L68-L79)

**Comment by chiefninew** [comment]
we tried downgrading to 0.6.6 and it works..

**Comment by jose920405** [comment]
In my case, it was because I was applying an interpolate on a touchable. It seems only valid for `View, Text, Image`

**Comment by MattFoley** [comment]
For those still experiencing this issue, it's probably because you're passing in your own component for "renderTabBar", and making the same "left" mistake in there.

**Comment by danieelvaraujo** [comment]
> 
> 
> Possible fix:
> 
> Go to render method of DefaultTabView, and find `const left` then update:
> 
> ```
> const left = {
>       transform: [
>         {
>           translateX: this.props.scrollValue.interpolate({
>             inputRange: [0, 1,], 
>             outputRange: [0, containerWidth / numberOfTabs,],
>           })
>         }
>       ]
>     }
> ```
> 
> then
> 
> `<Animated.View style={[tabUnderlineStyle, left, this.props.underlineStyle,]} />`

Thanks a lot.
