### ISSUE TITLE
Horizontal Scrollview is scrolling to end when textAlign is right in TextInput on Android

### ISSUE THREAD

**Issue by ahmetacikgoz** [happypancake/react-native-scrollable-tab-view#670]
This problem has appeared after version **0.7.x**
I guess it is related with ScrollView, because component was using ViewPager before 0.7.x

It is working correctly when textAlign is left in TextInput

**Example**:

![new_gif](https://user-images.githubusercontent.com/8920411/27284412-4d757592-5501-11e7-9e08-eac386240fd1.gif)

**Comment by jpapillon** [comment]
Same thing happens to me, too.

**Comment by yogevlahyani** [comment]
Same thing happens to me either

**Comment by ahmetacikgoz** [comment]
Additionally,
When there is a long text in textInput and focused it, tab is swiping as much as text lenght by itself.

**Comment by feluxz** [comment]
I have the same problem with a normal scrollview. Does anyone know how to fix this?
