### ISSUE TITLE
when i use it in tabNavigator on android , it transit slow

### ISSUE THREAD

**Issue by cielu** [happypancake/react-native-scrollable-tab-view#679]
两个问题，一个是关于在安卓平台下的tabnavigator中使用它的时候会很卡

as the title show , I got this problem , anyone have solution ?

另一个是，我想实现在顶部滚动的tab后面再加一个  Icon ，但是好像都固定了。。。

anthor one is , I want to add an Icon at the end of tab , 

such as : tab1,tab2,tab3,tab4 Icon 

![image](https://user-images.githubusercontent.com/13715811/27583379-bdc2e116-5b66-11e7-94a6-6c2e404d3dba.png)

**Comment by cielu** [comment]
react-navigation 1.0.0-beta.11

**Comment by cielu** [comment]
I solve  the problem @0.7.4 version，but got  a new problem ,  can't use ScrollView horizontal  in android

**Comment by adnbsr** [comment]
ScrollView will be deprecated soon use `FlatList` instead.

**Comment by cielu** [comment]
@adnbsr thank you . do you have any other contact way ,  how about make a friends .

**Comment by cielu** [comment]
@adnbsr  I thought that is a big problem , when I use scrollable-tab-view@0.6.7 in android .It transit slowly at the fist time  if I render the ScrollableTabBar . but after focus a inputView , the app works well .  
react-navigation@0.11
react-native-scrollable-tab-view@0.6.7

**Comment by boplennon** [comment]
Same problem here. I downgrade react-navigation to beta 9 and it worked fine. But then later, i upgrade react-native to 0.46 then it becomes slow again. Tab doesn't switched when i touch tab bar, and when i swipe it become slow and cant transition to new tab completely but stuck at the middle.

**Comment by yohanceli** [comment]
在安卓`tabNavigator`中使用他卡的问题,我将版本号改为`react-native-scrollable-tab-view@0.7.4`解决了

**Comment by cielu** [comment]
@yohanceli 你这样虽然解决了卡顿问题，但是还有scrollview的手势冲突问题出现，除非你不用scrollview在 tab view里面

**Comment by Taffyw** [comment]
@cielu 升级了确实出现这个bug  请问解决了吗 6.7版本scrolltab滑动失效  7.4横向滚动跟竖向滚动冲突
