### ISSUE TITLE
Keyboard push tab bar problem

### ISSUE THREAD

**Issue by niros001** [happypancake/react-native-scrollable-tab-view#683]
Hi, i used tabs at bottom position. In ios every thing good but in android when i open the keyboard the tab bar go up with the keyboard... 
how can i solve that behavior and make the tab bar stay on bottom?

**Comment by vasyas** [comment]
@niros001 have you been able to solve the issue? I have the same problem.

**Comment by SteveChina** [comment]
> @niros001 have you been able to solve the issue? I have the same problem.

have you solved the issue? I have the same problem.

**Comment by SteveChina** [comment]
> @niros001 have you been able to solve the issue? I have the same problem.

have you solved the issue? I have the same problem.
