### ISSUE TITLE
Extreme lags in transactions iOS and Android

### ISSUE THREAD

**Issue by ozsirma** [happypancake/react-native-scrollable-tab-view#693]
![iphone-se](https://user-images.githubusercontent.com/17460410/28119423-7f07c5dc-671d-11e7-98d0-9c2a7ab30c29.gif) ![iphone-7](https://user-images.githubusercontent.com/17460410/28119427-84270c44-671d-11e7-9d28-ae0f6d8f00d8.gif)

I have a problem. This code is running correctly in SE but scrollable tab has lag in other simulators. Why? This is interesting event.

react-native: 0.44.2
react-native-scrollable-tab-view: 0.7.4

**Comment by alxvallejo** [comment]
Did you check if you have Debug > Slow Animations on?

**Comment by chexuwu** [comment]
you can try in componentDidMount join
this.timer = setTimeout(()=> {
this.setState({
delayShowScrollTableView: true
});
}, 500);
`render(){
return(<View>
        { this.state.delayShowScrollTableView ?
<ScrollableTabView
                            onChangeTab={()=>this.onChangeTab()}
                            keyboardDismissMode="on-drag"
                            keyboardShouldPersistTaps={false}
                            renderTabBar={() => <DefaultTabBar/>}
                        >
{...this.props}
</ScrollableTabView>
:
<View style={{flex:1,justifyContent:'center',alignItems:'center'}} >
                            <ActivityIndicator
                                animating={true}
                                color='#ccc'
                            />
                        </View>
}
</View>)}`
