### ISSUE TITLE
ListView does not get rendered in a Scrollable Tab

### ISSUE THREAD

**Issue by sl-rnSPDVS** [happypancake/react-native-scrollable-tab-view#695]
ListView component is not getting rendered when added as part of ScrollableTabView. My Code is :

<ScrollableTabView
        initialPage={0}
        renderTabBar={() => <ScrollableTabBar />}
      >

        <View tabLabel='Tab # 2'>
              <ListView
                style={{flex : 1}} dataSource={this.state.dataSource}
                renderRow={(data) =>
                  <Text>{data.name}</Text>}
              />
        </View>

  < / ScrollableTabView>

The tab "Tab # 2" gets rendered empty.
If i have the same ListView code without ScrollableTabView the data gets rendered.

**Comment by Maydar** [comment]
Have the same issue with FlatList =(

**Comment by Amurmurmur** [comment]
Try to pass `removeClippedSubviews={false}` to your FlatList/SectionList as a prop.

**Comment by Maydar** [comment]
@Amurmurmur it does not take any effect =(

**Comment by emsihyo** [comment]
I have too.

**Comment by Amurmurmur** [comment]
What if you do the following:

```
import {Dimensions} from 'react-native'
var {height, width} = Dimensions.get('window');
  <View style={{flex: 1, width, height }} tabLabel='Tab # 2'>
          <ListView
            style={{flex : 1}} dataSource={this.state.dataSource}
            renderRow={(data) =>
              <Text>{data.name}</Text>}
          />
    </View>
```

Would that work? Last time I've used this package it was fine for me, however I would also suggest to check [react-native-tab-view](https://github.com/react-native-community/react-native-tab-view) it is the core of the TabView of the react-navigation package.
