### ISSUE TITLE
Empty (blank) tab view - changing initialPage during parent rerendering causes empty screen on iOS

### ISSUE THREAD

**Issue by Coobers** [happypancake/react-native-scrollable-tab-view#707]
It's caused by componentWillReceiveProps in index.js is not handling change of initialPage.

In order to make tab works, entire code from getDefaultProps must be running if initialPage prop value changes.

**Comment by josecarr1979** [comment]
Same problem.

**Comment by atitpatel** [comment]
I too am facing similar issue
