### ISSUE TITLE
react-native-scrollable-tab-view and react-navigation

### ISSUE THREAD

**Issue by uimom** [happypancake/react-native-scrollable-tab-view#709]
react-native-scrollable-tab-view and react-navigation at the same time use
Home page react-native-scrollable-tab-view can not slide!!!
![1](https://user-images.githubusercontent.com/28993716/28856144-ddfe5afe-7773-11e7-9896-cb6c859825da.gif)

Other page side no problem?
![2](https://user-images.githubusercontent.com/28993716/28856167-f3c348f4-7773-11e7-8269-bbead9e7ba37.gif)

Is this what is the reason?

**Comment by chexuwu** [comment]
+1

**Comment by chexuwu** [comment]
use react-native-scrollable-tab-view@0.5.3 have  the problem，use @0.7.4 is ok,but react-native-scrollable-tab-view and listView at the same time use,ListView's refreshControl can't use

**Comment by onemonster** [comment]
Same problem...

**Comment by chexuwu** [comment]
react-native-scrollable-tab-view @0.5.3 and react-navigation in IOS is no problem, but in Android my HomePage can't show. Then I joined <TextInput autoFocus={true}/> in my HomePage is OK.But the keyboard will flash.

**Comment by chexuwu** [comment]
react-native-scrollable-tab-view @0.5.3 and react-navigation in IOS is no problem, but in Android my HomePage can't show. Then I joined  `<TextInput autoFocus={true}/>`   this code  in my HomePage is OK.But the keyboard will flash. @uimom @onemonster if fixed please tell me,thanks

**Comment by NidhoggC** [comment]
same problem,And it will be fixed when i trigger hot reloading on device

**Comment by chexuwu** [comment]
I fixed this bug. in componentDidMount join 
this.timer = setTimeout(()=> {
            this.setState({
                delayShowScrollTableView: true
            });
        }, 500);

**Comment by p0d3r** [comment]
try https://www.npmjs.com/package/react-native-scrollable-tab-view-master

**Comment by RyanWan** [comment]
+1

**Comment by tianweicc** [comment]
一样

**Comment by tianweicc** [comment]
No effect after adding

**Comment by tianweicc** [comment]
@chexuwu   No effect after adding

**Comment by chexuwu** [comment]
@tianweicc 你的版本是多少的？代码方便贴下？或加我Q，429162739

**Comment by maxim-c** [comment]
seems broken AndroidViewPager in react-native...

**Comment by blueviewcc** [comment]
@tianweicc 请问楼主解决了吗

**Comment by zhangjun920912** [comment]
delay load render scrollable-tab-view can resolve this question,you can set state,when open this page ,show an activityIndicator,after 500ms,change state,then render scrollable-tab-view,this is an temporary method,maybe ,wo can wait plaugs refresh

eg:if(this.state.delayShowScrollableTabView)
            {
                return(
                    <View style={{flex:1,backgroundColor:'#fff'}}>
                        <View style={{marginTop:screenHeight*0.4+99,alignSelf:'center',flexDirection:'row'}}>
                            <ActivityIndicator size={'small'}/>
                            <Text style={newsListStyle.newsFootText}>Loading...</Text>
                        </View>
                    </View>
                );
            }else{
                return (
                    <View style={[newsNavRow.viewBackGround]}>
                        <TouchableOpacity activeOpacity={0.95} style={newsNavRow.searchWrapper} onPress={()=> {this.props.navigation.navigate("NewsSearch_V2",{searchContent:"News"})}}>
                            <View style={{backgroundColor:'#204B7D',flex:1,alignItems:'center',justifyContent:'center',height:Platform.OS=="ios"?44:55,width:44}}>
                                <Image source={require("../images/searchNews.png")} style={{height:20,width:20}}/>
                            </View>
                        </TouchableOpacity>
                        <View style={{flex:1,width:30,height:Platform.OS=="ios"?44:55,zIndex:11,position:"absolute",top:0,right:44}}>
                            <Image source={require("./../images/overlayGradient.png")} style={{width:30,height:Platform.OS=="ios"?44:55}} resizeMode={Image.resizeMode.stretch}/>
                        </View>
                        {newsListView}
                        {this.getUserVerifiedModal()}
                    </View>
                );
            }

**Comment by windydang26** [comment]
i can't open left drawer if screen use scroll-tab-view. anyone same me?

**Comment by MissLlq** [comment]
has the same problem

**Comment by MissLlq** [comment]
### change the renderScrollableContent function like this ,and it work .this problem is because android use ViewPagerAndroid.


change the file 
### react-native-scrollable-tab-view/index.js         
 **renderScrollableContent** like this:

```
  _renderScrollableContent = () => {
    const scenes = this._composeScenes()
    return (
      <Animated.ScrollView
        horizontal
        pagingEnabled
        automaticallyAdjustContentInsets={false}
        contentOffset={{ x: this.props.initialPage * this.state.containerWidth }}
        ref={(scrollView) => {
          this.scrollView = scrollView
        }}
        onScroll={Animated.event([{ nativeEvent: { contentOffset: { x: this.state.scrollXIOS } } }], {
          useNativeDriver: true,
          listener: this._onScroll,
        })}
        onMomentumScrollBegin={this._onMomentumScrollBeginAndEnd}
        onMomentumScrollEnd={this._onMomentumScrollBeginAndEnd}
        scrollEventThrottle={16}
        scrollsToTop={false}
        showsHorizontalScrollIndicator={false}
        scrollEnabled={!this.props.locked}
        directionalLockEnabled
        alwaysBounceVertical={false}
        keyboardDismissMode="on-drag"
        {...this.props.contentProps}
      >
        {scenes}
      </Animated.ScrollView>
    )
  }_
```

delete android code which is use ViewPagerAndroid.


this issues  can help you:
[https://github.com/happypancake/react-native-scrollable-tab-view/issues/187](url)
