### ISSUE TITLE
Nested TabView render child

### ISSUE THREAD

**Issue by rulgf** [happypancake/react-native-scrollable-tab-view#711]
Hi, I'm trying to create a tab view that has its own tab navigator. After searrching through the issues i found other users had the same problem, but i didn't find any solution. 

I found that if i call `this.setState`, or any function that calls the render, it works fine. But only after this call.

Example:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9823771/28846213-33ec6ffe-76d0-11e7-89fe-d8e4a616686b.gif)

The Render Child call this function:

```
renderChild(){
  this.setState(this.state);
}
````

Any idea how to solve this?

Versions:
react-scrollable-tabview: 0.6.7
react-native: 0.45.1

**Comment by uimom** [comment]
The same problem

**Comment by yogeshmoradiya121** [comment]
same issue.
can't navigate to new screen out of tabview
it shows navigator.push is not defind
