### ISSUE TITLE
Underline does not show on initial load for Default Tab Bar (v0.6.5)

### ISSUE THREAD

**Issue by LittleDragonHuman** [happypancake/react-native-scrollable-tab-view#712]
When the page first loaded, the underline for default tab bar doesn't show. It happens occasionally. Any ways to solve this problem? 
Thx.

**Comment by lavarajallu** [comment]
Just follow this one:
this.props.scrollValue._value to this.props.scrollValue.__getValue() in the < ScrollableTabBar/>

see 4312d6c

Or Go to this node module package  Change this views  this.props.scrollValue._value to this.props.scrollValue.__getValue()

**Comment by wanghz2** [comment]
update to .__getValue() in node module package can resolve the issue, but, we can't pack node module package in our product to release, do you have have workaround to update caller side, for example, how to overwrite imported function in caller side. Thanks!

**Comment by aravindhkumar23** [comment]
For me, Initial load for scrollableTabBar underline is not working for first tab even after changing `this.props.scrollValue._value to this.props.scrollValue.__getValue() in the < ScrollableTabBar/> node_modules`

works perfectly after changing tabs.

**Comment by br2me** [comment]
@lavarajallu  so good~
