### ISSUE TITLE
Drag on textinput will show keyboard on next page

### ISSUE THREAD

**Issue by Shu-Ji** [happypancake/react-native-scrollable-tab-view#714]
This only happens on iOS, Android is OK.

![ios-drag-on-textinput](https://user-images.githubusercontent.com/1127594/28992483-049ad710-79d0-11e7-8958-afe8a3a8e3fb.gif)

```jsx
render() {
    return (
      <ScrollableTabView
        keyboardDismissMode="on-drag"
        keyboardShouldPersistTaps={false}
        renderTabBar={() => <DefaultTabBar />}
      >
        <MyPage tabLabel="MyPage" />
        <Text tabLabel='Tab #2'>favorite</Text>
        <Text tabLabel='Tab #3'>project</Text>
      </ScrollableTabView>
    );
}
```

and this is MyPage:

```jsx
render() {
    return (
      <View>
          <TextInput placeholder="this is a TextInput" style={{height: 50, borderWidth: 1}} />
      </View>
    );
}
```

I also change keyboardShouldPersistTaps to 'always', 'never', {true} or {false}, and all is useless of this isuue.

**Comment by ptaking** [comment]
@Shu-Ji did you find a workaround?

**Comment by Shu-Ji** [comment]
@ptaking No, I give up React Native and head to native development.....

**Comment by natasha08n** [comment]
It can be helpful for everyone else:
You can hide keyboard using `Keyboard.dismiss()` inside `onChangeTab` or `onScroll` events, onChangeTab handles new tab index, onScroll handles position and you can calculate what tab is currently active
And do not forget to write at the top of the file `import { Keyboard } from 'react-native'`
