### ISSUE TITLE
Can't scroll content of ScrollableTabView inside ScrollView on Android

### ISSUE THREAD

**Issue by areeb111** [happypancake/react-native-scrollable-tab-view#715]
Hello,
I have a problem with scrolling content of `<ScrollableTabView>` which is nested inside `<ScrollView>` on Android only,
This feature works fine in iOS.

- Screenshots attached.
- React Native v0.46
- react-native-scrollable-tab-view v0.7.4

![aug-09-2017 15-51-28](https://user-images.githubusercontent.com/2633763/29122361-b8d08a02-7d1a-11e7-82e5-f5ca894147d4.gif)

**Comment by sylvain75** [comment]
Hi, 
I had the same issue only on Android also, my config was 
- "react-native": "0.47.2",
- "react-native-scrollable-tab-view": "0.6.0"

Updating  to ```"react-native-scrollable-tab-view": "0.7.4"``` solved it. I guess updating you RN version may solve the issue @areeb111

**Comment by vikas17** [comment]
Hi, @areeb111 did you solve that issue. because i have the same problem with ScrollableTabView.

And i am using the latest version of react-native-scrollable-tab-view

**Comment by areeb111** [comment]
@vikas17 Hi, Still have the same problem even with RN 0.48,
I have made a workaround to check the maximum number of items inside the tab and set the height to the maximum height ever.
So in that way i don't need to scroll vertically in Android.

**Comment by vikas17** [comment]
Hi @areeb111  thanks for help but i have follow https://github.com/tibbus/react-native-scrollable-tab-view . for collapsable Tabbar and it work like a charm.

**Comment by kaanoner3** [comment]
I have same issue both android and ios my hierarchy is: <ScrollView> -> <ScrollableTabView> -><ListView> 
ScrollableTabView is inside ScrollView and ListView is inside ScrollableTabView

**Comment by Ekhui** [comment]
Hi, @kaanoner3 i got the same problem . have u fixed it?

**Comment by Ekhui** [comment]
Hi, @areeb111  i got the same problem . have u fixed it?

**Comment by tandat2209** [comment]
+1

**Comment by vdpdev** [comment]
Wrapper of your ScrollableTabView should have `style={{ flex: 1 }}`

**Comment by wyn0731** [comment]
"react-native": "0.57.8",
    "react-native-scrollable-tab-view": "^0.10.0",


still not working. +1

**Comment by nabettu** [comment]
```
"react-native-scrollable-tab-view": "^0.10.0"
```
still not working too🤔

I hotfixed with the following code.
```
<ScrollableTabView style={{ height: contentsHeight }}>
  <ScrollableTabViewContent
    onLayout={event => {
      const { height } = event.nativeEvent.layout;
      this.setState({ contentsHeight: height });
    }}
  />
</ScrollableTabView>```

**Comment by ptomasroos** [comment]
Its not working because we're using Android Pager which can't work with nested ScrollView's it needs to be rewritten with a ScrollView instead to support nesting

**Comment by sundarbee** [comment]
@nabettu Did u get the fix? I am also using the same version, facing the same issue

**Comment by phonganhhung9xtb** [comment]
i can't scroll tab content on android, but on ios it working well. how to i scroll my list data for each tab? seem it conflic with horizontal scroll of scrollabletabview.

**Comment by sundarbee** [comment]
@phonganhhung9xtb set static height for scrollable tab

**Comment by bachbonglong** [comment]
Has anyone fixed that ?  on IOS it working well but Android not work 

- ScrollableTabView : 1.0.0
I want vertical scroll of scrollabletabview.
