### ISSUE TITLE
Conflict with react native slider (Swiper, Carousel) and ScrollView

### ISSUE THREAD

**Issue by duycoder** [happypancake/react-native-scrollable-tab-view#730]
I set a Swiper inside a ScrollView and the ScrollView  is inside a ScrollableTabView.  And the Swiper disappear ! If i set the Swiper outside of the ScrollView but still inside the ScrollableTabView, it's work fine. But the Swiper stay still when i scroll the app, i dont' want it. Does anyone know how to fix this  bug !

**Comment by readthecodes** [comment]
I have the same problem.

**Comment by readthecodes** [comment]
I have the same problem in Android, but iOS works.

**Comment by niocncn** [comment]
+1

**Comment by shahwajahat99** [comment]
Did any one try to find the solution of this problem? I have been facing the issue on Android as well.

**Comment by meiqi1992** [comment]
have the same problem, @duycoder resolved it?

**Comment by nomi9995** [comment]
i also have the same issue

**Comment by zhuiye** [comment]
+1,Did have some suggestion to slove same problem

**Comment by Alexuisis** [comment]
So the issue is with all horizontal sliders.
One workaround is to lock the tab with nested swipeable content and onChangeTab to lock/unlock  tabs.
Another is to capture and handle PanResponder. Maybe someone will look into this and come up with solution?

**Comment by krakz999** [comment]
Same issue here.

**Comment by kabus202** [comment]
did you guys find a solution to this? it's not swiping smoothly

**Comment by caizhuorongs** [comment]
did you guys find a solution to this? it's not swiping smoothly
