### ISSUE TITLE
ScrollableTabView is not work in Android

### ISSUE THREAD

**Issue by readthecodes** [happypancake/react-native-scrollable-tab-view#733]
ScrollableTabView inside another ScrollableTabView is not work in Android,  ListView inside ScrollableTabView in Android is not work too. But, everything is ok in iOS, RN version is 0.44.

**Comment by dreamrulez07** [comment]
I am also facing the same issue! Why is this happening?

**Comment by candRabbit** [comment]
update version 0.7.4 you can resolve it

**Comment by Linnxh** [comment]
update to version 0.7.4，but the icon on the tab can't show ?   maybe i am in agency

**Comment by candRabbit** [comment]
@Linnxh  我直接用TabNavigator包含ScrollableTabView 你可以试试

**Comment by HuoJiazhi** [comment]
这个问题解决了吗 ，我嵌套了之后也消失里面的样式。

**Comment by readthecodes** [comment]
升级到0.7.4？npm上的最新版本不是0.6.7吗？

**Comment by dlimx** [comment]
You can add the fork `skv-headless/react-native-scrollable-tab-view#710/head` to upgrade to a 0.7.4 version, or whatever PR/commit makes sense for you. This one supports RN 0.48+ with `prop-types`

用  `skv-headless/react-native-scrollable-tab-view#710/head` 升级应该没问题。 会支持RN0.48+。

**Comment by wangjun1989** [comment]
Hi, have you solved your problem? I've had this problem
