### ISSUE TITLE
how to disable bold text when tabBarActive

### ISSUE THREAD

**Issue by mrkentlng** [happypancake/react-native-scrollable-tab-view#742]
How to dsiable bold text when tabBarActive, i cant find props to do this, only has props tabBarActiveTextColor and only accept string, not an a object to styles item when active!
Please suggest me solution to disable bold text when choice item in scrollable tab view

**Comment by edzh1** [comment]
@mrkentlng You can pass fontWeight: 'normal' to a ScrollableTabView.tabBarTextStyle like that:
`
<ScrollableTabView 
    tabBarTextStyle={{  fontWeight: 'normal' }}>{tabs}</ScrollableTabView>
`
