### ISSUE TITLE
When the ScrollableTabView is nested ,it can not show anything.

### ISSUE THREAD

**Issue by HuoJiazhi** [happypancake/react-native-scrollable-tab-view#746]
![image](https://user-images.githubusercontent.com/24695000/30317833-e9d162c4-97dd-11e7-9495-cb859c462f4b.png)

![image](https://user-images.githubusercontent.com/24695000/30317641-45153a30-97dd-11e7-91aa-80de94a961b0.png)

![image](https://user-images.githubusercontent.com/24695000/30317867-03fbee8a-97de-11e7-8313-60bfa90a0037.png)

**Comment by mykelaballe** [comment]
i'm having this issue also

**Comment by xuwankang** [comment]
请问解决了吗，我也是这样，啥都不显示

**Comment by HuoJiazhi** [comment]
When you using the ScrollableTabView component , you may encounter the problem that you can’t render the it’s content , the reason of this problem is that you must give it’s outer container a specified Height or you can’t render it’s content and you can just see the tab

Below is the correct usage of the < ScrollableTabView />:

            <View style={{flexDirection:'column',flex:1}}>
                {this._renderUser()}
                <View style={{flex:1}}>              I give the container of the ScrollableTabView a speicified height(speicified by the flexbox)
                    <ScrollableTabView
                        tabBarActiveTextColor="red"
                        tabBarUnderlineStyle={{backgroundColor: 'red'}}
                        initialPage={0}
                        renderTabBar={() => <DefaultTabBar textStyle={Styles.tabText}/>}>
                        <ScrollView
                            tabLabel="线索"
                            style={Styles.tabView}>
                            <ListView dataSource={this.state.dataSource}
                                      renderRow={this._renderRow}/>
                        </ScrollView>
                        <ScrollView
                            tabLabel="客户档案">
                            {this._renderCusProfile()}
                        </ScrollView>
                    </ScrollableTabView>                    
                </View>
            </View>

And it will render something like this:

**Comment by HuoJiazhi** [comment]
When you using the ScrollableTabView component , you may encounter the problem that you can’t render the it’s content , the reason of this problem is that you must give it’s outer container a specified Height or you can’t render it’s content and you can just see the tab

Below is the correct usage of the < ScrollableTabView />:

            <View style={{flexDirection:'column',flex:1}}>
                {this._renderUser()}
                <View style={{flex:1}}>              I give the container of the ScrollableTabView a speicified height(speicified by the flexbox)
                    <ScrollableTabView
                        tabBarActiveTextColor="red"
                        tabBarUnderlineStyle={{backgroundColor: 'red'}}
                        initialPage={0}
                        renderTabBar={() => <DefaultTabBar textStyle={Styles.tabText}/>}>
                        <ScrollView
                            tabLabel="线索"
                            style={Styles.tabView}>
                            <ListView dataSource={this.state.dataSource}
                                      renderRow={this._renderRow}/>
                        </ScrollView>
                        <ScrollView
                            tabLabel="客户档案">
                            {this._renderCusProfile()}
                        </ScrollView>
                    </ScrollableTabView>                    
                </View>
            </View>

**Comment by GGwujun** [comment]
这样子，_renderUser是不能滑动的，我要的是整个页面是可以滑动的。

**Comment by luongs3** [comment]
@ptomasroos why did you close this issue?
What's the solution?

**Comment by ptomasroos** [comment]
There’s no repo included in the issue.
