### ISSUE TITLE
Setting InitialPage does not work

### ISSUE THREAD

**Issue by Waltari10** [happypancake/react-native-scrollable-tab-view#750]
When I set initialPage to 2 it still renders the first tab in the main view. TabBar shows that second tab is selected though. If I swipe left or right it acts as if the first tab was selected all along and tabBar corrects itself. Same thing if I just press on one of the tabs in tabView.

Am I doing something wrong or is this a bug? My React-Version is 0.48.
EDIT: This does not happen on React-Native 0.47.2.

```
render() {
    return (
      <ScrollableTabView
        renderTabBar={() => <DefaultTabBar />}
        initialPage={2}
        ref={(tabView) => { this.tabView = tabView; }}
        tabBarPosition={'bottom'}
        prerenderingSiblingsNumber={Infinity}
      >
        <Text
          style={{textAlign: 'center', fontSize: 50, marginTop: '40%'}}
          tabLabel='Tab #1'
          key={'tab1'}
        >Tab1</Text>
        <Text
          style={{textAlign: 'center', fontSize: 50, marginTop: '40%'}}
          tabLabel='Tab #2'
          key={'tab2'}
        >tab2</Text>
        <Text
          style={{textAlign: 'center', fontSize: 50, marginTop: '40%'}}
          tabLabel='Tab #3'
          key={'tab3'}
        >tab3</Text>
        <Text
          style={{textAlign: 'center', fontSize: 50, marginTop: '40%'}}
          tabLabel='Tab #4'
          key={'tab4'}
        >Tab4</Text>
      </ScrollableTabView>
    );
  }

```

![tabview-problem](https://user-images.githubusercontent.com/8919286/30469960-800b5f14-99fb-11e7-84e1-63c9f7e25429.gif)

**Comment by gao520sun** [comment]
+1

**Comment by BeudyZlip** [comment]
+1

**Comment by computist** [comment]
+1

**Comment by luyl** [comment]
react-native-scrollable-tab-view@v0.7.4
react-native@0.48.4

1. open the source file `react-native-scrollable-tab-view/index.js`
2. find the code in the method `componentDidMount`:
```
this.setTimeout(() => {
  InteractionManager.runAfterInteractions(() => {
    if (Platform.OS === 'android') {
      this.goToPage(this.props.initialPage, false);
    }
  });
}, 0);
```
3. delete the code about os check
```
this.setTimeout(() => {
  InteractionManager.runAfterInteractions(() => {
    this.goToPage(this.props.initialPage, false);
  });
}, 0);
```
reload your app , this problem will be fixed, test on ios 11.0.2

**Comment by kelvinaliyanto** [comment]
@Waltari10 is this fixed? in my case, whenever i set the initialPage to other than 0, it will move the selected tab on the tabbar to correct position, just that the tabview shown is always the first tabview. however, once you click on any tab in the tabbar, it will show the correct tabview.

@luyl I am using

react-native-scrollable-tab-view@v0.8.0
react-native@0.49.0

So the code for index.js has already changed, and I cannot find the os check happening. Is it already fixed in this version?

**Comment by svallen** [comment]
Agreed. This is still not working as it should be.

**Comment by raghudevan** [comment]
+1 facing the same issue

**Comment by MaxiSantos** [comment]
any updates on this? Anyone has been working on this? Let me know where you left so I can take it from there so I don't have to repeat all what you have done and maybe I can get the fix or a PR for those ones who wants a fix now.

**Comment by kubilaytural** [comment]
Try this. It worked. Ideal for changing first pages.

componentDidMount() {
setTimeout(() => this.scrollableTabView.goToPage(1), 300);
}
...
.....
...
<ScrollableTabView
ref={(ref) => { this.scrollableTabView = ref; }}

**Comment by wenkangzhou** [comment]
@kubilaytural setTimeout is still not working as it should be,it still stay first page a few time.

**Comment by kubilaytural** [comment]
Did you try to raise the time? Will you share the code? @wenkangzhou

**Comment by xclidongbo** [comment]
@kubilaytural  Thanks. It`s worked for me.

**Comment by huang-ju** [comment]
```
    InteractionManager.runAfterInteractions(() => {
      requestAnimationFrame(() => {
        this.scrollableTabView.goToPage(this.props.route.params.flag);
      });
    });
```
