### ISSUE TITLE
it's can't use on react-native 0.48.0,please update

### ISSUE THREAD

**Issue by banli17** [happypancake/react-native-scrollable-tab-view#753]

**Comment by ABAD-i** [comment]
+1

**Comment by syzer** [comment]
@hongshu123 can you me kind to post exception / stack / message ?
can you check version yarn `yarn add react-native-scrollable-tab-view@0.7.4`

**Comment by octohedron** [comment]
@syzer There is no error messages, it simply doesn't work, can't switch tabs and content is blank.

**Comment by syzer** [comment]
@octohedron  not at the right moment,
Thanks for the warning!
in the meantime im gonna use 
```js    
"react": "16.0.0-alpha.12",
 "react-native": "0.47.1",
```

**Comment by SupriyaKalghatgi** [comment]
it was working fine with RN 0.47.4

upgrading to RN 48, this is the issue
https://github.com/skv-headless/react-native-scrollable-tab-view/issues/762

**Comment by dlimx** [comment]
It works fine for me on 0.50.0-rc1.

What is broken for you?

**Comment by luco** [comment]
Working fine on `"react-native": "0.49.3"`.

**Comment by syzer** [comment]
have you seen the bug of division by 0 fix ?
https://github.com/skv-headless/react-native-scrollable-tab-view/pull/764
maybe try to use this one ^^
