### ISSUE TITLE
How to remove white under line in android 

### ISSUE THREAD

**Issue by nakulkundaliya** [happypancake/react-native-scrollable-tab-view#754]
hello 
i am using scrollable-tab-view.
how to remove white underline in android ( it's not showing in ios)

http://prntscr.com/gnf7f3

**Comment by rodrigopk** [comment]
I believe I had the same problem as you. The white line is related to a border on the `DefaultTabBar`. You can pass the style for it in the props:
```
<DefaultTabBar
            style={{
                  borderWidth: 0,
                  borderColor: #00000000,
              }}
          />
```

**Comment by ustcwudi** [comment]
remove

style: tabBarPosition === 'top' ? styles.Tabs.topTabBarSplitLine : styles.Tabs.bottomTabBarSplitLine

in node_modules

**Comment by bohehe** [comment]
> borderWidth: 0

Great, this helps

**Comment by zfing** [comment]
ths

**Comment by akhilesh-leap-club** [comment]
import ScrollableTabView, {DefaultTabBar} from 'react-native-scrollable-tab-view';
 
<ScrollableTabView
            renderTabBar={() =>
                <DefaultTabBar
                    style={{
                        borderWidth: 0,
                        borderColor: 'red',
                    }}
                />
            }
...other props 
>
// Your components here....
.............

</ScrollableTabView>
