### ISSUE TITLE
ScrollableTabView initialPage={0} doesn't display the underline highlight

### ISSUE THREAD

**Issue by bksantiago** [happypancake/react-native-scrollable-tab-view#756]
Only happens if I use `ScrollableTabBar` on `renderTab` rather than `DefaultTabBar`

**Comment by dtrukr** [comment]
can be fixed by adding this to the beginning of "updateView" method:
`	if (offset.value === undefined) {
      offset.value = 0
    }`

**Comment by hanxk** [comment]
+1

**Comment by edraitsev** [comment]
I have the same issue, will be very cool if you fix it in next release

**Comment by sebringj** [comment]
@dtrukr was kind of right so thanks for that.
This additional shithack takes away the glitch behavior.
```
  componentDidMount() {
    this.props.scrollValue.addListener(this.updateView);
    this.updateView({ value: 0 })
    setTimeout(() => {
      this.shithack = true
    }, 1000)
  },

  updateView(offset) {
    if (!this.shithack) offset.value = offset.value || 0
```

**Comment by aurorasimran** [comment]
this didn't work for me. Initial page is does not have the underlineBar

**Comment by shobhitnpm** [comment]
It's working fine 
thanks,

**Comment by JaxGit** [comment]
@sebringj It seems that this.updateView({ value: 0 }) is not mandatory. 
Also it might be better to disable updateTabPanel before nohack is set to true, otherwise the tabPanel could be jittering when dynamic tabs width is smaller than windowWidth (too few tabs, or on iPad etc). 

so it could be like this:
```
  componentDidMount() {
    this.props.scrollValue.addListener(this.updateView);
    setTimeout(() => {
      this.nohack = true
    }, 1000)
  },

  updateView(offset) {
    if (!this.nohack) offset.value = offset.value || 0
    ...
    if (this.necessarilyMeasurementsCompleted(position, position === lastTabPosition)) {
      if (this.nohack) this.updateTabPanel(position, pageOffset);
      this.updateTabUnderline(position, pageOffset, tabCount);
    }
```

**Comment by malonguwa** [comment]
@skv-headless  @brentvatne @JaxGit @sebringj @dtrukr hi guys seems like the fix is working, is that possible we could have a PR for this fix and get reviewed and released?

**Comment by matthieugayon** [comment]
this worked better for me, no timeout hack : 

`
getInitialState() {
    // HACK
    this.startup = true

    this._tabsMeasurements = []
    return {
      _leftTabUnderline: new Animated.Value(0),
      _widthTabUnderline: new Animated.Value(0),
      _containerWidth: null,
    }
  },

...

measureTab(page, event) {
    const { x, width, height, } = event.nativeEvent.layout
    this._tabsMeasurements[page] = {left: x, right: x + width, width, height, }
    this.updateView({value: this.props.scrollValue._value, })

    // HACK
    if (this._tabsMeasurements.length > 1 && this.startup) {
      this.updateTabUnderline(0, 0, this.props.tabs.length)
      this.startup = false
    }
  }
`

**Comment by mashangfeng** [comment]
I still don't understand it

**Comment by dogbutcat** [comment]
@matthieugayon Thank you for providing good solution, but I found it's still not a secure way to work, cuz this red box turned out 

![ladpbbcc1dht3wvnbd7naqy_678_1086 jpg_620x10000q90g](https://user-images.githubusercontent.com/8625449/40950977-a9e31bee-68a7-11e8-9d01-08cb9ca0fb05.jpg)

when I log the ```_tabsMeasurements```, it goes out such a wired array ```[null,{"left":111.5,"right":194.5,"width":83,"height":49}]```. I don't know what hell goes when measure the first tab. Then I solve this with:
``` js
const position = Math.floor(offset.value||0);
const pageOffset = (offset.value % 1)||0;
```
or
``` js
if (offset.value === undefined) { offset.value = 0 }
```
