### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by fforres** [happypancake/react-native-scrollable-tab-view#761]
I've been using this library for a while, and now starting a new project, as I though of using it, I remembered all the PRs in waiting for a review, issues, and considering the [last merged pr is from June 15](https://github.com/skv-headless/react-native-scrollable-tab-view/pull/661), I begin wondering.

So Jus as the title says. is this project being maintained?

**Comment by datvtwakumo** [comment]
maybe not, there some codes in this project keep using Prototype from 'react' library and React.createClass method, which all have been moved to separated library in react version 16

**Comment by bjrn** [comment]
Looks like the author just updated the project to v0.8.0 which brings React 16 compatibility – so maybe this issue can be closed?
