### ISSUE TITLE
Combining with react navigation?

### ISSUE THREAD

**Issue by compojoom** [happypancake/react-native-scrollable-tab-view#763]
With react navigation one is able to navigate back to previous scens by swiping from left to right. that works very well, but on scens with rn-scrollable-tab-view - the tab view steals the swipe most of the time and does a transition between the tabs. 

React navigation uses the first 25px from the screen to capture the gesture for going back. Is it somehow possible to tell rn-scrollable-tab-view to now react for those 25px?

**Comment by syzer** [comment]
i used react native gesture for that

**Comment by albinekb** [comment]
How did you use react native gesture to do that? @syzer
