### ISSUE TITLE
 0.8.0 version  in Android emulator cannot toggle tab

### ISSUE THREAD

**Issue by duheng** [happypancake/react-native-scrollable-tab-view#767]
react-native-scrollable-tab-view  0.8.0 version in Android emulator cannot toggle tab

**Comment by syzer** [comment]
I cannot reproduce.
It works on my machine TM :)
```
renderTabBar={...}
scrollWithoutAnimation={true},
prerenderingSiblingsNumber={1}
```
What are your options ?

**Comment by AFMW** [comment]
I downgrade to 0.7.8 and it works! 😄

**Comment by syzer** [comment]
also toggling tabs has performance issues on older android devices
