### ISSUE TITLE
 how to set activeTab  ?

### ISSUE THREAD

**Issue by Clcll** [happypancake/react-native-scrollable-tab-view#771]
Hi!

I want to set activeTab in my DefaultTabBar component but initial position doesn't changed.
My code like 
`                <ScrollableTabView tabBarUnderlineStyle={style.underline}
                                   renderTabBar={props => <DefaultTabBar {...props}  activeTab={1} />} >
                    <Page1 />
                    <Page2 />
                </ScrollableTabView>`
Thx

**Comment by syzer** [comment]
Have you try to change ui with `flex order` to display `tab2` first?
