### ISSUE TITLE
the 0.8.0version in android platform bug

### ISSUE THREAD

**Issue by dengwenqi123** [happypancake/react-native-scrollable-tab-view#772]
first enter the android app, is normal, however ,Exit app and re-enter, show blank.I'm using the latest version
`"dependencies": {
		"react": "16.0.0-beta.5",
		"react-native": "0.49.3",
		"react-native-button": "^2.1.0",
		"react-native-code-push": "^5.1.3-beta",
		"react-native-device-info": "^0.12.1",
		"react-native-linear-gradient": "^2.3.0",
		"react-native-scrollable-tab-view": "^0.8.0",
		"react-native-splash-screen": "^3.0.1",
		"react-native-vector-icons": "^4.4.2",
		"react-native-webview2": "^1.1.1",
		"react-native-wechat": "^1.9.9",
		"react-native-yunpeng-alipay": "^2.0.0",
		"react-navigation": "^1.0.0-beta.15",
		"rnpm": "^1.9.0"
	},`

**Comment by dengwenqi123** [comment]
Who can help me?

**Comment by Vilitsa** [comment]
+1

**Comment by zhangjun920912** [comment]
delay load render scrollable-tab-view can resolve this question,you can set state,when open this page ,show an activityIndicator,after 500ms,change state,then render scrollable-tab-view,this is an temporary method,maybe ,wo can wait plaugs refresh

eg:if(this.state.delayShowScrollableTabView)
{
return(
<View style={{flex:1,backgroundColor:'#fff'}}>
<View style={{marginTop:screenHeight*0.4+99,alignSelf:'center',flexDirection:'row'}}>
<ActivityIndicator size={'small'}/>
Loading...


);
}else{
return (

<TouchableOpacity activeOpacity={0.95} style={newsNavRow.searchWrapper} onPress={()=> {this.props.navigation.navigate("NewsSearch_V2",{searchContent:"News"})}}>
<View style={{backgroundColor:'#204B7D',flex:1,alignItems:'center',justifyContent:'center',height:Platform.OS=="ios"?44:55,width:44}}>
<Image source={require("../images/searchNews.png")} style={{height:20,width:20}}/>


<View style={{flex:1,width:30,height:Platform.OS=="ios"?44:55,zIndex:11,position:"absolute",top:0,right:44}}>
<Image source={require("./../images/overlayGradient.png")} style={{width:30,height:Platform.OS=="ios"?44:55}} resizeMode={Image.resizeMode.stretch}/>

{newsListView}
{this.getUserVerifiedModal()}

);
}

**Comment by haolee1990** [comment]
is there any other solutions？

**Comment by xuwankang** [comment]
我也遇到了，有的页面可以用，有的不可以，不知道跟什么组件冲突了，你解决了吗？

**Comment by marlti7** [comment]
why close this, face same problem in android
