### ISSUE TITLE
0.8.0 active tab text font on Android

### ISSUE THREAD

**Issue by kisubs** [happypancake/react-native-scrollable-tab-view#773]
Hi, I have set `tabBarTextStyle` so that the text font changes.
`tabBarTextStyle={{fontFamily: 'Comfortaa'}}`

IOS seems to work fine, but on Android, the active tab text style changes back to its default text style.

![screenshot_20171025-124244](https://user-images.githubusercontent.com/24979247/32019734-fba07316-b982-11e7-99b3-a6249f21c4f4.png)
![screenshot_20171025-124237](https://user-images.githubusercontent.com/24979247/32019736-fe9232a8-b982-11e7-8b3e-bff72e06387e.png)

**Comment by TareqElMasri** [comment]
+1

**Comment by TareqElMasri** [comment]
I think I have found an answer, try to add a fontWeight to tabBarTextStyle
