### ISSUE TITLE
undefined is not a function (near '...React.createClass...')

### ISSUE THREAD

**Issue by cohendl** [happypancake/react-native-scrollable-tab-view#777]
I commented out everything inside the propTypes object in index.js, DefaultTabBar.js, and ScrollableTabBar.js and get the error in the subject. Any way to fix this?

React 16.0.0-beta.5
React Native 0.49
Using Expo 22.0.0

**Comment by prayuditb** [comment]
just update to version 0.8.0 with `yarn add react-native-scrollable-tab-view@0.8.0`
