### ISSUE TITLE
Why not scrollView?

### ISSUE THREAD

**Issue by compojoom** [happypancake/react-native-scrollable-tab-view#781]
@skv-headless - I installed the latest version 0.8 with react native 0.49 - it works fine on iOS, but I couldn't get it to work on Android. I don't see my tabs content. I see the Tabbar, but not the content. 

I forked your repository and applied the old code that was using scrollView

https://github.com/skv-headless/react-native-scrollable-tab-view/compare/master...compojoom:fixes_android?expand=1

I don't understand why in one of the releases you switched to AnimatedPager? What is it helping with? And why don't we keep the scrollView as it makes the whole code a lot easier to follow...

**Comment by mistryhiren94** [comment]
same issue.... help!!!!!

**Comment by suxindao** [comment]
+1

**Comment by miketoken** [comment]
Just tried it and it works well, but if you use swiper inside it won't scroll :/

**Comment by compojoom** [comment]
@miketoken - what do you mean swipe inside?

**Comment by Mobile-Mike** [comment]
Yes, i have two pages you can swipe between, no problem there. One of the item has a react-native-swiper inside and when It is not triggered. Worked well when i use the default tab setup.
What it needs is some sort of zindex to elevate above scrollable tab swipe. 
It works well when i add locked:true
Hard to explain :) hope that make sense.
