### ISSUE TITLE
doesn't work on android platform when the app reopen

### ISSUE THREAD

**Issue by haolee1990** [happypancake/react-native-scrollable-tab-view#782]
Everything is ok when i open my app for the first time. But the react-native-scrollable-tab-view doesn't work when i double-click the back button to quit the app and then reopen it，anyone can help?

**Comment by haolee1990** [comment]
I'm using the 0.8.0 version. android platform.

**Comment by shubhangi-asgola** [comment]
I am also facing the same issue in android. I am using 
android 6, 
react-native": "^0.42.0",
"react-native-scrollable-tab-view": "^0.7.3"

Even if I logout and login again the same thing happens and I get an error saying "Cannot read property getScrollableNode of undefined"
