### ISSUE TITLE
React.PropTypes error

### ISSUE THREAD

**Issue by svallen** [happypancake/react-native-scrollable-tab-view#783]
Getting this error...

"react": "16.0.0-beta.5",
react-native: 22.0.2

![img_1422](https://user-images.githubusercontent.com/6169781/32624494-75068026-c557-11e7-909b-14ad72379726.jpg)

**Comment by haolee1990** [comment]
update to version 0.8.0 can solve this problem

**Comment by svallen** [comment]
I am using 0.8.0.

It was a fresh install as of yesterday morning via npm pull.

![screen shot 2017-11-10 at 8 36 43 am](https://user-images.githubusercontent.com/6169781/32660821-5314fab0-c5f2-11e7-8701-a3173312b81f.png)

**Comment by luklapp** [comment]
It's working for me with 0.8.0!

Expo 22.0.1
React Native 0.49
React 16.0.0-beta.5
