### ISSUE TITLE
undefined is not an object (evaluating 'ViewPropTypes.style')

### ISSUE THREAD

**Issue by changliugang** [happypancake/react-native-scrollable-tab-view#784]
react-native: 0.39.0
react-native-scrollable-tab-view@0.8.0

**Comment by minhphung210** [comment]
same issuse

**Comment by danieldai** [comment]
same issue with react-native: 0.50 and react-native-scrollable-tab-view@0.8.0

**Comment by REBOOTERS** [comment]
[resolve](http://coding.imooc.com/learn/questiondetail/13895.html)

It seems that this is a definite bug

**Comment by mokinzhao** [comment]
same issue with react-native: 0.51 and react-native-scrollable-tab-view@0.8.0
