### ISSUE TITLE
tabBarUnderlineStyle Does the setting not go into effect?

### ISSUE THREAD

**Issue by caoxiaoke** [happypancake/react-native-scrollable-tab-view#790]
tabBarUnderlineStyle Does the setting not go into effect?

The default value remains after setting，ScrollableTabBar  tabBarUnderlineStyle={{backgroundColor: "red"} }

<ScrollableTabView
					initialPage={0}
					tabBarUnderlineStyle={{borderWidth:0,backgroundColor:'#ce3d3a'}}
					scrollWithoutAnimation={true}
					renderTabBar={()=><ScrollableTabBar
						underlineColor='#ce3d3a'
						activeTextColor='#fff'
						inactiveTextColor='rgba(255, 255, 255, 0.7)'
						underlineHeight={0}
						textStyle={{ fontSize: 15 }}
						backgroundColor='#ce3d3a'
						tabStyle={{paddingLeft:12,paddingRight:12,paddingBottom:0,}}
					/>}
				>

**Comment by banmunongtian** [comment]
@skv-headless ，Thank you for your help

Configuration is as follows：

"dependencies": {
    "react": "16.0.0",
    "react-native": "0.50.3",
    "react-native-scrollable-tab-view": "^0.8.0",
    "react-native-vector-icons": "^4.4.2",
    "react-navigation": "^1.0.0-beta.19"
  },
  "devDependencies": {
    "babel-jest": "21.2.0",
    "babel-preset-react-native": "4.0.0",
    "jest": "21.2.1",
    "react-test-renderer": "16.0.0"
  },
  "jest": {
    "preset": "react-native"
  }

**Comment by AdamantG** [comment]
maybe you can use `width`/`height ` in tabBarUnderlineStyle
