### ISSUE TITLE
undefined is not an object (evaluating 'React.PropTypes.func') 

### ISSUE THREAD

**Issue by xyy7260** [happypancake/react-native-scrollable-tab-view#793]
"react-native": "^0.46.4",
    "react-native-scrollable-tab-view": "^0.7.4",
![Uploading FCF086C3-84CB-42E4-8BD6-A1159D0C4307.png…]()

-
react-native-scrollable-tab-view  ，下的 DefaultTabBar.js 13:30
When I install the app to enter page hint to define,When I was in the Windows system did not encounter such a situation,In a Mac installation come when you least expect them to

**Comment by chenyanji** [comment]
React.PropTypes.func

import:
import PropTypes from 'prop-types';

change:
PropTypes.func

**Comment by xyy7260** [comment]
@chenyanji 
Thank you, I also try to the above method is not enough, I uninstalled mode_modules anew NPM install is done, because before I finally yarn installation with NPM
