### ISSUE TITLE
Detected a division by zero in Animated.divide node

### ISSUE THREAD

**Issue by kubilaytural** [happypancake/react-native-scrollable-tab-view#794]
Hello,

I get this error when I push a page from a page to a segmented page.

ERROR : Detected a division by zero in Animated.divide node

Help me.

**Comment by melvinxie** [comment]
I got the same problem. It happens sometimes if you put ScrollableTabView inside a ScrollView.
The same also happens for react-native-tab-view lib, not sure why.

**Comment by dammy95** [comment]
Hey! I am still having this problem unfortunately - I am currently using `react-native-scrollable-tab-view": "=0.8.0"`. Came across this issue while searching for a solution. It seems the solution that @kubilaytural suggested still has not been updated in npm? Is it possible if we can push for this ASAP?

**Comment by Tracklous** [comment]
in my case the fix was to give static height  & width to it's container.

like 

<View style={{height: 400, width: 400}}>
    <ScrollableTabView>
    {...props}
    </ScrollableTabView>
</View>

if you give flex as dimensions to it's container it will always give this error.
just try giving height & width to container and it will work.

**Comment by rheng001** [comment]
@Tracklous 

I'm also facing the same error. Do you know where in the code we should go to give a static height and width? Could you give a example? Thanks

**Comment by Tracklous** [comment]
@rheng001 
yes! In ScrollableTabView container, just give height and width to the view which you are creating in the ScrollableTabView instead of giving flex 1 just try with static height&width.

**Comment by rheng001** [comment]
@Tracklous 

Thank you! It works!

**Comment by wenkangzhou** [comment]
+1
