### ISSUE TITLE
 It is wrapped in ScrollView outside and can't operate normally.

### ISSUE THREAD

**Issue by showtan** [happypancake/react-native-scrollable-tab-view#795]
hi ! It is wrapped in ScrollView outside and can't operate normally.
For example:data cannot be displayed...

**Comment by wangbingqiong** [comment]
me too

**Comment by showtan** [comment]
can use the antd-mobile tabs and scrollView

**Comment by wangwpapril** [comment]
anyone has a fix to this ?

**Comment by nilaybrahmbhatt** [comment]
anyone has a fix to this ?

**Comment by huy-lv** [comment]
Hey everyone, try add height to the View contains ScrollableTabView :D

**Comment by OrangeFlavoredColdCoffee** [comment]
if child view is  ListView , add  props   scrollEnabled={false}.

**Comment by luongs3** [comment]
@showtan did you resolve this issue.
Please, i got the same one
