### ISSUE TITLE
iPhone X issue

### ISSUE THREAD

**Issue by xiaoerge** [happypancake/react-native-scrollable-tab-view#807]
Tab isn't rendering correctly in iPhone X.

![simulator screen shot - iphone 6 - 2017-12-19 at 15 35 05](https://user-images.githubusercontent.com/2677490/34177888-3f9efa6c-e4d3-11e7-8354-4593189d207c.png)
![simulator screen shot - iphone x - 2017-12-19 at 15 33 34](https://user-images.githubusercontent.com/2677490/34177889-3facce94-e4d3-11e7-88a1-79dcde3454da.png)

**Comment by xiaoerge** [comment]
Is there any progress or comment to this issue?
@ptomasroos

**Comment by ptomasroos** [comment]
You should wrap it inside the safe view provided by react native repo.
