### ISSUE TITLE
Not Working in Android.

### ISSUE THREAD

**Issue by sukumardv3101** [happypancake/react-native-scrollable-tab-view#808]
Here is my code:
<ScrollView
	bounces={false}
	removeClippedSubviews={true}
	style={{alignSelf:'stretch'}}>
	<View style={styles.content}>
		<ScrollableTabView
			initialPage={0}
			onChangeTab={(i,ref) => console.log(i)}>
				<PersonalInformation tabLabel="Personal" userInfo={this.props.userInfo}/>
				<ChangePassword tabLabel="Change Password"/>
		</ScrollableTabView>
	</View>
</ScrollView>

**Comment by sukumardv3101** [comment]
Inside ScrollView scrollable tabbar is Not working in android but it was working fine in ios. It was showing all state changes.

**Comment by kkotkkio** [comment]
+1

**Comment by TareqElMasri** [comment]
+1

**Comment by jiyarong** [comment]
me too

**Comment by basilbai** [comment]
me too

**Comment by msannikov** [comment]
+1

**Comment by akivanov** [comment]
+1

**Comment by msannikov** [comment]
Can be fixed with this pull request https://github.com/skv-headless/react-native-scrollable-tab-view/pull/797
@skv-headless is there any chance to get this PR in anytime soon? Thanks!

**Comment by parthv21** [comment]
I am still facing this issue.

My code:

 ```
      <SafeAreaView style={styles.container}>

               <ButtonGroup
                    onPress={(index) => {this.setState({selectedIndex:index})}}
                    selectedIndex={this.state.selectedIndex}
                    buttons={headerButtonNames}
                    buttonStyle={styles.buttonStyle}
                    selectedButtonStyle={styles.selectedButtonStyle}
                    textStyle={styles.buttonTextStyle}
                    selectedTextStyle={styles.selectedButtonTextStyle}
                    containerStyle = {{marginLeft: 0, marginRight: 0}}
                />
                <Text>
                    Called From: {this.props.navigation.getParam('calledFrom', 'No Source') }
                </Text>
                <ScreenName ScreenName={headerButtonNames[this.state.selectedIndex]}/>
                <ScrollableTabView
                        tabBarPosition = "top"
                        tabBarActiveTextColor = {Colors.GrayAccent}
                        scrollWithoutAnimation = {true}
                        tabBarUnderlineStyle = {styles.tabBarUnderline}
                    >
                    <RequestList tabLabel="Sub Requests" />
                    <ResponseTemplate tabLabel="Responses" />
                </ScrollableTabView>
            </SafeAreaView>   

```

It works well on iOS, but on Android, I get this:

![screenshot_1548431847](https://user-images.githubusercontent.com/17941287/51756883-07fc7d80-20e8-11e9-8408-c4cb6a943414.png)

**Comment by parthv21** [comment]
> I am still facing this issue.
> 
> My code:
> 
> ```
>      <SafeAreaView style={styles.container}>
> 
>               <ButtonGroup
>                    onPress={(index) => {this.setState({selectedIndex:index})}}
>                    selectedIndex={this.state.selectedIndex}
>                    buttons={headerButtonNames}
>                    buttonStyle={styles.buttonStyle}
>                    selectedButtonStyle={styles.selectedButtonStyle}
>                    textStyle={styles.buttonTextStyle}
>                    selectedTextStyle={styles.selectedButtonTextStyle}
>                    containerStyle = {{marginLeft: 0, marginRight: 0}}
>                />
>                <Text>
>                    Called From: {this.props.navigation.getParam('calledFrom', 'No Source') }
>                </Text>
>                <ScreenName ScreenName={headerButtonNames[this.state.selectedIndex]}/>
>                <ScrollableTabView
>                        tabBarPosition = "top"
>                        tabBarActiveTextColor = {Colors.GrayAccent}
>                        scrollWithoutAnimation = {true}
>                        tabBarUnderlineStyle = {styles.tabBarUnderline}
>                    >
>                    <RequestList tabLabel="Sub Requests" />
>                    <ResponseTemplate tabLabel="Responses" />
>                </ScrollableTabView>
>            </SafeAreaView>   
> ```
> It works well on iOS, but on Android, I get this:
> 
> ![screenshot_1548431847](https://user-images.githubusercontent.com/17941287/51756883-07fc7d80-20e8-11e9-8408-c4cb6a943414.png)

Okay it works now with the help of this: 

```
<ScrollableTabView
                        tabBarPosition = "top"
                        tabBarActiveTextColor = {Colors.GrayAccent}
                        scrollWithoutAnimation = {true}
                        tabBarUnderlineStyle = {styles.tabBarUnderline}
                        style={styles.scrollableTabView}
                    >
                    <RequestList tabLabel="Sub Requests" navigation={this.props.navigation}/>
                    <ResponseTemplate tabLabel="Responses" navigation={this.props.navigation}/></ScrollableTabView>

.
.
.

let styles = StyleSheet.create({
    tabBarUnderline: {
        backgroundColor: Colors.GrayAccent
    },
    scrollableTabView: {
        flex: 1,
        width: "100%"
    }
})

```

Should probably include in the docs.

**Comment by HaManhTuan** [comment]
Chỉ là thuộc tính: width: '100%' là được
