### ISSUE TITLE
Is it possible to center horizontally a custom tabBarUnderlineStyle?

### ISSUE THREAD

**Issue by JoaoTMDias** [happypancake/react-native-scrollable-tab-view#812]
I wanted to display an active tab as the image shows below:
![screen shot 2017-12-30 at 01 17 19](https://user-images.githubusercontent.com/2223881/34450376-3c3741fc-ecff-11e7-917d-83469baa59cd.png)
So there is a 4x4 underline style, 4px from the bottom of the tab.
Somehow, I can't seem to be able to center that little dot in the middle of the tab.
![screen shot 2017-12-30 at 01 18 44](https://user-images.githubusercontent.com/2223881/34450391-6849f49c-ecff-11e7-844b-9a2a5b27e875.png)

Does anyone know how can I achieve that?
It's nothing fancy, but I'm really struggling with this.

Thanks!

Btw, here is the style i'm applying there.
`<ScrollableTabView
          tabBarPosition="top"
          tabBarUnderlineStyle={{
            backgroundColor: 'rgba(231, 76, 60, 1)',
            height: 4,
            width: 4,
            marginBottom: 4,
            borderRadius: 2,
            flexDirection: 'column',
            justifyContent: 'center',
            alignItems: 'center'
          }}
          tabBarBackgroundColor="rgba(255, 255, 255, .92)"
          tabBarActiveTextColor="rgba(231, 76, 60, 1)"
          tabBarInactiveTextColor="rgba(145,145,145,0.64)"
          tabBarTextStyle={{ fontWeight: '500' }}
          renderTabBar={() => (
            <ScrollableTabBar style={styles.scrollableTabBar} />
          )}
        >`

**Comment by lucasfls** [comment]
Have you tried alignSelf: 'center' ?

**Comment by yuanshenbin** [comment]
@JoaoTMDias Hello, I've met this problem, too. Please forgive me. Have you solved it

**Comment by NguyenPhatBG** [comment]
tabBarUnderlineStyle: {
        backgroundColor: '$color_primary',
        height: 2,
        width: '30%',
        marginHorizontal: '5%',         
}
Hope can help you! I solved it 👍

**Comment by harikanammi** [comment]
hi @JoaoTMDias, can you resolve this issue??? Please help me....

**Comment by plimerence** [comment]
https://github.com/plimerence/react-native-scrollable-tab-view the Repositories
can solve u problem, just set <ScrollableTabBar
underlineStyle={{
width: 20,
}}
style={{ borderWidth: 0 }}
{...props}
/>

the core code is fixUnderLine = {
left: Animated.add(dynamicTabUnderline.left, Animated.divide(Animated.add(dynamicTabUnderline.width, new Animated.Value(-underLineWidth)), 2)),
width: new Animated.Value(underLineWidth),
};

**Comment by getumangon** [comment]
@JoaoTMDias How do you resolved it? I want to achieve same functionality.
Can you please help me. Thanks in advance.
