### ISSUE TITLE
react native scrollable tabs doesnot scroll inside scrollview

### ISSUE THREAD

**Issue by Thanmai-C** [happypancake/react-native-scrollable-tab-view#813]
Hi,
I am trying to place the tabs inside a scroll view(parent), but the tabs doesnot seem to scroll with the parent scroll.
Saw an issue regarding this #187 , but no solution to it.
Please provide a solution such that it works on both android and ios.

**Comment by wtsoftware** [comment]
I have the same problem ,How to resolve it?IOS run ok but android can't scroll in ScrollView

**Comment by Thanmai-C** [comment]
Check the below link, it might help
https://github.com/skv-headless/react-native-scrollable-tab-view/pull/667#commits-pushed-5d8aeb1

**Comment by showtan001** [comment]
@Thanmai-C   collapsableBar?  
without effect      and  react-native-scrollable-tab-view without this Props

**Comment by shuiRong** [comment]
[rn-collapsing-tab-bar](https://github.com/ashrithks/rn-collapsing-tab-bar) can help you.
It bases on this repo.

**Comment by Josin22** [comment]
> I have the same problem ,How to resolve it?IOS run ok but android can't scroll in ScrollView

same !
