### ISSUE TITLE
Dynamic Tabs with ScrollableTabView when update State

### ISSUE THREAD

**Issue by sinhpn92** [happypancake/react-native-scrollable-tab-view#814]
I have problem with `ScrollableTabView` when render dynamic tabs. This is my code to implements my feature: 

    constructor() {
    	super();
    	this.state = {
    		tabItems: []
    	}
    }
    
    componentDidMount() {
        const {item} = this.props;
        if (item === undefined) return;
        this.setState(prevState => {
        	prevState.tabItems.push(item);
        	return {
        		tabItems: prevState.tabItems
        	}
        });
    
        this._loadRelatedItems(item.tag);
    }
    
    render() {
        const items = this.state.tabItems;
        if (items === undefined || items.length < 1) {
            return (
                <View>
                    <Text>Loading...</Text>
                </View>
            );
        }
        return (
            <ScrollableTabView
                initialPage={0}
                renderTabBar={this._renderTabBar}
                tabBarUnderlineStyle={{
                    backgroundColor: '#000',
                    height: 2
                }}
                tabBarBackgroundColor={'#ffffff'}
                tabBarActiveTextColor={'#353535'}
                tabBarInactiveTextColor={'#999999'}>
    
                {
                    items.map((item, index) => {
                        return (
                            <TabItemContainer
                                item={item}
                                navigation={this.props.navigation}
                                tabLabel={item.title}
                                key={item.id + '_' + index}/>
                        )
                    })
                }
    
            </ScrollableTabView>
        )
    }
    
    
    _loadRelatedItems(tag) {
    	fetch(API_ENDPOINT + tag)
    	    .then(items => {
    	        this.setState(prevState => {
    				return {
    					tabItems: prevState.tabItems.concat(items)
    				}
    			});
    	    })
    	    .catch(err => {
    	        console.log(err);
    	    });
    }

When `TabComponent` render first time, a tab view as `TabItemContainer` have render. After that, the items relate loaded, and state updated. Now all `TabItemContainer` are create including the ones that were created before. 

My Question: 
1. How to only create new items that added after load related items (not including the ones that were created before)? 
2. When `ScrollableTabView` render first time, i don't see `tabBarUnderline` at first tab, how can i fix it?
3. Have `ScrollableTabView` work fine when have a lot of tab?

**Comment by LFDCC** [comment]
me too

**Comment by GowthamGr** [comment]
me too same issue

**Comment by godot007** [comment]
me too

**Comment by masious** [comment]
It's a year later, and no one has the answer?!

Then how have you implemented dynamic scrolling?!

**Comment by jrb1995** [comment]
renderTabBar = () => {
    let isRenderTabBar = this.state.isRenderTabBar
    if (isRenderTabBar) {
      return (
        <ScrollableTabBar 
          tabStyle={{ paddingBottom: 0 }}
          style={{ borderWidth: 0, height: 42 }}
        />
      )
    } else {
      return <View></View>
    }
  }

**Comment by jrb1995** [comment]
added a status control display

```
renderTabBar = () => {
    let isRenderTabBar = this.state.isRenderTabBar
    if (isRenderTabBar) {
      return (
        <ScrollableTabBar 
          tabStyle={{ paddingBottom: 0 }}
          style={{ borderWidth: 0, height: 42 }}
        />
      )
    } else {
      return <View></View>
    }
  }
```
