### ISSUE TITLE
i has something wrong on react-native@0.52.0

### ISSUE THREAD

**Issue by liuaaaddxiaoer** [happypancake/react-native-scrollable-tab-view#825]
it can,t be use in react-native version 0.52.0

**Comment by favoriteMyself** [comment]
+1 
The new version of react-native does not support old syntax，Hopefully the next version will fix the problem.

**Comment by favoriteMyself** [comment]
I solved this problem by downloading react-native-scrollable-tab-view@0.8.0.

**Comment by HankinsPan** [comment]
i have same problem by Version0.53.0 ,react-native-scrollable-tab-view@0.8.0.
