### ISSUE TITLE
Do not display a child page on Android, only display tab

### ISSUE THREAD

**Issue by mvpdream** [happypancake/react-native-scrollable-tab-view#828]
Do not display a child page on Android, only display tab

**Comment by walter211** [comment]
ios two， version is 0.8.0

**Comment by mvpdream** [comment]
@skv-headless

**Comment by jinzunyue** [comment]
Me too and the underLineView don't move when touch other tabs.The phone is a little slow,but other apps works fine.

**Comment by basilbai** [comment]
I also have the same problem. I can't work properly at Android，version is 0.8.0

**Comment by gzLonglilin** [comment]
I also have the same problem,and the phone is a little slow,version is 0.8.0

**Comment by mvpdream** [comment]
![image](https://user-images.githubusercontent.com/16203724/35950880-b7f2ffb0-0cb3-11e8-8ab6-90ee169d5eb4.png)
![image](https://user-images.githubusercontent.com/16203724/35950890-c109269c-0cb3-11e8-90bf-e9bfca64ccdf.png)
That's what I did.

**Comment by AllenJCheng** [comment]
I also have the same problem , when I set 'ScrollableTavView' into ‘VIew’ then it does't work at Android , but run in ios is ok

**Comment by AllenJCheng** [comment]
@mvpdream 为了实现一些功能，我把ScrollableTavView嵌套在View中，在iOS中可以正常工作，但是在Android中ScrollableTavView的children page 就不显示了，请问你有遇到过了吗，有没有好的解决方法

**Comment by NextVictim** [comment]
I also have the same problem , when I set 'ScrollableTabView' into ‘ScrollView’ then it does't work at Android , but run in ios is ok.

**Comment by callcter** [comment]
if ScrollableTabView was nested in a ScrollView, you should add contentContainerStyle={{ flex: 1 }} to ScrollView. from [stackoverflow question](https://stackoverflow.com/questions/36014191/viewpagerandroid-is-not-rendered-under-scrollview-using-react-native/44300630#44300630)

**Comment by ChinaLike** [comment]
To solve this problem, what you should do.

``` javascript
componentDidMount() {
    this.timer = setTimeout(() => {
        this.setState({
            delayShow: true
        })
    })
}

render() {
    return (
        {
            this.state.delayShow && (<ScrollableTabView> ...</ScrollableTabView>)
        }
    )
}
```
