### ISSUE TITLE
ios软键盘覆盖

### ISSUE THREAD

**Issue by panhs** [happypancake/react-native-scrollable-tab-view#830]
ios软键盘覆盖的问题  用了KeyboardAvoidingView 但是textinput嵌套在scrollable-tab-view 内部的时候textinput还是完全被软键盘覆盖了（当软键盘弹起）

**Comment by mengerpiao** [comment]
使用IQKeyboard

**Comment by pttyy** [comment]
ios软键盘覆盖 bug 解决方案 在 index.js 中 239行 keyboardDismissMode="on-drag" 下 添加 keyboardShouldPersistTaps='always'
