### ISSUE TITLE
Height View Issue (Native Navigation + FlatList)

### ISSUE THREAD

**Issue by leonardocaldas** [happypancake/react-native-scrollable-tab-view#835]
Hey guys!

I'm having a very annoying issue, when using react native navigation + scrollable tabs with FlatList inside it, for some reason, the height of the view inside the tab crops in the end, which makes impossibile to scroll all the way to the end and see the content.

The only way I found to fix this was to manually set the height of the views, I had to do something like the below:
Window Height - Navbar Height - Tabs Height

Can anyone help me?

**Comment by liujett** [comment]
show with screen image?

**Comment by wjTime** [comment]
is the issue resole

**Comment by wjTime** [comment]
is the issue resolve？ i have the same problem as you，while i put the scrollable tab view inside the flatlist or the sectionlist as it item or the footer。when i change scrollable tab view ，all sub page view height is the same highest ，above all，i in one tab content load more data，and switch another tab content ，the page content heigh is the same to last tab content height ，can you help me？

**Comment by alexpchin** [comment]
I'm just adding a comment to this... I'm not 100% sure if I'm correct but I believe this might solve your problem?

```js
<ScrollableTabView style={{flex: 1 }}>
  <FlatList tabLabel="First" contentContainerStyle={{flexGrow: 1}} /> // Could be inside a named component...
<FlatList tabLabel="Second" contentContainerStyle={{flexGrow: 1}} /> // Could be inside a named component...
</ScrollableTabView>
```
