### ISSUE TITLE
using with react navigation and null this.props.navigation

### ISSUE THREAD

**Issue by barron9** [happypancake/react-native-scrollable-tab-view#836]
navigation is returning null, is not passing after first stack to sub-tabs
```
class Chats extends React.Component {
        const { navigate } = this.props.navigation;
 render() {

  renderItem={({item}) => <TouchableOpacity onPress={() => navigate('Chat')}><View style={{flex: 1,flexDirection:'row'}}>
```

> TypeError: undefined is not an object (evaluating 'this.props.navigation.navigate')

**Comment by barron9** [comment]
noone?

**Comment by dbecker215** [comment]
I'm having the same problem. Any update/response?

**Comment by TylerPin** [comment]
Pass parent reference to the child tab and inside child call navigate.
`<ScrollableTabView
               style={{ marginTop: 20, }}
               initialPage={0}
               renderTabBar={() => <DefaultTabBar />}
            >
               <Chat 
               parentRef={this} 
               tabLabel='Tab #1' />
               <Text tabLabel='Tab #2'>favorite</Text>
               <Text tabLabel='Tab #3'>project</Text>
            </ScrollableTabView>`

and in Chat class call navigate by `this.props.parentRef.props.navigation.navigate('ChatDetail'))`

**Comment by motogod** [comment]
@TylerPin nice solution! Thank you very much.
