### ISSUE TITLE
initialPage  problem

### ISSUE THREAD

**Issue by long-joan** [happypancake/react-native-scrollable-tab-view#838]
The initialization of the tab option will not roll to the corresponding position at the time of the sixth, is there a solution?

**Comment by kubilaytural** [comment]
Try this. It worked. Ideal for changing first pages.

componentDidMount() {
    setTimeout(() => this.scrollableTabView.goToPage(1), 300);
  }
...
.....
...
 <ScrollableTabView
          ref={(ref) => { this.scrollableTabView = ref; }}

**Comment by Versus2017** [comment]
though the page goes as I expect. the tab indicator still got problem, it always scroll to a wrong tab, or not scroll. is this project still maintained?
