### ISSUE TITLE
Toggling tabs not working after poping back in Android

### ISSUE THREAD

**Issue by AndrewJikun** [happypancake/react-native-scrollable-tab-view#839]
I have a react-native-scrollable-tab-view working well in screen A and then push to screen B. In Screen  B I do nothing and pop back to screen A. then in Screen A I can not toggle tabs in Screen A any more. It works well in IOS but bad in Android.

**Comment by AndrewJikun** [comment]
react-native-scrollable-tab-view version: 0.8.0. React native version:0.51

**Comment by AndrewJikun** [comment]
@skv-headless can you fix that?

**Comment by oankarberg** [comment]
+1

**Comment by fpauer** [comment]
+1

**Comment by cloudslade** [comment]
+1

**Comment by lukaleli** [comment]
+1

**Comment by jenswellmeyer** [comment]
+1

**Comment by jenswellmeyer** [comment]
I'm not yet sure what's happening, but it seems to be related to this issue:
https://github.com/zbtang/React-Native-ViewPager/issues/123

**Comment by jenswellmeyer** [comment]
Should be related to this:
https://github.com/facebook/react-native/pull/14867

**Comment by Tritty** [comment]
@fpauer   Perfect. It works for me!  Thank you so much!

**Comment by kubilaytural** [comment]
@fpauer Thank's. I works for me!

**Comment by harrydema** [comment]
@fpauer Can you please show the full class? As my event is not fired. I am passing the navigator through props to the child screens.
