### ISSUE TITLE
use 0.8.0 first tabBar Underline not display

### ISSUE THREAD

**Issue by afatshiba** [happypancake/react-native-scrollable-tab-view#845]
![image](https://user-images.githubusercontent.com/29405099/36625549-89a9cf66-195c-11e8-9dd4-c616ce9b7b13.png)

**Comment by LFDCC** [comment]
same issue

**Comment by CoderSwitch** [comment]
same issue

**Comment by CoderSwitch** [comment]
It seems that i have done this:

Changed
renderTabBar={() => <ScrollableTabBar />}

to
renderTabBar={() => <DefaultTabBar /> }

If u copypasting the code, watch what you are pasting. Closing.

**Comment by Maquert** [comment]
What is this noticeable change that I cannot see? Could you please elaborate?

**Comment by wakeupmycat** [comment]
same issue

**Comment by CoderSwitch** [comment]
It seems that i have done this:

Changed
renderTabBar={() => }
<ScrollableTabBar/>
to
renderTabBar={() => }
<DefaultTabBar/>
If u copypasting the code, watch what you are pasting. Closing.

**Comment by CoderSwitch** [comment]
change "ScrollableTabBar" to   "DefaultTabBar"。

**Comment by CoderSwitch** [comment]
I don't know why I can paste the copy directly, but I can't show these two words.
So I made another one.

**Comment by wakeupmycat** [comment]
![image](https://user-images.githubusercontent.com/31644475/37016517-94122140-2147-11e8-9e03-a5a4206c3b6c.png)

**Comment by kingctan** [comment]
same issue.

**Comment by girvo** [comment]
Me too

**Comment by JaxGit** [comment]
dup #756 ?

**Comment by malonguwa** [comment]
same issue

**Comment by bitting304** [comment]
same issue..

**Comment by jamessawyer** [comment]
+1 same issue.When this problem will be solved?

**Comment by Just013** [comment]
1.open the resource code ScrollableTabBar.js
2.find line 150 && line 212 && line 217 : 
3.change this -----code this.props.scrollValue._value  -> this.props.scrollValue.__getValue()
4.i,m Chinese boy Coder Li . no thanks.

**Comment by yubo725** [comment]
@Just013 good boy, 666

**Comment by ptomasroos** [comment]
A solution is merged, and will be released during the day!
