### ISSUE TITLE
Refresh tab content on change of props

### ISSUE THREAD

**Issue by sumanth234** [happypancake/react-native-scrollable-tab-view#847]
How to refresh the child component from inside ComponentWillReceiveProps function.i,e as soon as the props get changed , only the child component should get refreshed and not the whole component

It would be great if you can provide the solution.

**Comment by Balasnest** [comment]
+1

**Comment by leoAntu** [comment]
+1,The same problem, has been flashing

**Comment by Ashalbulk** [comment]
why do you close this one?

**Comment by yogendrajs** [comment]
Is this resolved? Need a fix for the same
