### ISSUE TITLE
next and previous arrow not showing 

### ISSUE THREAD

**Issue by yogeshR5** [happypancake/react-native-scrollable-tab-view#848]
react-native-scrollable-tab-view is not displaying tab header of ( right and left) next ( >) and the previous ( < ) arrow not displaying.

![screenshot 1](https://user-images.githubusercontent.com/34572252/36714960-1fc442a6-1bba-11e8-9018-8294d983a454.png)

**Comment by yogeshR5** [comment]
@ptomasroos  could you explain the above issue. it was fixed or not?

**Comment by ptomasroos** [comment]
@yogeshR5 this issue has no repository which show's the error so its impossible for us to guess what you expect to happen and how its implemented. Hence please open a new issue with source code.

If this is now working fine in the latest release, then its def not fixed.

**Comment by yogeshR5** [comment]
@ptomasroos Thank you for comments. 'll check and update.

**Comment by ptomasroos** [comment]
Feel free to make a example based on https://snack.expo.io/@ptomasroos/react-native-scrollable-tab-view-examples and open a new issue with the link to your fork
