### ISSUE TITLE
AnimatedViewPagerAndroid key should be changed on key changes

### ISSUE THREAD

**Issue by barbieri** [happypancake/react-native-scrollable-tab-view#851]
At https://github.com/skv-headless/react-native-scrollable-tab-view/blob/74a0b3fc3f5b69b49b93e0e5f9b0d9089da757c5/index.js#L247 we see:

```js
      return <AnimatedViewPagerAndroid
        key={this._children().length}
```

However if I change the items keeping their total number the same, the `AndroidViewPagerAndroid` won't pick the changes. I believe that component is buggy and that's why `key` was needed, but using the number is not enough.

My solution was to use `sceneKeys` instead:

```js
      return <AnimatedViewPagerAndroid
        key={this.state.sceneKeys.join(',')}
```

Patch:

```diff
--- index.js~	2017-06-15 11:21:34.000000000 -0300
+++ index.js	2018-03-07 13:05:24.000000000 -0300
@@ -245,7 +245,7 @@
     } else {
       const scenes = this._composeScenes();
       return <AnimatedViewPagerAndroid
-        key={this._children().length}
+        key={this.state.sceneKeys.join(',')}
         style={styles.scrollableContentAndroid}
         initialPage={this.props.initialPage}
         onPageSelected={this._updateSelectedPage}
```

**NOTE:** problem doesn't show on iOS

**Comment by est7** [comment]
save my time thank u

**Comment by MoonHoo** [comment]
@barbieri thx save my time, and I think 'this.state.sceneKeys.join(',')' is also has a problem,
my solution is as follows:
```
 _getAllSceneKey() {
    let keys = [];
    this._children().map((child, idx) => {
      keys = keys.concat(child.props.tabLabel + '_' + idx);
    });
    return keys.join(',');
  }
...

const keys = this._getAllSceneKey();

<AnimatedViewPagerAndroid
          key={keys}>
</AnimatedViewPagerAndroid>
```
and it works great for my android device

**Comment by ptomasroos** [comment]
Thanks for sharing

**Comment by MoonHoo** [comment]
> Thanks for sharing

and I create a PR to fix this
