### ISSUE TITLE
Back button behaviour in tabs

### ISSUE THREAD

**Issue by ritesh-malav** [happypancake/react-native-scrollable-tab-view#853]
In android whenever we press back button if we are on the any tab other then first it will take us to first tab and then it will remove the the tab page or any default behaviour. Shall that not be the case here also.

**Comment by riteshmalav** [comment]
I believe react navigation tabs also follows the same.

**Comment by riteshmalav** [comment]
Or atleast we can provide some props that will take care of this.

**Comment by AlexCernik** [comment]
I'm having the same problem. Any update/response?. In android whenever we press back button if we are on the any tab other then first it will take us to first tab
