### ISSUE TITLE
Problem on android（安卓上没有显示第一页的页面）

### ISSUE THREAD

**Issue by SwitchDestiny** [happypancake/react-native-scrollable-tab-view#854]
I have two page：
![code1](https://user-images.githubusercontent.com/25134250/37269707-b6277866-2606-11e8-8a1f-6eb7edcb8150.png)

the first page is not showing，Only a piece of white，but The second page is normal
![first](https://user-images.githubusercontent.com/25134250/37269271-9dfc8788-2604-11e8-9d6e-eff6a091cdee.png)
![second](https://user-images.githubusercontent.com/25134250/37269272-9e30261a-2604-11e8-9858-3df14558c0fe.png)

But there was no problem before.This is the problem today. only on android

RN 0.42.3 
react-native-scrollable-tab-view 0.6.0

**Comment by SwitchDestiny** [comment]
When I modify the code。
![hot](https://user-images.githubusercontent.com/25134250/37269532-bf1adcde-2605-11e8-9821-1098a5a82e2d.png)
![normal](https://user-images.githubusercontent.com/25134250/37269533-bf5a7498-2605-11e8-9780-cee0747ab77d.png)

Only when hot loading is normal，When I use reload, it will be the same as before.

**Comment by shafips** [comment]
same here :(

**Comment by j-schuster** [comment]
@shafips @SwitchDestiny Have you guys been able to find a solution this?

**Comment by SwitchDestiny** [comment]
@j-schuster @shafips 
I've solved this problem

![qq 20180427091402](https://user-images.githubusercontent.com/25134250/39339503-b1637294-49fb-11e8-8315-bf86c1cad875.png)


In this page，I have a ListView 。I set the background color for the Listview, so that led to this problem.
