### ISSUE TITLE
help me.please

### ISSUE THREAD

**Issue by pheromone** [happypancake/react-native-scrollable-tab-view#855]
你好,打扰一下,如果在ScrollView内部使用react-native-scrollable-tab-view.无法控制TabBar的高.请问怎么办?
Hello,Excuse me, if I use the react-native-scrollable-tab -view inside ScrollView, I can't control the height of TabBar. What should I do?
就像

ScrollView
    .~~~~render other

      <ScrollableTabView
                renderTabBar={() => <DefaultTabBar />}
            >
            <View tabbar="one">
                   <Text></Text>
                    <Text></Text>
                   <Text></Text>
                   .........
             </View>
            <View tabbar="one">
                  <Text></Text>
            </View>
     </ScrollableTabView>
  ScrollView

-------->
tab one is long
tab two is short

**Comment by GuoAxiang** [comment]
flex:0 然后设置高度

**Comment by orcunorcun** [comment]
@GuoAxiang can you give more detail or example?

**Comment by GuoAxiang** [comment]
@orcunorcun `renderTabBar={() => <WalletDetailBar
                        tabStyle={{ paddingBottom: 0 }}
                        textStyle={{ fontSize: 32 }}
                        backgroundColor={'#24252F'}
                        style={
                            {
                                borderWidth: 1, borderColor: ‘white', height: 96
                            }
                        } />}`
