### ISSUE TITLE
[iOS] Click on another Tab, but onPress does not response when FlatList during scrolling

### ISSUE THREAD

**Issue by malonguwa** [happypancake/react-native-scrollable-tab-view#857]
I use scrollableTabView 0.8.0, 

```
 <ScrollableTabView
                    renderTabBar={() => <ScrollableTabBar/>}
                    tabBarUnderlineStyle={{backgroundColor:'#FB7400',height:2}}
                    // tabBarTextStyle={{marginBottom:0,paddingBottom:0,marginTop:0}}
                    tabBarActiveTextColor={'#FB7400'}
                    tabBarBackgroundColor={'#EEEEEE'}
                    scrollWithoutAnimation={true}
                    initialPage={0}
                    page={0}
                    locked={false}
                >
                    <ScreenOne tabLabel="ScreenOne"/> // FlatList
                    <ScreenTwo tabLabel="ScreenTwo"/> // FlatList
                    <ScreenThree  tabLabel="ScreenThree"/> // FlatList
                    <ScreenFour tabLabel="ScreenFour"/> // FlatList
            </ScrollableTabView>

```
Tab's onPress does not response when I click it during the FlatList scrolling, I think this should be another classic issue between onPress event not working during FlatList scrolling....... Is there any walk around for this? so far only pressIn working for me... but it will make scrollableTabView can not be scrolled anymore... since pressIn will trigger at the moment when we touch the component and it will not trigger pan/drag gesture any more.....

Any help would be much appreciate!!!!

**Comment by lerpo** [comment]
me too

**Comment by JaxGit** [comment]
@malonguwa @lerpo do you guys have issues with the static/scrollable tab control itself, or with the contents inside any tab?
I don't have problems with the former case.
However I do have problems with the latter shows in [this gist](https://gist.github.com/JaxGit/7f3f4f84f9db53c35ad1f259d1aaf206) : 
Touchable onPress does not response: when coexists with a FlatList under the same Tab of react-native-scrollable-tab-view and the FlatList is scrolling (only on iOS, all good on Android)

Some refs may be related: 
https://github.com/facebook/react-native/issues/12884
https://github.com/facebook/react-native/issues/14240
https://github.com/dancormier/react-native-swipeout/issues/179

**Comment by JaxGit** [comment]
@malonguwa After I tried using onPressIn or onPressOut instead of onPress as you mentioned, it works for my gist example (SimpleExample or even ScrollableTabsExample) and production code. It doesn't freeze any thing at all (tab control or tab contents). 

Don't know what issue you have met, but thank you mate 👍

**Comment by malonguwa** [comment]
@JaxGit Thanks for the info, but once you using usch as onPressIn, does it will triger the click event but ignore t
