### ISSUE TITLE
[Android] Copy/Paste not appearing in InputBox

### ISSUE THREAD

**Issue by PatrikTes** [happypancake/react-native-scrollable-tab-view#859]
Hello,

I have found strange behaveiour with ScrollableTabView and InputBox inside.

1.) Any Textbox in the first tab is never displayed copy/paste dialog. 
2.) On the second and other tabs it's normally working.

I have this behaveiour ONLY on Android. On iOS everything works.

Has this someone?

Thx!

**Comment by PatrikTes** [comment]
has anyone this issue?

**Comment by turbozv** [comment]
@ptomasroos @PatrikTes I'm hitting the same issue on Android, any suggestion on the fix?
