### ISSUE TITLE
Dynamic loading of data

### ISSUE THREAD

**Issue by yuanshenbin** [happypancake/react-native-scrollable-tab-view#863]
Hello, bothered, bothered, at present a very annoying problem, ScrollableTabView inside data, network access, tabbar ScrollableTabBar, network load good data, sometimes can appear, can not slide, data all squeezed in a row, sometimes normal, I use tabShow to control render, is also no effect, excuse me, is there a way to solve it, excuse me, thank you, thank you, thank you, thank you

  <ScrollableTabView
                            page={0}
                            scrollWithoutAnimation={true}
                            renderTabBar={() => <ScrollableTabBar
                                tabStyle={{height: 41}} tabsContainerStyle={{height: 43}}
                                style={{height: 44}}/>}
                            tabBarUnderlineStyle={styles.lineStyle}
                            tabBarActiveTextColor='#e53935'
                            tabBarInactiveTextColor='#666666'
                            tabBarTextStyle={{fontSize: 16}}
                            onChangeTab={(prevPage, currentPage) => {
                                this.includeProductList.setChangeCategory(this.state.categoryTab[prevPage.i].categoryId)
                            }}
                        >
                            {this.state.categoryTab.map((item, position, items) => {
                                return (
                                    <Text key={position} style={styles.textStyle} tabLabel={item.categoryName}></Text>
                                )
                            })}

                        </ScrollableTabView>

**Comment by tangshenghao** [comment]
try this -> #362       

in ScrollableTabBar.js add 
`componentWillReceiveProps(nextProps) {
    // If the tabs change, force the width of the tabs container to be recalculated
    if (JSON.stringify(this.props.tabs) != JSON.stringify(nextProps.tabs) && this.state._containerWidth) {
      this.setState({ _containerWidth: null, });
    }
},`
