### ISSUE TITLE
Heigh TabView can not reset when change tab if using with ScrollView

### ISSUE THREAD

**Issue by ada2603** [happypancake/react-native-scrollable-tab-view#866]
Hi all, 
I am using scrollable tab view with scrollview. I have 2 tab.  tab 1 is higher tab 2 when i change tab from tab 1 to tab 2.  Height of tab 2 doesn't reset
<ScrollView style={{flex: 1}}>

    <ScrollalbeTabView>
        <View tabLabel="TAB1>
              <Text>TAB1</Text>
         </View>
         <View tabLabel="TAB2>
              <Text>TAB2</Text>
         </View>
    </ScrollalbeTabView>
</ScrollView>

I don't know how to fix it please help me thank all so much

**Comment by orcunorcun** [comment]
+1

**Comment by Binhluan1234** [comment]
i have a same problem, can someone help me fix it ?

**Comment by hpmax00** [comment]
+1
