### ISSUE TITLE
OnChangeTab is called twice in iOS

### ISSUE THREAD

**Issue by Balasnest** [happypancake/react-native-scrollable-tab-view#873]
I am getting weird issue in iOS. When I click any of the tab, OnChangeTab is getting called twice. In Android, its calling only once.

Version: **0.8.0**

**Comment by stupidWall** [comment]
I also have this problem, so how to solve?

**Comment by stupidWall** [comment]
I solve this problem.

**Comment by cielu** [comment]
> I solve this problem.

怎么解决的啊？

**Comment by FullMoon04** [comment]
I got same issue. Please reopen this issue.

**Comment by YanmaY** [comment]
> I solve this problem.
老铁，你咋解决的啊？

**Comment by YanmaY** [comment]
@stupidWall 老铁，你咋解决的啊？

**Comment by Hiroshi2033** [comment]
I'm faced this issue too. simple just maybe you are using **initialPage** as your page index. 
just need to replace **initialPage** to **page**.

**Comment by YanmaY** [comment]
@Hiroshi2033 Thank you very much
