### ISSUE TITLE
How can I get rid of the following lines, thank you?

### ISSUE THREAD

**Issue by azhengyongqin** [happypancake/react-native-scrollable-tab-view#876]
### How can I get rid of the following lines, thank you?

![pmf_ cp fw_ fzvfea09j2](https://user-images.githubusercontent.com/18138282/39164275-30b6cad4-47b1-11e8-8dd9-52ec2c73bce1.png)

**Comment by skylingfly** [comment]
try to modify the source code directly

**Comment by GuoAxiang** [comment]
给DefaultTabBar添加
`style={
                            {
                                borderWidth: 0
                            }
                        }`
