### ISSUE TITLE
dynamic flatlist inside tabview

### ISSUE THREAD

**Issue by karimkhamwani** [happypancake/react-native-scrollable-tab-view#880]
<ScrollableTabView
                    initialPage={0}
                    tabBarBackgroundColor="white"
                    // tabBarUnderlineStyle={{borderBottomColor: 'aqua'}}
                    tabBarActiveTextColor="#1CAADE"
                    tabBarUnderlineStyle={{ backgroundColor: '#1CAADE', borderColor: '#1CAADE', borderBottomWidth: 0.1, borderBottomColor: '#1CAADE' }}
                    renderTabBar={() => <ScrollableTabBar />}
                >
                    {
                        data.map((data, index) => {
                            return <View key={index} tabLabel={data.category} style={{flex:1}}>
                                <View style={{ flex: 1   }}>
                                    <FlatList
                                        data={data1}
                                        renderItem={({ item }) => <FeatureProductItem />}
                                        keyExtractor={item => item.id}
                                        numColumns={2} />
                                </View>
                            </View>
                        })
                    }

                </ScrollableTabView>;

--------
this code working fine on ios but in android it gives error
cannot have child that doesnt have yoganode to parent without a measure function

**Comment by ujjwalagrawal17** [comment]
Do you find any solution to this ??

**Comment by LudoLamerre** [comment]
Is there a solution for this issue ?
