### ISSUE TITLE
将该组件嵌套在ScrollView里在安卓上无法显示

### ISSUE THREAD

**Issue by mengerzhuanyong** [happypancake/react-native-scrollable-tab-view#881]
<---ScrollView>
    .... // other code
    <ScrollableTabView
        initialPage={0}
        tabBarInactiveTextColor = "#999"
        style = {GlobalStyles.scrollTabBarNav}
        renderTabBar = { () => <ScrollableTabBar />}
        tabBarActiveTextColor = {GlobalStyles.themeColor}
        tabBarUnderlineStyle = {GlobalStyles.tabBarUnderline}
    >
        <LivingTabView tabLabel={'全部'} {...this.props} />
        <LivingTabView tabLabel={'汇讲堂'} {...this.props} />
        <LivingTabView tabLabel={'汇娱乐'} {...this.props} />
    </ScrollableTabView>
<---/ScrollView>

"react-native": "0.52.1",
"react-native-scrollable-tab-view": "^0.8.0",
在苹果上没有问题，但在安卓上内容区域无法显示怎么处理啊！

**Comment by z5829984520** [comment]
我也遇到了这个问题，解决方法是在父级元素设定一个高度就会显示了，但是不太好，有没有别的解决方式

**Comment by afresh** [comment]
我遇到了相同的问题。
I have the same problem.

**Comment by Binhluan1234** [comment]
i have the same problem.

**Comment by mengerzhuanyong** [comment]
@bingoo2008 这样做虽然可以显示了，但是底部状态条不行了，

**Comment by 0es** [comment]
比较完美的解决方案：
1. ScrollableTabView外部包裹一层View
2. View设置初始height
3. ScrollableTabView的内部View使用onLayout动态获取内部View的height
4. 外部View的height根据当前内部View的height改变

Temporary perfect solution:
1. ScrollableTabView external wrapping a layer of View
2. View sets the initial height
3. ScrollableTabView's internal View uses onLayout to dynamically get the height of the internal View.
4. The height of the external View changes according to the height of the current internal View.
