### ISSUE TITLE
[Android]tab fontColor become shallow

### ISSUE THREAD

**Issue by qq326646683** [happypancake/react-native-scrollable-tab-view#882]
![default](https://user-images.githubusercontent.com/15717688/39692770-5f4efbd8-5214-11e8-870a-0fad498a5143.png)

**Comment by GuoAxiang** [comment]
因为源码里用的是button：
`  renderTab(name, page, isTabActive, onPressHandler) {
    const { activeTextColor, inactiveTextColor, textStyle, } = this.props;
    const textColor = isTabActive ? activeTextColor : inactiveTextColor;
    const fontWeight = isTabActive ? 'bold' : 'normal';

    return <Button
      style={{flex: 1, }}
      key={name}
      accessible={true}
      accessibilityLabel={name}
      accessibilityTraits='button'
      onPress={() => onPressHandler(page)}
    >
      <View style={[styles.tab, this.props.tabStyle, ]}>
        <Text style={[{color: textColor, fontWeight, }, textStyle, ]}>
          {name}
        </Text>
      </View>
    </Button>;
  },`
你把button换掉就行了

**Comment by qq326646683** [comment]
我自定义的tabbar，没用到button，还是有同样bug @GuoAxiang
