### ISSUE TITLE
OnChangeTab Issue

### ISSUE THREAD

**Issue by Murtaza09** [happypancake/react-native-scrollable-tab-view#888]
When the "Remote JS Debugging" is enabled application respond correctly but when bundled and disables the "Remote JS Debugging OnChangeTab Does not respond and application got crashed.

**Comment by GuoYingxu** [comment]
Got the same problems!

**Comment by pwsses** [comment]
Got the same problems!

**Comment by xiongxhc** [comment]
Here is the solution that works for me, took me quite sometime to figure out. 
```
<ScrollableTabView
       style = {{width: '100%'}} // need this, also Android BUG!!!
       onChangeTab={(event)=>{this.setStateForTabChange(event.i)}}
>
       <TAB1 tabLabel = "A" />
       <Tab2 tabLabel =  "B" />
</ScrollableTabView>
```
