### ISSUE TITLE
设置initialPage的问题

### ISSUE THREAD

**Issue by YanYuanFE** [happypancake/react-native-scrollable-tab-view#889]
当tab数量过多的时候，设置initialPage为很大的一个（超出屏幕），initialPage对应的tabbar没有在屏幕居中显示，如下：
![1527303001024](https://user-images.githubusercontent.com/17774285/40571844-a6f3564c-60d2-11e8-8d50-fe6f3fff9bbc.jpg)
 此处我设置的initialPage为7，上面的tabbar一共有15个，当前的tabbar就超出屏幕了，希望能得到下面的效果。
![1527302994609](https://user-images.githubusercontent.com/17774285/40571910-d58ed872-60d3-11e8-859a-3b13ff9ed346.jpg)

**Comment by YanYuanFE** [comment]
`
<ScrollableTabView
                    initialPage={7}
                    tabBarUnderlineStyle={{backgroundColor: '#FFF', height: 0}}
                    tabBarBackgroundColor={'#3F99F7'}
                    renderTabBar={() =>
                        <ScrollableTabBar
                            renderTab={this.renderTab}
                            style={{height: getDip(44), borderWidth: 0}}
                            tabStyle={{height: getDip(44)}}/>
                    }
                    onChangeTab={this.handleChangeTab}
                    tabBarActiveTextColor='white'
                    tabBarTextStyle={{fontSize: 17}}
                >
                    {times.map((tab, i) => {
                        return <TaskList
                            tabLabel={tab}
                            i={i}
                            key={i}
                            onPay={() => this.toggleModal('payModalVisible', true)}
                            onCall={(phone) => this.call(phone)}
                            onService={() => this.toggleModal('serviceModalVisible', true)}
                            onUploadSugar={() => this.toggleModal('sugarModalVisible', true)}
                            onUploadBlood={() => this.toggleModal('bloodModalVisible', true)}
                            onStart={this.handleStartService}
                            {...this.props}
                        />;
                    })}
                </ScrollableTabView>
`

**Comment by YanYuanFE** [comment]
`
renderTab = (name, page, isTabActive, onPressHandler, onLayoutHandler) => {
        const time = moment(name).format('M.DD');
        const weekdays = {
            "Sunday": '周日',
            "Monday": '周一',
            "Tuesday": '周二',
            "Wednesday": '周三',
            "Thursday": '周四',
            "Friday": '周五',
            "Saturday": '周六'
        };
        const week = moment(name).format('dddd');
        const ActiveTextStyle = isTabActive ? {color: '#FFF', fontSize: 17 } : {};
        return <TouchableOpacity
            key={`${name}_${page}`}
            onPress={() => onPressHandler(page)}
            onLayout={onLayoutHandler}
            style={styles.item}
        >
            <View style={{justifyContent: 'center', height: getDip(44)}}>
                <Text style={[styles.text, ActiveTextStyle]}>{time}</Text>
                <Text style={[styles.text, ActiveTextStyle]}>{weekdays[week]}</Text>
            </View>
        </TouchableOpacity>;
    }

`

**Comment by hzx1621260121** [comment]
我也是这样，找了好多天突然来到了社区

**Comment by vincent1988** [comment]
同样的问题+1

**Comment by hzx1621260121** [comment]
通过修改组件，问题已经解决，看我简书文章，多多支持https://www.jianshu.com/p/9b110a3656a8

**Comment by YanYuanFE** [comment]
![image](https://user-images.githubusercontent.com/17774285/42098213-cc1bad90-7bec-11e8-9e53-77112215c898.png)

WINDOW_WIDTH是这个文件中的全局变量。屏幕宽度。

**Comment by hzx1621260121** [comment]
@YanYuanFE 在这里提醒各位，如果你是npm引入的官方组件，请移步到https://www.jianshu.com/p/9b110a3656a8，如果你是从node_modules拷贝一份官方代码到自己的components下作为自己的组件，请参考@YanYuanFE 的方法。两种方法生命周期不同，所以代码也会不相同
