### ISSUE TITLE
JSX element type 'ScrollableTabView' does not have any construct or call signatures.

### ISSUE THREAD

**Issue by jakabjack** [happypancake/react-native-scrollable-tab-view#890]
using library with typescript.
import * as ScrollableTabView from 'react-native-scrollable-tab-view';

<ScrollableTabView /> will yield the error message from typescript: 
JSX element type 'ScrollableTabView' does not have any construct or call signatures.

**Comment by jmporchet** [comment]
https://www.npmjs.com/package/@types/react-native-scrollable-tab-view
