### ISSUE TITLE
新版0.8 与scrollview flatlist 冲突

### ISSUE THREAD

**Issue by Yinetsrl** [happypancake/react-native-scrollable-tab-view#892]
最新版本冲突， 给ScrollableTabView 高度会显示， 但是flatlist上拉就没有效果了。 请问应该要怎么样才能解决。
`<ScrollView style={{flex:1}}>
                <Animated.View  style={[styles.sweeperContainer,
                    {
                        transform: [{
                            translateY: searchY
                        }]
                    }
                ]}>
                    <Swiper 
                    autoplay={true}
                    activeDotColor="#ff871d"
                    style={styles.wrapper}>
                        <View style={styles.slide1}>
                        <Text style={styles.text}>Hello Swiper</Text>
                        </View>
                        <View style={styles.slide2}>
                        <Text style={styles.text}>Beautiful</Text>
                        </View>
                        <View style={styles.slide3}>
                        <Text style={styles.text}>And simple</Text>
                        </View>
                    </Swiper>
                </Animated.View >

                <View style={styles.itemsContainer}>
                <ScrollableTabView
                    style={}
                    initialPage={0}
                    renderTabBar={() => <ScrollableTabBar 
                        />}
                    tabBarActiveTextColor="#ff871d"
                    tabBarBackgroundColor="#ffffff"
                >
                    <View tabLabel="BEST SELLER">
                        <BestSeller /> //flatlist
                    </View>
                    <View tabLabel="HOT ON SALE">
                        <HotOnSale /> //flalist
                    </View>
                </ScrollableTabView>
                </View>
                </ScrollView>`

**Comment by afresh** [comment]
我遇到了相同的问题。
I have the same problem.

**Comment by OrangeFlavoredColdCoffee** [comment]
me too

**Comment by quhuainan** [comment]
me too

**Comment by WowJesse** [comment]
me too
