### ISSUE TITLE
第一次加载下划线不显示

### ISSUE THREAD

**Issue by xx-dr** [happypancake/react-native-scrollable-tab-view#893]
第一次加载下划线不显示，设置tabBarUnderlineStyle也不行，滑动或者点击其他后就可以了，只有第一次加载时不显示，这是什么原因？

**Comment by ParkourH** [comment]
我也是, 只能先用DefaultTabBar渲染,

**Comment by zzq18705510289** [comment]
me too，has anyone fixed?

**Comment by Versus2017** [comment]
me too, it is a bug, and hope that it can be fixed

**Comment by xx-dr** [comment]
@Edwardelric 这样虽然会显示第一个，但是左右滑动的时候，会出现下划线始终在第一个位置上的问题，实际上是已经切换了的，但下划线没有正确的显示

**Comment by xx-dr** [comment]
@ParkourH 如果要显示多个tab的时候，DefaultTabBar满足不了需求

**Comment by sclcoder** [comment]
https://github.com/skv-headless/react-native-scrollable-tab-view/pull/832

**Comment by lizhuoyuan** [comment]
waiting。。
