### ISSUE TITLE
<ANDROID> Views within tabs are not being rendered

### ISSUE THREAD

**Issue by AndyCrisan** [happypancake/react-native-scrollable-tab-view#895]
After I change height of a view(parent or child) on hotLive Reload, the tabs are being rendered. PS all the views have dimensions established in style(either with flex either with height and width )

HERE IS MY CODE

       <View style={{height:GLOBALS.HEIGHT*0.61,width:GLOBALS.WIDTH}}>
                        <ScrollableTabView
                            tabBarActiveTextColor={"black"}
                            tabBarUnderlineStyle={styles.tabBarUnderline}
                            initialPage={0}
                            onChangeTab={(i) => this.setSearchGroup(i)}
                            tabBarTextStyle={{fontFamily: 'CaviarDreams'}}
                            renderTabBar={() => <BlogTabBar/>}
                        >
                            <View tabLabel="chart-line-variant" style={{flex:1, backgroundColor: '#000'}}>
                                {this.favList()}
                            </View>
                            <View tabLabel="trophy" style={{flex: 1, backgroundColor: '#000'}}>
                                {this.favList()}
                            </View>
                            <View tabLabel="menu" style={{flex: 1, backgroundColor: '#000'}}>
                                {this.favList()}
                            </View>
                        </ScrollableTabView>
                    </View>

When opening the app.
![2018-06-11_1102](https://user-images.githubusercontent.com/32058478/41219448-00aade44-6d67-11e8-91d4-3939c4b9d818.png)

After changing height of a View
![2018-06-11_1103](https://user-images.githubusercontent.com/32058478/41219508-290050f4-6d67-11e8-9c95-351fab01a91f.png)

**Comment by mananjobanputra** [comment]
I also face this problem now. how do you solve it?

**Comment by samuelmataraso** [comment]
i have the same issue, how do you solve it?²

**Comment by krishnamanieee** [comment]
can make clear explain

**Comment by Edwardelric** [comment]
I don't want to set a const height, other ways can resolve it ?

**Comment by Edwardelric** [comment]
@callcter unluckily, didn't  solve this problem.

**Comment by Edwardelric** [comment]
@callcter unluckily, didn't  solve this problem.

**Comment by louiechristie** [comment]
*Investigation*

Looks like this third party libary:
https://github.com/skv-headless/react-native-scrollable-tab-view/pulse

Is no longer actively maintained and has not been upgraded to work with RN 0.51+ and has this issue:
https://github.com/skv-headless/react-native-scrollable-tab-view/issues/895
and this issue (which is probably a duplicate)
https://github.com/skv-headless/react-native-scrollable-tab-view/pull/797

And Github issue 797 has been fixed by this fork and branch:
https://github.com/compojoom/react-native-scrollable-tab-view/tree/fixes_android

By this dev:
https://github.com/compojoom

*Proposed Solution*

Changing this line in package.json:
{code:javascript}
    "react-native-scrollable-tab-view": "git+https://github.com/compojoom/react-native-scrollable-tab-view.git#fixes_android",
{code}

A quick test today showed it fixes 797 issue.  I will further dev test on Monday.

Perhaps it also fixes this issue 895 ?

**Comment by bearty** [comment]
Same issue.
@louiechristie not helped for me.

**Comment by ngothanhtai** [comment]
It works for me. Thanks @louiechristie alot!

**Comment by louiechristie** [comment]
@ngothanhtai , @rarira , glad my suggestion worked for you.

Also, as react-native-scrollable-tab-view library is no longer being actively maintained, I am looking for a replacement.

When I was at the React Native EU 2018 conference I learned about a thing that might be a good replacement.  It is the react-navigation library, createBottomTabNavigator component:
https://reactnavigation.org/docs/en/tab-based-navigation.html

If the react-navigation library, createBottomTabNavigator component above is not flexible enough a possible alternative may be the react-native-community/react-native-tab-view library:
https://github.com/react-native-community/react-native-tab-view
(I _think_ it is the lower level library used by react-navigation library, createBottomTabNavigator component)

**Comment by mrmurazza** [comment]
@louiechristie it works for me too, thanks

**Comment by sahil-kc** [comment]
If your `ScrollableTabView` is under a `ScrollView`, consider adding `contentContainerStyle={{ flex: 1 }}` to your `ScrollView`.

**Comment by rauchp** [comment]
@sahil-kc Thanks for that, worked great after adding that line!

**Comment by bean-sprouts** [comment]
https://github.com/ptomasroos/react-native-scrollable-tab-view/issues/881#issuecomment-419932168
It works for me.
