### ISSUE TITLE
in android its not working

### ISSUE THREAD

**Issue by barron9** [happypancake/react-native-scrollable-tab-view#909]
<ScrollableTabView
    style={{marginTop: 80,zIndex:30 }}
    initialPage={0}
    renderTabBar={() => <DefaultTabBar />}

code is example code, which works in ios but not in android nothing comes to screen

**Comment by liam-lee1** [comment]
I also have this problem, a blank

**Comment by WStupid** [comment]
Maybe you should add a state to render in componentDidMount.

**Comment by corasan** [comment]
I have the same problem, were you able to fix this?

**Comment by falay26** [comment]
Why would you close this? Same problem for me, works great on ios tho..

**Comment by marlti7** [comment]
Why would you close this? Same problem for me, works great on ios tho..
