### ISSUE TITLE
SyntaxError: A trailing comma is not permitted after the rest element (9:32)

### ISSUE THREAD

**Issue by wjyx1lalala** [happypancake/react-native-scrollable-tab-view#910]
i know you had resolve the bug Removed trailing comma, which is a breaking change for RN 0.56 , but why not publish a new npm version to fix? I could`t  build success when i use the latest version '0.8.0' now

**Comment by vasilich6107** [comment]
Is it so hard to add new tag?

**Comment by shx1545** [comment]
The same bug

**Comment by Huanqiang** [comment]
+1 @skv-headless

**Comment by iceVeryCold** [comment]
+1@skv-headless

**Comment by rderwin** [comment]
For anyone stuck there's a couple short term hacks to get past this if you are trying to upgrade your app to 0.56 

1. use npm's github URLs to grab the latest version in master https://docs.npmjs.com/files/package.json#github-urls
`"react-native-scrollable-tab-view": "git@github.com:skv-headless/react-native-scrollable-tab-view#master"
`
2. go into your node modules folder and remove the trailing comma
`react-native-scrollable-tab-view/SceneComponent.js`

**Comment by HS3** [comment]
+1 how?

**Comment by badaz** [comment]
Hi, tx for this very nice component, could you make an npm release including the commit fixing the trailing coma pb please ?

https://github.com/happypancake/react-native-scrollable-tab-view/commit/45a0d58effe9c34bda13e18745b50575ea61d2b3

**Comment by wikiwu** [comment]
yarn add happypancake/react-native-scrollable-tab-view#master

**Comment by prashantsingh0205** [comment]
@ptomasroos  when will the update be released? Still showing errors.
