### ISSUE TITLE
Disabled ScrollableTabBar Scroll

### ISSUE THREAD

**Issue by mazenchami** [happypancake/react-native-scrollable-tab-view#918]
I would like to disable the ability to scroll the tab bar from the props.

Adding `scrollEnabled={false}` to the `<ScrollableTabView />`.

Let me know if I need to open a PR for this or if someone found a solution...

**Comment by virdesai** [comment]
Enhancement PR: https://github.com/happypancake/react-native-scrollable-tab-view/pull/919
