### ISSUE TITLE
scrollTabBar does not work sometimes in Android

### ISSUE THREAD

**Issue by WaitInRaining** [happypancake/react-native-scrollable-tab-view#927]
as titile, when i set renderTabBar as scrollTabBar ,sometimes it does not work, not all ways

**Comment by WaitInRaining** [comment]
<ScrollableTabView
                    renderTabBar={() => <ScrollableTabBar textStyle={{}} style={{
                        height: 40,
                        backgroundColor: 'white',

                    }} />}
                    style={{
                        height: 10,
                        padding: 0,
                    }}
                    tabBarBackgroundColor='transparent'
                    tabBarActiveTextColor='#EE6723'
                    tabBarInactiveTextColor='#555555'
                    tabBarTextStyle={styles.tabBarText}
                    tabBarUnderlineStyle={styles.tabBarUnderline}
                    // initialPage={initPage}
                    //page={this.state.indexTab}
                    onChangeTab={(obj) => {
                        this.setState({
                            indexTab: obj.i,
                        })
                    }}
                >
                    {this.state.allTab.length > 0 && this.state.allTab}
                </ScrollableTabView>

**Comment by sunzhishuai** [comment]
一样的问题

**Comment by fightingljm** [comment]
你们解决了吗
