### ISSUE TITLE
ReactNative 0.56.0 version ',' need delete

### ISSUE THREAD

**Issue by GideonLiu** [happypancake/react-native-scrollable-tab-view#928]
![image](https://user-images.githubusercontent.com/16357389/44974870-828afc00-af93-11e8-9d3e-a1132dbf4cca.png)
ReactNative 0.56.0 version SceneComponent class line 9, this ',' need delete

**Comment by mozibrand** [comment]
I solved this problem, I'm not going to wait for the author, I used this branch
https://www.npmjs.com/package/react-native-scrollable-tab-view2

**Comment by elkinjosetm** [comment]
+1

**Comment by ptomasroos** [comment]
This has now been published, truly sorry for the delay on this: 0.9.0
