### ISSUE TITLE
Publish new version on npm

### ISSUE THREAD

**Issue by superandrew213** [happypancake/react-native-scrollable-tab-view#933]
Can we have a new version on npm?

**Comment by VesperDev** [comment]
+1 

in which version can I use the Collapsable Bar prop

Demo : [https://github.com/tibbus/react-native-scrollable-tab-view/blob/demo/demo_images/demo-collapsable.gif](url)

**Comment by feruzm** [comment]
yes, a lot of improvements are missing...it would be great to get them published otherwise everyone will push their own version or use github directly which is not optimal...

**Comment by ptomasroos** [comment]
This has now been published, truly sorry for the delay on this: 0.9.0
