### ISSUE TITLE
componentDidMount called twice on first tab

### ISSUE THREAD

**Issue by roc-chang** [happypancake/react-native-scrollable-tab-view#945]
The NewsListTab1's componentDidMount will called twice, how can i fix it? 
Here is my code.
`
<ScrollableTabView
                        initialPage={0}
                        tabBarBackgroundColor={ThemeUtils.CurTheme.themeColor? 
                       ThemeUtils.CurTheme.themeColor: '#2196F3'}
                        tabBarInactiveTextColor='mintcream'
                        tabBarActiveTextColor='white'
                        tabBarUnderlineStyle={{ backgroundColor: '#e7e7e7', height: 4 }} >
                        <NewsListTab1 key={'one'} tabLabel="one" /> 
                        <NewsListTab2 key={'two'} tabLabel="two" />
                        <NewsListTab3 key={'three'}  tabLabel="three" />
                    </ScrollableTabView>
`

**Comment by ptomasroos** [comment]
Can you please post a expo reproduction for this in order for us to help out?
