### ISSUE TITLE
Temporary solution for "trailing comma" error in react-native >= 0.56.0

### ISSUE THREAD

**Issue by x13945** [happypancake/react-native-scrollable-tab-view#946]
## Situation

While we use  `react-native-scrollable-tab-view <= v0.8.0`  in `React-native >= v0.56.0`, npm server will throw a error like below:

```shell
 error: bundling failed: SyntaxError: /node_modules/react-native-scrollable-tab-view/SceneComponent.js: A trailing comma is not permitted after the rest element (9:32)

    7 |
    8 | const SceneComponent = (Props) => {
  >  9 |   const {shouldUpdated, ...props, } = Props;
      |                                 ^
    10 |   return <View {...props}>
    11 |       <StaticContainer shouldUpdate={shouldUpdated}>
    12 |         {props.children}

```

### Reason for the error

From `React-native v0.56`, it migrate babel from 6.xx to 7.xx.

### Why this temporary solution

As the `react-native-scrollable-tab-view`  has fix the bug in master branch, but the new release is not available for now. And my project need the bugfix emergency. 

## How to fix the problem ?

1. Download the js script from here: [postinstall.js](https://gist.githubusercontent.com/x13945/1010710bbe496989548d076315abd904/raw/e8010a8c70201ac4d9132be547740fc70386ff59/postinstall.js)
2. Put the `postinstall.js` in you project directory like below : 

```shell
.
├── ./App.js
├── ./android
├── ./app.json
├── ./index.js
├── ./ios
├── ./node_modules
├── ./package.json
├── ./scripts
 │   └── ./scripts/postinstall.js
└── ./yarn.lock
```
3. Add `postinstall.js` to you `package.json` like below:

```json

{
  "scripts": {
    "flow": "flow",
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "postinstall": "node scripts/postinstall.js",  // Here is what we add 
     ... ...
  }
}

```

4. Rerun `npm install` to install all your dependencies to active `postinstall.js`

## Last 

You guys need to remove what you add in above after `react-native-scrollable-tab-view` release new version. But it will not hurt you if you not remove these.

## Reference

#910 #932 #936  #937

**Comment by ptomasroos** [comment]
This has now been published, truly sorry for the delay on this: 0.9.0
